### ISSUE TITLE
Test reporting in CICE and Icepack

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#116]
The report_results test reporting needs to be reviewed.  Pushing back to the wiki has been disabled in CICE because there are problems.    Both CICE and Icepack need to be synchronized and made consistent with the wiki with stability and backwards compatibility required moving forward.

**Comment by eclare108213** [comment]
@apcraig can this issue be closed?

**Comment by apcraig** [comment]
I think we're OK now on the icepack trunk and PR 208 in icepack brings icepack scripts up to date with cice.
