### ISSUE TITLE
Suspicous history writing errors with pgi

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#117]
We are getting errors in a limited number of test cases and machines,

conrad_pgi_smoke_gx3_1x2_debug_diag1_run5day
conrad_pgi_smoke_gx3_2x1_debug_diag1_run5day
throws this error,
0: Null pointer for a2d (/p/home/apcraig/cice-consortium/cice.travis/cicecore/cicedynB/analysis/ice_history.F90: 1344)

but the following non-debug runs pass

PASS conrad_pgi_smoke_gx3_1x2_diag1_run5day run
PASS conrad_pgi_smoke_gx3_1x1_diag1_run5day_thread run
PASS conrad_pgi_smoke_gx3_2x1_diag1_run5day_thread run
PASS conrad_pgi_restart_gx3_2x1_diag1 exact-restart
PASS conrad_pgi_restart_gx3_1x2_diag1 exact-restart
PASS conrad_pgi_restart_gx3_2x1_diag1_pondcesm exact-restart
PASS conrad_pgi_restart_gx3_2x1_diag1_pondtopo exact-restart

Not seeing this problem with other compilers.  It could be pgi but we should look into it.

**Comment by mattdturner** [comment]
Debug runs with PGI include the `-Mchkptr` compile flag.  This flag is supposed to "Check for unintended de-referencing of NULL pointers."  `a2d` is an allocatable array, not a pointer.  Removing this runtime check results in the model running to completion.  This suggests to me that it is a problem with pgi, but that is just my opinion.

**Comment by nemequ** [comment]
If you want to add a PGI build to CI, I have a script at https://github.com/nemequ/pgi-travis which should make it pretty easy.

**Comment by anders-dc** [comment]
@nemequ, cool, thanks for sharing!

**Comment by nemequ** [comment]
> EDIT: It seems @nemequ also developed a similar repository for Intel compilers. A license is needed, but may be worth considering by the CICE-Consortium.

Unfortunately,Intel changed how their license server works after I wrote that. Now you can only have (IIRC) 5 active installations, and the only way to deactivate an installation is to log into their web site and manually remove it (i.e., we can't just uninstall the compiler after everything else is done). Unless you want to log in to Intel's web site every few builds you'll end up with build failures from Travis. I've pretty much stopped maintaining that repo since the change.

**Comment by apcraig** [comment]
I am not seeing this problem anymore.  We have updated some of the pgi compiler options over the last few months among other things.  I'm going to mark it wontfix and close it.
