### ISSUE TITLE
TravisCI test suite

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#118]
We are running into reproducibility problems on travisCI as well as a problem with a 1x1 test.  The test output from a broader suite is below.  We are turning off failed tests for now so travis will pass.  But this needs to be sorted out.

The main issues are the answers are changing according to the testing when they shouldn't.  It would be good to see/get output from the tests and maybe we can have travis ftp data out so we can look at it.  The other problem is the 1x1 test failure.  That fails with

>   Current forcing data year =         1997
>   
>  Finished writing ./history/iceh_ic.1998-01-01-00000.nc
> 
> mpirun noticed that process rank 0 with PID 13802 on node travis-job-anders-dc-cice-360441545.travisci.net exited on signal 11 (Segmentation fault).
> 

PASS travisCI_gnu_smoke_gx3_2x1_debug_diag1_run5day build
PASS travisCI_gnu_smoke_gx3_2x1_debug_diag1_run5day run
#---
PASS travisCI_gnu_smoke_gx3_1x2_debug_diag1_run5day build
PASS travisCI_gnu_smoke_gx3_1x2_debug_diag1_run5day run
#---
PASS travisCI_gnu_smoke_gx3_1x1_diag1_run5day build
PASS travisCI_gnu_smoke_gx3_1x1_diag1_run5day run
#---
PASS travisCI_gnu_smoke_gx3_2x1_diag1_run5day build
PASS travisCI_gnu_smoke_gx3_2x1_diag1_run5day run
FAIL travisCI_gnu_smoke_gx3_2x1_diag1_run5day bfbcomp travisCI_gnu_smoke_gx3_1x1_diag1_run5day.travisCItest different-data
#---
PASS travisCI_gnu_smoke_gx3_1x2_diag1_run5day build
PASS travisCI_gnu_smoke_gx3_1x2_diag1_run5day run
#---
PASS travisCI_gnu_smoke_gx3_1x1_diag1_run5day_thread build
FAIL travisCI_gnu_smoke_gx3_1x1_diag1_run5day_thread run
#---
PASS travisCI_gnu_smoke_gx3_2x1_diag1_run5day_thread build
PASS travisCI_gnu_smoke_gx3_2x1_diag1_run5day_thread run
FAIL travisCI_gnu_smoke_gx3_2x1_diag1_run5day_thread bfbcomp travisCI_gnu_smoke_gx3_1x2_diag1_run5day.travisCItest different-data
#---
PASS travisCI_gnu_restart_gx3_2x1_diag1 build
PASS travisCI_gnu_restart_gx3_2x1_diag1 run-initial
PASS travisCI_gnu_restart_gx3_2x1_diag1 run-restart
PASS travisCI_gnu_restart_gx3_2x1_diag1 exact-restart
#---
PASS travisCI_gnu_restart_gx3_1x2_diag1 build
PASS travisCI_gnu_restart_gx3_1x2_diag1 run-initial
PASS travisCI_gnu_restart_gx3_1x2_diag1 run-restart
PASS travisCI_gnu_restart_gx3_1x2_diag1 exact-restart
#---
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondcesm build
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondcesm run-initial
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondcesm run-restart
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondcesm exact-restart
#---
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondtopo build
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondtopo run-initial
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondtopo run-restart
PASS travisCI_gnu_restart_gx3_2x1_diag1_pondtopo exact-restart

**Comment by eclare108213** [comment]
Was this issue fixed or does travisCI still have the failing tests turned off?

**Comment by apcraig** [comment]
This seems to have been fixed with #125.  We are consistently passing a bfbcomp test that failed before.  We have reduced the number of tests a bit due to cost, but I believe this is fixed.  I will close this.
