### ISSUE TITLE
Crashes when using CCE

### ISSUE THREAD

**Issue by mattdturner** [CICE-Consortium/CICE#119]
@rallard77 and I have tested the most recent CICE code on 2 Cray machines using the CCE environment.  On both machines, every run fails to complete successfully.  The issue appears to be related to reading the input files.

Here is a snippet from the log file:
```
  max_blocks =                 4
  Number of ghost cells:       1

  read_global  11,  1,  -1.47038251591136854E+308,  7.17269300631787991E+307,  -1.72150506148753856E+308
  read_global  12,  1,  0.,  419430400.,  2820535222272.
  Processors (X x Y) =    2 x    2
```
For reference, here is the same snippet section from a run with the Intel compiler:
```
  max_blocks =                 4
  Number of ghost cells:       1

  read_global           11           1  -1.36148077740934
   1.56905100613449        916.469935499633
  read_global           12           1  0.000000000000000E+000
   25.0000000000000        168117.000000000
  Processors (X x Y) =    2 x    2

```

The first `read_global` output line is information regarding the grid file.  I have read the grid file in python, using both big endian and little endian:
```
Big-Endian: Min = -1.36148077741
Big-Endian: Max = 1.56905100613
Little-Endian: Min = -1.47038251591e+308
Little-Endian: Max = 7.17269300632e+307
```

The CCE `Macros.*` files all have `-h byteswapio` included in the `FFLAGS` variable, which should correctly read big endian files.  I have tested compiles both with and without `-h byteswapio` and it does not have any effect.  So, for whatever reason, it seems that the CCE-compiled executable is always reading the file as little-endian.

**Comment by apcraig** [comment]
I have seen the same issues.  There are a number of issues on the current CICE master that need to be addressed.  I am going to start working thru some of them.  In parallel, I think we also need to review and extend the test suite to improve coverage.
