### ISSUE TITLE
gx3 grid/kmt and forcing do not match

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#135]
There are some grid points where the gx3 land mask and forcing data do not match.  We could re-create the forcing (maybe), or perhaps it's easier to fix the land mask data to fill in points that do not have forcing data from the files.  Those points are currently set to the internally defined default values for the forcing fields.  Or maybe we don't need to worry about this, since the gx3 configuration is only for testing.

**Comment by eclare108213** [comment]
Another reason to address this via the land mask:  we could also change some of the values in land-fast ice regions so that the ocean depth is less than 25 m.

**Comment by rallard77** [comment]
I'll take a look at this. Should be straightforward.

**Comment by eclare108213** [comment]
Moving to JRA-55 forcing should make this issue moot.  I'll close the issue.
