### ISSUE TITLE
Albedo output by surface type

### ISSUE THREAD

**Issue by proteanplanet** [CICE-Consortium/CICE#150]
We need to work on appropriate albedo output categorized by surface type that makes physics sense.  Currently, when a surface type does not exist, or when astronomical twilight has all but passed to night, albedos according to melt pond, snow or bare ice surface types are set to zero. Upon internal averaging for model output, for example, that bare ice albedo can then be less than melt pond albedo, which belies the actual physics of the Delta-Eddington radiation scheme.  We need a way to reconcile this problem that either filters out albedo zero-samples from mean output, or that includes the virtual albedo - the albedo a surface type would have if it existed - in the internal averaging.  This is a decision for the team leads, and should be discussed on a teleconference when possible.

**Comment by eclare108213** [comment]
Does the albcnt counter not work properly, or is it not applied to the fields you need?  It is intended to prevent zeroes from being included in the averages.

              ! back out albedo/zenith angle dependence
              if (avail_hist_fields(n)%vname(1:6) == 'albice') then
              do j = jlo, jhi
              do i = ilo, ihi
                 if (tmask(i,j,iblk)) then 
                    ravgctz = c0
                    if (albcnt(i,j,iblk,ns) > puny) &
                        ravgctz = c1/albcnt(i,j,iblk,ns)
etc

**Comment by dabail10** [comment]
This accounts for the sun above the horizon, but not the presence of snow/bare ice/ponds. Also, what do we average in or not when there is no ice?

Dave

**Comment by proteanplanet** [comment]
Dave is correct.  There are a number of options to address the problem.  The simplest option is to only allow bare ice, snow, and bare ice albedo to be output as instantaneous fields.  These  instantaneous fields are already correct in CICE in that a zero value flags night-time or a non-existent surface type, and otherwise gives the correct albedo from Delta-Eddington.  The most complex option is to include extra counter fields to indicate how many timesteps in the given averaging period include real physical values for each surface type.  The problem with that solution is: What do you do when the counter is different for each surface type, over, say, a one month average?     The intermediate option is to output what the albedos would be if the surface type did exist.  If we do do that, then the fields should be relabeled as 'virtual' and the field description made clear to indicate that it in no way indicates if the surface type exists throughout the averaging period.  I personally think this last option is best, in combination with keeping the instananeous field as it currently is.

**Comment by eclare108213** [comment]
Would it make sense to create a diagnostic tracer for tracking the albedo?  It would depend on the ice fraction and be calculated based on the fractions of surface types at each time step, and it would work analogously to Tsfc, which takes a particular temperature where there is no ice.  Advection doesn't matter for either Tsfc or albedo since they are determined purely thermodynamically, but we can still track them this way.

**Comment by proteanplanet** [comment]
I think the tracer idea is a really good one.  It will, of course, add computational expense, so we'll need a flag to switch it on, and I feel the default should be for it to be turned off.  The albedo tracers, combined with the option of outputing instantaneous albedo as mentioned above, would cover all we need to know about surface-type albedo.  I think this is important not just for BGC, but also for tracking differences between the two explicit melt pond options in CICE now.  The morphological difference between the two is substancial in RASM, and the ultimate reason for including them - albedo - need to be carefully accounted for.

**Comment by proteanplanet** [comment]
Further progress has been made on this, with Marina Frants determining that the instantaneous albedo-by-surface-type is also incorrect.  We believe this is caused by averaging by area of the thickness category in the output, rather than by surface type area within each category, and Marina and Dave are working together to rectifiy the problem.   Marika has suggested output effective albedo (outgoing flux/incoming) as a different option from the ones suggested so far.  Since Marina is working to solve a problem for a paper she is writing, she's working to first fix the instantaneous albedo-by-surface-type issue already in the code.  I believe the conduit by which changes resulting from this work enter the CICE Consoritium code will be:  Marina and Dave work together to test a fix to the problem for instantaneous albedo-by-surface-type in RASM and CESM respectively, and then make the fixes available to the consortium code  via Dave, who could submit then as a member of the Dev Team.

**Comment by eclare108213** [comment]
@proteanplanet says this can be closed
