### ISSUE TITLE
time manager concerns

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#162]
There have been some long standing time manager questions.  Particularly, the relationship between istep, istep0, istep1, idate, idate0, and dt when intializing, restarting, and changing calendars.  As well as how they impact history and restart file, their time axis, and what should be written to and used on restart files.  And finally how a coupled model differs from a stand-alone run and what should be set in the model coupling layer and initialization.  This probably impacts the coupled models more than others.  But I think it would be nice to have some clearly defined protocol for dealing with this in CICE6 once and for all.

Mostly, all the variables need to be consistent and they need to work with respect to the netcdf time axis convention.  They also need to work with different calendars, on initial and restart runs, initializing a new run from an old restart on a different date and/or with a different calendar.  Also, what happens when the timestep is changed in the middle of the run.

I will try to pull together some documentation that, when ready, can be added to the user guide.

**Comment by apcraig** [comment]
See https://docs.google.com/document/d/15HmyNDbU0x13BlKWZnYjrTpeetzGh6H9z4grVmqBdEc

**Comment by eclare108213** [comment]
see also #139, #23

**Comment by apcraig** [comment]
#289 noted a problem when writing a history or restart file on timestep 1 in some cases.  #289 results in a known bug being issued in the documentation.  But this should be revisited.  The underlying issue is

> The problem actually is that all the logic to turn on the history and restart flag is within an if test,
> 
> if (istep > 1) then
> 
> at about line 280 of ice_calendar.F90. If I change that to (istep > 0), it writes the first history file fine.

**Comment by apcraig** [comment]
#343 notes some issues with leap years.  We will want to make sure we can address leap years in general.  In particular, this comes into play with the internal time manager as well as forcing files (which may be missing leap days or may have them when we aren't using leap year calendars).

**Comment by apcraig** [comment]
I have updated the google doc (see above), would love to have some feedback.  I think I'm going to start working on this in the next few weeks.  I think it's becoming more important all the time.  I plan to build a unit tester, and testing within the model will need to be quite comprehensive.  It will not be a small task, but I think I can make reasonable progress.

**Comment by TillRasmussen** [comment]
Increment of time in initialization seems to be wrong. If you run 1 time step then time and istep will be increased twice. Once in initalization and once in the end of a time step.

A potential solution could be to remove the increment of time and  istep in the beginning of each time step instead of the end

**Comment by apcraig** [comment]
I think we can close this when #566 is merged.  See also #567.

**Comment by apcraig** [comment]
Addressed in #566
