### ISSUE TITLE
restart and run comparisons

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#164]
Restart and run comparisons are done using "cmp" on binary restart files based on 'ls -lt'.  This is OK for netcdf output, but binary produces multiple restart files, so only a subset of the state is checked.  Also, binary and netcdf runs cannot be compared using this technique.

We probably need to extend this to test "all restarts" somehow and/or add an option to compare the diagnostic log files.  We need to develop some requirements first.

@eclare108213, @mattdturner, @rallard77; feel free to add some ideas.

**Comment by mattdturner** [comment]
It wouldn't be very difficult to have the scripts setup to loop through all restart files (binary or netCDF) and compare each pair.  This would compare every restart file that is created, instead of (what I think is) the current behavior of only comparing the final restart file.  Or is the issue that CICE creates multiple binary restart files for each date-time group?

Comparing binary restart files to netCDF restart files is a bit more difficult.  We would have to write a script that could read all of the data from the binary files, match them with the variables in the netCDF files, and then perform the comparison.  I'm not familiar enough with the CICE binary files to know how much work would be involved.

**Comment by apcraig** [comment]
thanks @mattdturner.  The binary version produces multiple restarts per timestep, optional tracers each have their own file.  I think we need to be able to compare all the files if we are going to use restarts to check bit-for-bit.  I also agree comparing binary to netcdf is not a realistic option.  In that case, I'm wondering if we can compare the log files.  There are several issues including whether the frequency and amount of data written is adequate, whether two runs will truly overlap in start and end, how long of a time series we should compare from the log file, what fields to compare, and so forth.  I think if we can come up with a "log file" comparison to supplement the restart file comparison, that might be useful.  In my experience, if two runs are not bit-for-bit in physics, the diagnostics in the log file will diverge immediately.  So while we might not be able to absolutely tell that all aspects of two cice model runs are identical, we should be able to tell when they are not.  In fact, the restart comparison also does not guarantee that two runs are identical in all ways.  So all of the approaches has some compromises.

**Comment by eclare108213** [comment]
What would be the reason for comparing binary restart data with netcdf?  Is there a chance that those might not be BFB anyhow, because of the formatting, even if the runs are otherwise identical?
e

**Comment by apcraig** [comment]
The reason to think about doing this is to make sure a run with binary and a run with netcdf output are identical.  That requires other things like identical initial conditions.  Thinking about it more, maybe the ability to compare two runs with different IO is not really an important test case.  Although I do think there is some merit in having an ability to compare log files from two runs to check for same results.  There may be cases where we don't have restart files or where, like for binary, there are many restart files and maybe it's just easier to compare the log files.

**Comment by eclare108213** [comment]
I agree that comparing the log files would be useful because of the global sums, which could show differences in fields that aren’t in the restarts.  In my opinion, comparing binary and netcdf output is a lower priority than some of the other things that need to be done.

**Comment by mattdturner** [comment]
So it sounds like we want to always compare both the restart files AND the log files?

**Comment by apcraig** [comment]
#202 addresses this. Will close now.
