### ISSUE TITLE
NWS UFS w. CICE6

### ISSUE THREAD

**Issue by rgrumbine** [CICE-Consortium/CICE#168]
Testing FV3-ocean-CICE6(to be) in NWS platforms

**Comment by rgrumbine** [comment]
Now have all regression tests passing on phase2, but fail to compile (reprosum comment I made earlier today) on phase3 and theia.

**Comment by rgrumbine** [comment]
Apologies for not updating this (much) earlier: Regression tests now pass on all available systems. 

CICE6-FV3-MOM6 tests cannot proceed in NWS until after CMEPS integration is complete.

**Comment by eclare108213** [comment]
This issue appears to be complete, for now.  I'll close it.
