### ISSUE TITLE
Icepack issues

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#170]
I haven't figured out how to add Icepack issues to the CICE v6 project board, so here are Icepack items for the release:

- code coverage, https://github.com/CICE-Consortium/Icepack/pull/202
- emissivity namelist, https://github.com/CICE-Consortium/Icepack/issues/211

**Comment by duvivier** [comment]
Item 2 (emissivity namelist) was taken care of by PRs #176 and #208

**Comment by apcraig** [comment]
The code coverage tool is being deferred.  I will close this and let the code coverage tasks stand on their own.
