### ISSUE TITLE
BGC testing

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#174]
We need to add bgc tests to the CICE test suites.  We also need to finish addressing #130 for the bgc namelist at that time.  If someone helps me create a set of bgc namelist settings, I can help implement and validate.

**Comment by njeffery** [comment]
@apcraig , @eclare108213 :  I found some bugs in the bgc code that need to be addressed first.  Hope to submit a PR by Wednesday.

**Comment by eclare108213** [comment]
see PR #175

**Comment by apcraig** [comment]
I believe we can mark this as complete at this time.  We have skl and bgcz test working in CICE.
