### ISSUE TITLE
Machine support for flush command

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#177]
We have some CPP logic for IRIX64, CRAY, OSF1, SUNOS, LINUX, NEC_SX, UNICOSMP, and AIX in ice_fileunits.F90. First, I suspect we don't need to support all of these particularly as they all use:

call flush(iunit)

except for AIX which uses:

call flush_(iunit)

I would like to propose a change here to simplify this code which is just:

#ifdef CESMCOUPLED
         call sys_shr_flush(iunit)
#else 
         call flush(iunit)
#endif 

I am guessing that AIX is not needed. Thoughts?

**Comment by dabail10** [comment]
The thing is, that the current logic has nothing in the subroutine flush_fileunit as NAG reports that iunit is not used.

**Comment by eclare108213** [comment]
Let me understand -- the code never calls the subroutine flush_fileunit?  That's quite possible, since we rewrote the warning system completely.  If so, let's get rid of this subroutine.  It's ancient...  I don't remember what AIX is anymore.

**Comment by dabail10** [comment]
No, flush_fileunit is called, but it does nothing.

Dave

**Comment by dabail10** [comment]
AIX is the old IBM operating system.

**Comment by dabail10** [comment]
I also learned that since Fortran 2003, this is an intrinsic function. So, the syntax is now

flush(iunit)

with no "call". Do we need to worry about compiler support older than Fortran 2003?

**Comment by eclare108213** [comment]
Does it do nothing even in CESM?  It looks like the non-CESM part should be recoded to use the intrinsic version.  I wouldn't think we'd need to support 15-year old Fortran versions.
https://github.com/CICE-Consortium/CICE/blob/master/cicecore/shared/ice_fileunits.F90

**Comment by apcraig** [comment]
The flush code is probably overdue for a refactor.  It is obsolete.  I would suggest we do the following,

```
#ifdef CESMCOUPLED
  call sys_shr_flush(iunit)
#else
#if ndef NO_F2003
  flush(iunit)
#else
  ! custom code if needed
#endif
#endif
```

basically adding a new cpp (TBD) that turns off f2003 features.  In this case it's pretty easy to just set the flush_fileunit() call to a noop with NO_F2003.  We could also add a print statement indicating flush is a no op if F2003 or keep a place holder for local customization.  But I agree it's time to move away from the machine dependent specialization that is no longer needed/used.

**Comment by dabail10** [comment]
This is a good idea. A bigger issue I noticed is that all of the Fortran modules still have the F90 extension. This implies we are supporting back to Fortran 1990. We might consider renaming these to just F. Thoughts?

**Comment by dabail10** [comment]
I will implement the NO_F2003 ifndef and close this.
