### ISSUE TITLE
Threading issue in ice_restart_driver.F90

### ISSUE THREAD

**Issue by mhrib** [CICE-Consortium/CICE#185]
cicecore/cicedynB/infrastructure/ice_restart_driver.F90: line 500:
Miss (i,j) as private in OMP loop line 500 in :ice_restart_driver.F90

Replace
      !$OMP PARALLEL DO PRIVATE(iblk)
with
      !$OMP PARALLEL DO PRIVATE(iblk,i,j)

--o--

      !-----------------------------------------------------------------
      ! compute aggregate ice state and open water area
      !-----------------------------------------------------------------

      !$OMP PARALLEL DO PRIVATE(iblk)
      do iblk = 1, nblocks

      do j = 1, ny_block
      do i = 1, nx_block
         if (tmask(i,j,iblk)) &
         call icepack_aggregate (ncat,               &
                                aicen(i,j,:,iblk),  &
                                trcrn(i,j,:,:,iblk),&
                                vicen(i,j,:,iblk),  &
                                vsnon(i,j,:,iblk),  &
                                aice (i,j,  iblk),  &
                                trcr (i,j,:,iblk),  &
                                vice (i,j,  iblk),  &
                                vsno (i,j,  iblk),  &
                                aice0(i,j,  iblk),  &
                                max_ntrcr,          &
                                trcr_depend,        &
                                trcr_base,          &
                                n_trcr_strata,      &
                                nt_strata)

         aice_init(i,j,iblk) = aice(i,j,iblk)
      enddo
      enddo

      enddo
      !$OMP END PARALLEL DO

**Comment by apcraig** [comment]
Fixing this now.

**Comment by apcraig** [comment]
Fixed in #215
