### ISSUE TITLE
history strength units

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#197]
The units in this block of code in ice_history.F90 should be N/m:

      call define_hist_field(n_trsig,"trsig","N/m^2",tstr2D, tcstr, &
             "internal stress tensor trace",                         &
             "ice strength approximation", c1, c0,                   &
             ns1, f_trsig)
 
I haven't checked other docs to see if it's wrong there too....

**Comment by duvivier** [comment]
I'm taking care of this with my vector-history work that should be added as a PR later today. I'll double check the documentation too and probably add a mod to the PR 195 that I'm waiting to hear from Andrew about.

**Comment by duvivier** [comment]
Corrected by #198. The documentation is fine too.
