### ISSUE TITLE
another scripting question

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#213]
What happens when there is an entry in a file in configuration/scripts/options/set_nml.option that is not used in the code?  Is it simply ignored?  We have some options files with lines like
>  n_trdoc         = 2

but the variable used in the code is n_doc.  n_trdoc is not defined anywhere.

**Comment by apcraig** [comment]
I believe the namelist substitution will be skipped and ignored.  If we want to trap these cases and abort, that's probably a better approach.  thoughts?

**Comment by eclare108213** [comment]
We probably ought to trap them.  In this example, I think we're not running the tests we intend to run.

**Comment by apcraig** [comment]
OK, let me see whether I can figure out how to do that robustly.

**Comment by apcraig** [comment]
So, I have something working and we do have a few errors in our set_nml files.  It's good to implement this trap and fix this.  One big one is ocn_data_type vs sst_data_type.  I think this is what's also tripping up Alice and why we haven't picked up on that bug before.  I am fixing the problems I find.
