### ISSUE TITLE
mpirun vs serial ./cice

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#216]
When creating a serial case using -p 1x1, 'mpirun' is put into the cice.run script.  This works, but is it necessary?  Are there ramifications, other than that the job scheduler at LANL insists on there being a proper allocation for the job (i.e. I can't quickly run it on the front-end machine)?  I can live with it, I just want to be sure it's intended and has no unintended side effects.

**Comment by apcraig** [comment]
It's a good point.  We should be able to fix this and get rid of the mpirun for serial builds.  I will look into it.  I don't think there are any serious ramifications.  For machines that have mpi, launching a serial application with mpi is fine.  For machines that don't have mpi, they would not implement an mpirun in their launch.  Having said that, it's probably worth exploring whether we can selectively launch with or without mpi on the fly.

**Comment by apcraig** [comment]
Capability added and tested for conrad and gordon in #239.  Can be implemented by default on a machine by machine basis.  This will provide testing of the capability on an ongoing basis, at least on gordon and conrad.  Also good to test that serial jobs can launch with mpi, still doing that on other test platforms.
