### ISSUE TITLE
results.csh output

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#221]
The output from the results.csh script is confusing when it's executed while a test suite is running -- it returns FAIL for jobs that are still in process.  Can these be changed to PEND?

**Comment by apcraig** [comment]
I had that implementation until recently, but then thought that we need more clear pass/fail info.  If the default is pend, then any job that fails to submit will be left pending, not failing.  I think it's better to have the default be fail and then have a running job go to pend and and a completed job go back to pass or fail.  I think we just have to understand that when using results.csh while testing.

**Comment by eclare108213** [comment]
Okay.  Can we have the script print a message to that effect, if there are still jobs pending that are marked FAIL?

**Comment by apcraig** [comment]
When a test is created, the default result is FAIL.  As soon as the test is built, the status changes to PASS for build and PEND for run.  Then after that, the run and test results will depend on the results of the run.  It is still hard to know whether a PEND run is still pending or whether it was never submitted.  Users have to look at that.  These results need to interact with the reporting as well.  If someone can come up with a clear set of requirements, that address what is needed for both the results.csh script and report_results script, I can implement them.

**Comment by apcraig** [comment]
Good idea.  thanks.

**Comment by apcraig** [comment]
Fixed in #239
