### ISSUE TITLE
HYCOM forcing check for initial forcing

### ISSUE THREAD

**Issue by mhrib** [CICE-Consortium/CICE#273]
If "hycom" forcing is chosen, CICE checks if forcing is available in the future and abort if not.
A similar check should also be done to check, that forcing is also available at first timestep. This is fixed as below:

In file:
cicecore/cicedynB/general/ice_forcing.F90

Replace these 2 lines (line 4134):
      ! Check if current time do not exceed last forcing time 
      if ( hcdate>jday_atm(recnum+1)+p001 ) then

With these 3 lines:
      ! Check if current time do not exceed last forcing time 
      !  + check forcing is available before (or at) current forcing time
      if ( hcdate>jday_atm(recnum+1)+p001 .or. hcdate<jday_atm(recnum)-p001) then

... Done

**Comment by apcraig** [comment]
I just checked and this has not been added to the master yet.   I can do it, although I will not be able to test it because it involves hycom forcing.  How should we proceed?

**Comment by eclare108213** [comment]
I reopened this issue, pending a final test to make sure the hycom forcing works as expected:  @mhrib @TillRasmussen

**Comment by mhrib** [comment]
Now tested, that the HYCOM calendar check work as expected using the current CICE code (downloaded 3 days ago)

**Comment by mhrib** [comment]
Now tested, that the HYCOM calendar check work as expected using the current CICE code (downloaded 3 days ago)
