### ISSUE TITLE
Place test and test_suite in specific filesystem location

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#275]
When using `cice.setup` to create a test or a test_suite, the scripts creates folders in the current CICE directory ; there does not seem to be an option to put the folder and files for the test/test_suite in a different location, as is possible for cases. It would be great to have that possibility, because right now running quick tests on a development machine clutters up the git repository....
Discussion board link : [https://bb.cgd.ucar.edu/put-test-and-testsuites-specific-directory](https://bb.cgd.ucar.edu/put-test-and-testsuites-specific-directory)

**Comment by apcraig** [comment]
Fixed in PR #281 also in Icepack PR 253
