### ISSUE TITLE
Make the build process independent of the layout

### ISSUE THREAD

**Issue by guillaumevernieres** [CICE-Consortium/CICE#287]
As a CICE user, it would be useful if you could remove the layout specification from the build process 
and instead be a run-time configuration option.

**Comment by apcraig** [comment]
@guillaumevernieres when you say layout, are you implying grid and blocksize, or pe counts?  

With the latest release of CICE6.0.0, the blocks and grid are no longer build time specifications, they are set at runtime.  In fact, in automated testing we reuse the same binary with different grids, pe counts and different blocks, so we know the build does not depend on the grid, pe layout or blocks.  If you are asking about the ability to quickly change the pe count at runtime, that is a slightly different issue which the CICE scripts don't currently support automatically, but maybe something could be added.  Can you clarify what you mean by layout in your request.  thanks.

**Comment by JessicaMeixner-NOAA** [comment]
For me, it would be nice to not have to set the grid, layout and pe-count at compile time.

**Comment by dabail10** [comment]
As @apcraig said, we now have dynamic allocation in CICE6. We'll all be working towards bringing in CICE6 into our coupled systems in the near future. Of course with a unified NUOPC cap. ;)

**Comment by guillaumevernieres** [comment]
OK, good to know and thanks for the quick reply @apcraig . 
so "mpirun -np npes ./cice" should work for different npes?

**Comment by apcraig** [comment]
@guillaumevernieres, that is correct.  With the CICE6.0.0 release, the grid and blocks are dynamically allocated and set at runtime in namelist.  What is not set at runtime is the batch settings and the job launch command which generally also depend on the pe settings and are defined when cice.setup is run.  But that is also not a build time issue.  You can build the model, change the grid and/or block sizes in the namelist then manually change batch/launch command and the model should run.  

If you are running CICE6 in a coupled framework, the standalone build/scripts won't really matter, how that works depends on the coupled framework.  

We could add a feature that would allow a user to reset the pe counts after the case is created.  It would like be implemented something like "edit the cice.settings file and change pe counts, run a script that recreates the run script, submit".  That would automate the run script re-setup.  If this would be a useful feature, we can consider it for the cice scripts, although I'm not convinced it's high priority.

**Comment by apcraig** [comment]
I am going to close this issue for now.  If there are future feature requests, please feel free to add another issue.   It sounds like the ability to dynamically allocate grids and blocks addresses the original request.
