### ISSUE TITLE
FSD:  miscellaneous

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#298]
- [x] Move l_conservation_check into namelist
- [x] Add/clean up FSD sanity checks
- [x] Add FSD timers

**Comment by apcraig** [comment]
@eclare108213, do you have a preference what the namelist should be called or in what namelist group it should appear.  By default, I'll use l_conservation_check and put it in dynamics.  But maybe we need to change the name to something a little clearer, maybe "conservation_checks" or "tracer_conservation_checks"?  Should it be in the dynamics namelist group?

**Comment by eclare108213** [comment]
It could just be conservation_check.  The l_ just indicates it's a logical flag, not something we have to have.  It could also be shorter, like conserv_check.  I could go in the dynamics namelist, but in icepack it also is used for zbgc, so maybe it should go in the general-use namelist (setup_nml).

**Comment by apcraig** [comment]
Thanks @eclare108213, I'll probably go with conserv_check and put it in setup_nml.

**Comment by apcraig** [comment]
https://github.com/CICE-Consortium/Icepack/pull/318 and #450 have been merged.  @eclare108213, please close if you feel all tasks are complete.
