### ISSUE TITLE
poll_queue script / general csh usage

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#299]
I tried using the **`poll_queue.csh`** script on my machine (ubuntu 14.04) and it fails ; it just outputs
```end: No match.```
 However, when I run it under tcsh instead of plain csh (by changing the shebang), it works.

On my system I have the following links:
 /bin/csh -> /etc/alternatives/csh -> /bin/bsd-csh

So it seems the csh version that comes with ubuntu is not capable of running this script. I think this should be documented, and maybe we should change the shebang for this script (and maybe others? from what I read csh has a reputation of being buggy...)

**Comment by phil-blain** [comment]
The line 
```set res="$?"```
 in the **`cice.test`** script is also causing a problem with my csh:
``` Illegal variable name.  ```
It works fine with tcsh.

**Comment by apcraig** [comment]
Portability of these scripts is very important.  If you switch the poll_queue script to tcsh, everything works fine?  Any idea what's causing problems in that script for you?

Also, does $status work better than $? for you in your csh environment?

**Comment by phil-blain** [comment]
Also, on a different note:
The poll_queue script is only copied to the suite directory if the suite is created with the --report option (line 372 in cice.setup). I think this script is useful even if the user is not reporting the test results back to the wiki, so I think it should always be copied.

**Comment by apcraig** [comment]
This is being fixed in #300.  I have replaced $? with $status and have refactored the poll_queue so it does not parse the suite.log file.  I am also copying the poll_queue script into the test suite directory for all suites.

**Comment by apcraig** [comment]
PR #300 complete
