### ISSUE TITLE
longitude dependence of solar time

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#3]
From: Pedro Duarte <Pedro.Duarte@npolar.no>
Sent: Monday, May 22, 2017 8:13 AM

I have just noticed that in ice_forcing.F90, in the subroutine compute_shortwave there is the following equation to calculate solar time:
solar_time = mod(real(sec,kind=dbl_kind),secday)/c3600 &
                   + c12*sin(p5*TLON(i,j))
 
As I understand, the second term is to correct solar time as a function of longitude. However, I think there may be an error here since c12*sin(p5*TLON(i,j)) should return 6 hours when TLON = 90 and it returns ~8.5 hours. I wonder why not using a simple linear function here since solar time varies one hour per 15 degrees? Or am I missing something here?

**Comment by dabail10** [comment]
Just a thought here. This was used for the AOMIP protocol and I believe there are some corrections for the eccentricity of the Earth's orbit. There is an interesting page here:

http://www.pveducation.org/pvcdrom/2-properties-sunlight/solar-time

This formula gives GMT+12 precisely at 180 degrees. Elizabeth, do you recall discussions about this during AOMIP?

Dave

**Comment by eclare108213** [comment]
@dabail10 I do not recall conversations about this during AOMIP -- I pretty much just took the documentation that was given and coded it up.  If this formula is technically correct, why would it be returning the wrong value when TLON=90?

**Comment by dabail10** [comment]
You can assign this issue to me. I can't assign it to myself.

**Comment by eclare108213** [comment]
It seems like you ought to be able to claim it yourself if you wanted to do it...
@apcraig Do we need to have permissions set differently, or is this standard github procedure?

**Comment by phil-blain** [comment]
I think this can be closed as it was fixed in #323.
