### ISSUE TITLE
Remove ice_shr_reprosum.c code

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#302]
if possible after careful review of need and value.

**Comment by apcraig** [comment]
I have confirmed that on conrad with 4 compilers, we can remove the c code and get bit-for-bit results.  I don't believe the c code is triggered unless the x86 cpp is turned on AND the ddpdd option is used.   The ddpdd option can be set explicitly or it can be triggered with the reprosum option if "(radix(0._r8) /= radix(0_i8))".  But again, the c code is only needed if the x86 cpp is turned on.

It's not clear when that x86 cpp is needed.  It has something to do with how values are represented in the machine, the number of bits, and so forth.  The ddpdd algorithm requires some bitwise consistency between integers and reals.  I believe most machines will not require the x86 cpp these days, but I'm not positive.  I also don't know whether it will be easy to detect an error because these algorithms are only used for CICE diagnostics and will not impact the solution.

An alternative is to completely disable the ddpdd option.  I think that is likely a safer option and I will test that now as well.

**Comment by apcraig** [comment]
I have created a branch, https://github.com/apcraig/CICE/tree/reproc, that has what I would propose the mods would be to remove the ice_shr_reprosum86.c code.  I have confirmed on conrad with 4 compilers and 4 test suites that the results are bit-for-bit.  There are a few reasons to do this

- gets rid of the c code which makes building CICE a little more complex.
- eliminates questions about when the x86 cpp should be set, if ever, because it does not exist anymore
- deprecates the ddpdd global sum algorithm which is generally not as good as the reprosum algorithm.

There are a few reasons not to do this

- having c code tests the CICE6 build more comprehensively
- the reprosum algorithm will fail if radix of real*8 and integer*8 are not the same because it will switch to use of the ddpdd algorithm which is now deprecated
- in cases where the x86 cpp is needed, we will not have a valid method available.
- it eliminates an alternative global sum method, ddpdd.
- it creates some divergence from the reprosum implementation in other models

There is an alternative implementation which also eliminates the c code.  That is to assume the x86 flag is never needed and that will automatically allow the c code to be removed.  But I think this is also risky in other ways.

**Comment by apcraig** [comment]
I've been trying to understand this better and still don't have a good handle.  One basic reference is here that explains why the c code exists, https://en.wikipedia.org/wiki/Extended_precision.  The issue is that the ddpdd implementation assumes a particular rounding behavior that is violated with the 80 bit extended precision floating bit representation.  So, turning on the x86 cpp and the associated c code forces 64 bit representation for the ddpdd computation.  It's unclear what hardware still uses the 80 bit representation or if it might be just older PCs that CICE might or might not ever be run on.   I am refactoring the current implementation a bit.  I have decided if we do want to get rid of the c code (and I'm not necessarily advocating that), then we should support the ddpdd code as we do today with the 80 bit correction option turned off and removed.

**Comment by eclare108213** [comment]
@apcraig thanks for working through this issue.  I'm happy to defer to your best judgment, whether that means keeping the c code or dropping it.  Let me know if/when you'd like me to review the changes.

**Comment by apcraig** [comment]
I would like to propose we leave the c code as is.  There are some things about how it's implemented that could be improved and that may happen down the road leveraging work from other collaborators.  But I think it helps our build system to have a c file, even if it doesn't do very much at this point.  I would like to leave this issue open for now, but lower priority.

**Comment by apcraig** [comment]
If we run into problems with the code or the implementation, we can rapidly re-evaluate.

**Comment by eclare108213** [comment]
If you think the current implementation will remain stable for a while, I propose adding the 'wont fix' label and closing the issue.  It can be reopened if needed.
