### ISSUE TITLE
Problem dumping restart files 

### ISSUE THREAD

**Issue by AlfaAli** [CICE-Consortium/CICE#305]
Hi, 
I am running version 5.1, at  ~4km resolution for the Arctic.  The  model runs OK and outputs hourly and daily averages  (as netCDF) without any problem, for this I use the following:

  , histfreq         = 'h','d','x','x','x'
  , histfreq_n     =  1 , 1, 0 , 0 , 0
  , hist_avg       = .true.
  , history_dir    = './cice/'
  , history_file   = 'iceh'

I am also trying to dump restart files with this:

   , restart_dir    = './cice/'
  , restart_file   = 'iced'
  , pointer_file   = './cice/ice.restart_file'
  , dumpfreq       = 'd'
  , dumpfreq_n     = 1
  , dump_last      = .true.

However, the model does not dump any restart files. The log file looks normal and it even says restart files are written, for example:

   Writing ./cice/iced.2001-01-05-00000.nc
   Restart read/written      1508160   1357344000.00000
   0.000000000000000E+000

But actually, I do not find any file under '/cice/'. The model will only update pointer_file with the name of the restart file "./cice/iced.2001-01-05-00000.nc" but it does not successfully write the restart file.

Any help is appreciated.

Note that I also run the same code with ~6km resolution and I don't get this problem.  

-Alfati

**Comment by apcraig** [comment]
Community Support is provided thru the bulletin board.  Please feel free to ask for help there,

https://bb.cgd.ucar.edu/forums/cice-consortium-model-development

I will close this issue.

**Comment by eclare108213** [comment]
@AlfaAli, I hope you were able to resolve this problem.  If not, let's take it to the bulletin board for further discussion.  We prefer to use the github issues to track our code/doc/repository tasks, rather than answering users' questions.  The bulletin board also allows the broader community to look for  answers, if they have similar questions.  If you haven't found a solution and don't want to use the bulletin board, could you tell me why?  You can email me at eclare at lanl gov.

**Comment by AlfaAli** [comment]
@eclare108213, the issue is resolved.  It turned out that the problem is due to the restart files becoming too
 big (each >2GB) when increasing the grid resolution and therefore the netCDF failed to create them. Luckily this is solved by turning on the 64-bit offset flag in the setup file. This flag is set to false by default.

The model does not give any clue on why it fails to create the restart files, and it took me a lot of time to track the code and figure it out. So you may need to add some checks which can make the model smarter to discover such an issue.

I will take future issues to the bulletin board in future.
Thank you all.
