### ISSUE TITLE
cice.build quirk when cross-compiling

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#306]
I came across a subtle limitation of the current build system. 

I'm working on a test system from Cray in preparation for our next HPC migration. The login nodes on this system have a broadwell architecture. That is where I'm compiling the code with `cice.build`. However, I want to run the code on some nodes with a different architecture (skylake). These are just available within a batch job (no interactive access). 

So in my env file I load the necessary modules for the Intel compiler and the skylake architecture. This by defaults adds the option '-xCORE-AVX512' to the compiler flags. The problem is with the program `makdep.c`. Since this program runs as part of the build process, it needs to be compiled with the right architecture for the **login** node. The AVX512 directives are not available on the login nodes and so the program `makdep` does not run correctly: it outputs 
```Please verify that both the operating system and the processor support Intel(R) MOVBE, F16C, FMA, BMI, LZCNT, AVX2, AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions```
 and the dependencies (*.d) are generated but **are all empty**.

If I add the flag '-xHost' in cice.build when compiling 'makdep.c' : 
```cc -xHost -o makdep ${ICE_CASEDIR}/makdep.c     || exit 2``` 
then it works (it uses the highest instruction set available for the platform where the compiler is running). This flag is however specific to the Intel compiler...

I see 3 issues here : 
1. The compilation should abort somehow if the dependencies are not correctly generated. (That might me hard to check...)
2. We could add a variable "ICE_MACHINE_MAKDEP_CFLAGS" to the env files and then compile makdep with 
```cc ${ICE_MACHINE_MAKDEP_CFLAGS} -o makdep ${ICE_CASEDIR}/makdep.c || exit 2``` 
3. As a side note, the makdep.c program is recompiled each time cice.build is run, this could be improved but it would mean modifying the Makefile. Also, since it is just one file I don't think it adds a lot of time to the build time.

I can submit a PR for (2.) if we go for that...

**Comment by apcraig** [comment]
We should definitely incorporate this feature into the build system.  It's likely to come up occasionally.  Thanks for finding, reporting, testing some workarounds, and proposing some solutions.

I think we should focus on a solution around (2) above.  We can separately look into 1 or 3, but I would defer those for now.  (2) should address the basic problem robustly and can be used as it comes up on other platforms.  I think this issue suggests we should move the makdep build into Makefile and out of cice.build.  In other words,

echo "building makdep"
cc -o makdep ${ICE_CASEDIR}/makdep.c || exit 2

in cice.build would be replaced by something like

echo "building makdep"
${ICE_MACHINE_MAKE}   -f ${ICE_CASEDIR}/Makefile MACFILE=${ICE_CASEDIR}/Macros.${ICE_MACHCOMP} makdep

then in the Makefile, we would a rule something like (note, i'm not sure this syntax is quite correct, but i think the idea is there)

makdep: $(ICE_CASEDIR)/makdep.c
    $(CC) -o $(EXEC) $(CFLAGS_HOST) <$

then each Macros file should have this set by default

CFLAGS_HOST := $(CFLAGS)

or maybe it should just be

CFLAGS_HOST := 

or maybe we should set this up even a little more clever which is that the Makefile would set the default and then only if CFLAGS_HOST is defined in the Macros file is it picked up.  That's probably better for backwards compatibility.  So the Makefile would be more like

ifdef $(CFLAGS_HOST)
CFLAGS_HOST_LOCAL := $(CFLAGS_HOST)
else
CFLAGS_HOST_LOCAL :=
endif
...
makdep: $(ICE_CASEDIR)/makdep.c
    $(CC) -o $(EXEC) $(CFLAGS_HOST_LOCAL) <$

and if you need to use this feature, just set CFLAGS_HOST in the Macros file.

I'm open about the best ways to implement this and would love to hear some better ideas.  @phil-blain if you want to prototype some of this and create a PR, please do.  I can also help.

**Comment by phil-blain** [comment]
Thanks for the feedback. I will start working on a PR.

**Comment by phil-blain** [comment]
The PR is here #307. It addresses (2) and since the compilation of `makdep` is done by the Makefile it also addresses (3) ! I will do a similar PR for icepack.

**Comment by phil-blain** [comment]
Icepack PR :  CICE-Consortium/Icepack#257

I might add a thing or two to these two PR but they work as-is for now.

**Comment by apcraig** [comment]
Both the Icepack and CICE PRs have been merged.  I will close this issue.  Sorry for the delay on the Icepack one, I thought I merged it days ago when I did CICE.   I guess I just approved it and never did the merge.  It's merged now.
