### ISSUE TITLE
CICE Consortium visibility on government.github.com/community

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#308]
I stumbled upon [this page ](https://government.github.com/community/#research) that lists government agencies doing work in the open on github. I thought it could be cool to feature the CICE Consortium on this page (I saw ACME is listed there, as well as a few other projects from the national labs). What do you guys think ?

**Comment by eclare108213** [comment]
That's interesting.  I think we should add our logo to the mix.  I'm not sure which category to put it in, though.  International?  US Federal doesn't seem inclusive enough.

**Comment by phil-blain** [comment]
I was thinking adding an "International" sub-section to the "Government-funded Research"  section. I can issue a PR for that on that page if you want.

**Comment by phil-blain** [comment]
The PR is here : https://github.com/github/government.github.com/pull/766

**Comment by apcraig** [comment]
I'm not entirely sure what's happening but the travis check is failing in the PR.  You can look at the travis log and see an error.  I don't know where it's coming from.  It looks like travis passing is a requirement but I have not looked at their git process carefully.

**Comment by phil-blain** [comment]
There was an error because since I added an International subsection under _Research_ and there already was one under _Governments_, Jekyll generated different HTML tags with the same id's. I just modified the Jekyll file to account for that.

**Comment by duvivier** [comment]
@phil-blain Do we need to do anything for this on our end? it looks like to be added to the governments page we'll need them to add it. Based on your PR there, it looks like you thought it was best to add a new subsection (International) rather than adding the CICE consortium under the US, Denmark, and Canada separately (if this would even be allowed).

**Comment by phil-blain** [comment]
Yes, when the pull request is accepted the page will be updated. I thought it best to add it only once.

**Comment by duvivier** [comment]
@phil-blain So the bottom line is we don't have to do anything on our end though. It's just once they accept the PR it'll be added to their page. Is this all correct?

**Comment by phil-blain** [comment]
Yes,correct. We don't have anything more to do.

**Comment by apcraig** [comment]
It looks like the PR sat too long and now is out of date with the base, github/government.github.com#766.  What a pain.  @phil-blain are you able to update?  Should we give up?

**Comment by phil-blain** [comment]
Yes I will update the PR with their latest master. As I wrote to Elizabeth this morning, I will do this after the sea-ice conference in Winnipeg in 2 weeks.

**Comment by phil-blain** [comment]
I just updated the PR

**Comment by apcraig** [comment]
Thanks @phil-blain!  I get we can see if it gets stale again.

**Comment by phil-blain** [comment]
They merged our PR ! https://government.github.com/community/#research

**Comment by eclare108213** [comment]
Terrific!  I just now looked at this, and we top the page!  Thanks again @phil-blain
