### ISSUE TITLE
Add max wallclock time to machine files

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#330]
I'm porting to one of our clusters which has a max wallclock time of 3 hours. 
The `base_suite` has a few tests wihch use the "medium" option, which sets ICE_RUNLENGTH to 4 (4 hours), so I have to manually change `configuration/scripts/options/set_env.medium` from 4 to 3 before creating a test or a suite, or else it fails to submit.
I propose adding a setting to the env files, such as ICE_MACHINE_MAX_WALLCLOCK or similar, and modifying `cice.batch` such that the "batchtime" variable is capped to the value of ICE_MACHINE_MAX_WALLCLOCK.

**Comment by eclare108213** [comment]
This seems like a good idea.  There are issues like this more generally, e.g. some machines don't have enough processors to run some of the base_suite tests, so those return fails (I think).  It would be nice to have a way of specifying ahead of time what the computing environment limitations are.

**Comment by apcraig** [comment]
I am implementing machine limits on both total number of pes (tasks * threads) and the batch wall limit.  Are there other constraints we want?

If some current machines have limits, let me know and I'll add them to the env machine files.  For now, I'll just test on one of the machine I have access to with fake limits but won't check those limits in.

**Comment by apcraig** [comment]
This is done with #349 and #356.  MAXPES, MAXRUNLENGTH, and MAXTHREADS are options.
