### ISSUE TITLE
Documentation RST syntax cleanup

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#335]
I noticed that there is a lot of wrong RST syntax for variable names in the documentation, for example in
https://cice-consortium-cice.readthedocs.io/en/latest/user_guide/ug_implementation.html#masks
the variable 'icetmask' appear as  `ice\_tmask`. A lot of other variables are similarly wrongly rendered. 

When searching 'icetmask' in the search bar, these references do not appear so it causes a usability problem.

This should be tagged 'Documentation'.

**Comment by duvivier** [comment]
@eclare108213 Are you wanting this complete before release? I am happy to do it, but I'm just swamped before leaving town this weekend and I don't want to hold up the release.

**Comment by eclare108213** [comment]
It's not critical for this release - let's fix it for the next one.  It's just formatting, not wrong information content.

**Comment by eclare108213** [comment]
@duvivier, just pinging this issue, which we'd postponed before the previous release.  We can continue to postpone, but it would be nice to fix.  Let me know if there's something you'd like me to do...

**Comment by duvivier** [comment]
@eclare108213 it's something I'm planning to address today actually. I'll let you know how it goes.

**Comment by phil-blain** [comment]
This can be closed.
