### ISSUE TITLE
setting diag_type = 'file' in namelist makes cice.run end with 'CICE run did not complete'

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#344]
Not a big issue, but still it would be nice if cice.run could grep the diag file specified in the namelist (diag_file) if diag_type is set to 'file' instead of the default value 'stdout'. Then real runtime errors would be spotted faster when diag_type = 'file' is used.

**Comment by apcraig** [comment]
I just had a look at this and don't think there's an easy or general fix.  We could possibly detect the diag_type='file' setting at runtime and then figure out the output filename, but there are a whole cascade of other issues like

  - does it get saved to the case logfile
  - does it get saved to the test suite baseline directory
  - do the baseline comparisons work properly.  can the scripts figure out all the filenames for any case ever run.

My recommendation is that we not try to fix this at this time.  What we could do, if others felt it was important, would be to detect the diag_type='file' setting and then just turn off the successfully completed check and add a note that users are on their own.  Is that something worth doing?

**Comment by phil-blain** [comment]
I think that's sound. Also, just having this issue open can serve as rudimentary documentation if anyone stumbles onto this and ends up here.

**Comment by phil-blain** [comment]
@apcraig we can close this issue as it was fixed in #396 right ?

**Comment by apcraig** [comment]
It was fixed in part in #396.  The successful completion is found, but the rest of the testing will not work.  I agree it should be closed.  We don't normally use diag_type=file.  I think we're OK for now.
