### ISSUE TITLE
Write git commit hash to cice.settings in cice.setup

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#353]
I think it could be valuable to write the output of `git describe --dirty` to the cice.settings file when cice.setup creates the case/test directory. This would be useful when we go back to an old case to know from which commit this case was originally created. Of course this would have to be taken with a grain of salt if using incremental builds since then the compiled executable could change after the case is created and first built. 

I guess a further thing we could do is embed the output of `git describe` into the executable (using a preprocessor macro for the value of a variable) and then we could run `cice --version` to get this information.

**Comment by apcraig** [comment]
Ultimately, a case points to a sandbox.  And that sandbox can tell you the git info.  As suggested, there are also many caveats to formally tracking the version in the case, custom mods, updates to the sandbox after the case is created, etc.  I'm not convinced this buys us much.

When a test suite is run, part of what is tracked is the origin, branch, hash, and other git info.  That too has some of the caveats above, but for all my automated testing, I always use a clean checkout of a sandbox and run the test suite to completion with any manual intervention.  In that case, the git info is meaningful and important.

I'm inclined to pass on implementing this feature at this time, but open to other feedback.

**Comment by eclare108213** [comment]
@phil-blain I will close this for now, but if you want to continue the discussion, we can reopen it.
