### ISSUE TITLE
Scripts: add support for parameter sweeps

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#360]
I think that parameter sweeps would be a very nice feature to have. Basically I mean automating the creation and submission of different cases where the only difference is the numerical value of some namelist parameter that varies between min and max with a certain step. 
I think we could leverage parts of the existing test suite script infrastructure to implement this. 
We would have to decide in what format should the parameter input space be given by the user. 
We could also use PBS job arrays (or the equivalent for other schedulers) as they are often used for that purpose, but then it is less portable (for example I think LoadLeveler does not have a similar feature). @apcraig what do you think ?

**Comment by apcraig** [comment]
I think this is an interesting idea.  Is this to support science or model testing?  I have some mixed feelings about whether we should implement a bunch of scripts to support it though.  These kinds of things tend to be pretty custom.  What I think we could do is add a section in the documentation that describes how to do these kinds of tests.  We might add some small changes to the scripts to make this easier.  But we need some ground rules first.  Is each different configuration a new case?  Or are we running a single case multiple times?  Is this science or testing?  We could certainly leverage the parse_namelist tool to modify namelists quickly and we should be able to create a template (or document) that loops over namelist settings, applies them to ice_in, and runs the case.  I don't think any of this is hard to do given our current scripts.  For me, I think it's mainly a question of whether it's worthwhile formally supporting this feature through some sort of automation in the current scripts (which could be tricky) vs just documenting a way (or a few ways) to achieve this capability via some simple scripts that a user might implement (and that we may partly provide as a starting point).  You could do this quite readily by having a high level script that loops over the cases by creating the case, updating the namelist with parse_namelist, building and submitting.  If you want to do this within a case, you would have something similar, a script that loops over the namelist changes, applies them, and submits the run.  You can imagine the requirements are to support multi-dimensional testing of multiple namelist changes.  Again, this is easy to do, but maybe not so easy to automate.

**Comment by apcraig** [comment]
We decided the Consortium does not need to play a role in this feature at this time.  We feel this is a model science tuning issue more than a testing issue and recommend that all model tuning be done in coupled configurations in the community.
