### ISSUE TITLE
Building CICE with NEMO 3.6

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#366]
I'm starting to work on coupling CICE6 with NEMO 3.6 for our ice-ocean forecasting systems at ECCC. 

First step is getting it to compile; how it was done for CICE4 and CICE5 is that the NEMO build system (a [deprecated version](https://metomi.github.io/fcm/doc/user_guide/build.html) of [FCM](https://metomi.github.io/fcm/doc/)) is in charge of compiling a single executable comprising both NEMO and CICE code.
I noted a first issue here https://github.com/CICE-Consortium/CICE/issues/363#issuecomment-533161469 which was solved with #365.
Another issue is I found out that the file **ice_dyn_evp_1d.F90** contains 3 Fortran modules (_dmi_omp_, _bench_v2_ and _ice_dyn_evp_1d_), and this is not handled by FCM (it expects 1 module per file) so the compilation aborts.

I think the easiest and cleanest way to solve this would be to split this file into 3 (one per module), and maybe renaming them for consistency with the rest of the CICE code base (ice_*). 
@apcraig @TillRasmussen what do you think ?

**Comment by apcraig** [comment]
I am testing CICE in RASM right now too.  I haven't updated the RASM CICE code for over 6 months.  I believe I am seeing the same issue.  I think splitting the files as proposed is a good idea. 

I would like to create a PR for CICE that addresses this issue and any other issues I find in the RASM integration testing.  I think this needs to be sorted out before the next CICE release.  This is top priority for me right now and I hope to have a PR in a few days.  @phil-blain, are you OK if I take this task on as high priority?

**Comment by TillRasmussen** [comment]
I don't have a problem splitting each module  into their own file.
-> @phil-blain Phil-blain May I ask why you work on Nemo 3.6 instead of 4?

**Comment by apcraig** [comment]
@TillRasmussen how about combining all 3 modules under the single ice_dyn_evp_1d module.  The only public interfaces in the file are in ice_dyn_evp_1d so the subroutines in dmi_omp and bench_v2 could just be private subroutines in ice_dyn_evp_1d.

**Comment by TillRasmussen** [comment]
That would probably work fine

**Comment by phil-blain** [comment]
@apcraig yes no problem, be my guest!
@TillRasmussen we just migrated our operational systems to NEMO 3.6 so we want to do things one step at a time... NEMO 4 is on the roadmap but further down the road.

**Comment by apcraig** [comment]
This should be addressed in #367 and am closing.
