### ISSUE TITLE
forcing data

### ISSUE THREAD

**Issue by Yukai12345** [CICE-Consortium/CICE#373]
I want to know what is the meaning of these data cldf、prec、swdn.

**Comment by eclare108213** [comment]
@Yukai12345, those forcing fields are described briefly in the code and also should be described in the [online documentation](https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#model-documentation).  If you are unable to find the information you are looking for, please submit a question to our [bulletin board](https://bb.cgd.ucar.edu/forums/cice-consortium-model-development), where we can discuss it.  It's possible that we need to update the documentation and your experience would be helpful for that.  Thank you for contacting us.

**Comment by Yukai12345** [comment]
Thank you very much！




------------------ 原始邮件 ------------------
发件人: "Elizabeth Hunke"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 晚上11:00
收件人: "CICE-Consortium/CICE"<CICE@noreply.github.com>;
抄送: "玖辛奈"<1838053191@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CICE-Consortium/CICE] forcing data (#373)




@Yukai12345, those forcing fields are described briefly in the code and also should be described in the online documentation.  If you are unable to find the information you are looking for, please submit a question to our bulletin board, where we can discuss it.  It's possible that we need to update the documentation and your experience would be helpful for that.  Thank you for contacting us.

**Comment by Yukai12345** [comment]
Thank you very much!

**Comment by Yukai12345** [comment]
May I ask what cldf (the monthly cloud forcing) is in the gx1 data? Is it the monthly total cloud?Does prec (precipitation) refer to the average monthly precipitation?What does swdn mean?I haven't seen any explanation for the data in documentation.I would like to download these from ECMWF now and hope you can explain what they mean.Thank you!




------------------ 原始邮件 ------------------
发件人: "Elizabeth Hunke"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 晚上11:00
收件人: "CICE-Consortium/CICE"<CICE@noreply.github.com>;
抄送: "玖辛奈"<1838053191@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CICE-Consortium/CICE] forcing data (#373)




@Yukai12345, those forcing fields are described briefly in the code and also should be described in the online documentation.  If you are unable to find the information you are looking for, please submit a question to our bulletin board, where we can discuss it.  It's possible that we need to update the documentation and your experience would be helpful for that.  Thank you for contacting us.
