### ISSUE TITLE
forcing data

### ISSUE THREAD

**Issue by Yukai12345** [CICE-Consortium/CICE#374]
May I ask what cldf (the monthly cloud forcing) is in the gx1 data? Is it the monthly total cloud?Does prec (precipitation) refer to the average monthly precipitation?What does swdn mean?I haven't seen any explanation for the data in documentation.I would like to download these from ECMWF now and hope you can explain what they mean.Thank you!

**Comment by eclare108213** [comment]
Please move your question to our bulletin board, which is here:
https://bb.cgd.ucar.edu/forums/cice-consortium-model-development

**Comment by Yukai12345** [comment]
Sorry I can't open this link

**Comment by eclare108213** [comment]
I see the bulletin board is having some sort of issue -- I'm not able to reach the site.  So for now:

I had a look at the docs and the code, and I agree with you that these fields are not sufficiently documented.  I am reopening this issue, as a reminder for us to improve this aspect of the docs.

Here's what I remember (NB some things might be wrong and if so, other people can correct me):

- cldf is total cloud coverage, as a fraction between 0 and 1.  In our test data, it is monthly but it can be provided and used at other frequencies.  This variable is not used directly in the sea ice physics, but rather to generate other forcing fields such as downwelling longwave radiation, and to modify the amount of shortwave that reaches the surface.  In coupled runs, I believe this is all done prior to the forcing reaching the sea ice model, and so cldf does not need to be sent by a flux coupler.
- prec is precipitation, in units that can be set in the namelist file (ice_in).  This is often just liquid precipitation, a portion of which might be converted to snow if the temperature is cold enough.  Again, in coupled runs the coupler or atmosphere component determine exactly what this is.  You'll need to check the sea ice model code to be sure that what you are sending it is being used the way you expect.  The ice model can handle both liquid and solid precipitation. (And this does need to be better documented.)
- swdn is the downwelling shortwave radiation, in W/m2.  In our test configurations, it is provided as a single value and then divided up into 4 wavelength bands.  In coupled runs, the bands are sent directly.  The model has a couple of different options for calculating the radiation balance, and this part of the code is well documented.

**Comment by Yukai12345** [comment]
Sorry I can't open this link.




------------------ 原始邮件 ------------------
发件人: "Elizabeth Hunke"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 晚上11:46
收件人: "CICE-Consortium/CICE"<CICE@noreply.github.com>;
抄送: "玖辛奈"<1838053191@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CICE-Consortium/CICE] forcing data (#374)




Please move your question to our bulletin board, which is here:
 https://bb.cgd.ucar.edu/forums/cice-consortium-model-development

**Comment by Yukai12345** [comment]
Thank you very much！

发自我的iPad

------------------ Original ------------------

**Comment by dabail10** [comment]
The new link is here: https://xenforo.cgd.ucar.edu/cesm/index.php#sea-ice.125. They changed the software without giving us more warning. We are in the process of trying to reorganize the forums again.

**Comment by Yukai12345** [comment]
OK,thanks.





------------------ Original ------------------

**Comment by duvivier** [comment]
@eclare108213 To clarify what needs to be done still:
1. Better document names of the forcing files
2. Document the cldf and precip details
3. Change the links to the bulletin board everywhere - and yes, this is a pain. >:-(

**Comment by duvivier** [comment]
You are correct @eclare108213, in the coupled model we don't need cloud fraction. Just the direct radiative forcing (SW down - in the 4 components, LW down). We calculate the SW up and LW up and pass those back.

> * cldf is total cloud coverage, as a fraction between 0 and 1.  In our test data, it is monthly but it can be provided and used at other frequencies.  This variable is not used directly in the sea ice physics, but rather to generate other forcing fields such as downwelling longwave radiation, and to modify the amount of shortwave that reaches the surface.  In coupled runs, I believe this is all done prior to the forcing reaching the sea ice model, and so cldf does not need to be sent by a flux coupler.

**Comment by Yukai12345** [comment]
Hello, I found this problem when installing CICE mode. What is the reason?
Looking forward to your reply。
Please check the attachment.

**Comment by phil-blain** [comment]
@Yukai12345 please ask for help in the CICE Consortium's forum here : https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/

You will likely get more help there. (and there is no attachment in you previous message as it's not a real email, it's a GitHub issue (https://github.com/CICE-Consortium/CICE/issues/374#issuecomment-601651455)

**Comment by Yukai12345** [comment]
Hello, I found this problem when installing CICE mode. What is the reason?

cli_25]: write_line error; fd=16 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_25]: Unable to write to PMI_fd
[cli_25]: write_line error; fd=16 buf=:cmd=get_appnum
:
system msg for write_line failure : Bad file descriptor
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474):
MPID_Init(152).......: channel initialization failed
MPID_Init(426).......: PMI_Get_appnum returned -1
[cli_26]: write_line error; fd=18 buf=:cmd=abort exitcode=1094415
:
system msg for write_line failure : Bad file descriptor

**Comment by Yukai12345** [comment]
Hello, I found this problem when installing CICE mode. What is the reason?

cli_25]: write_line error; fd=16 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_25]: Unable to write to PMI_fd
[cli_25]: write_line error; fd=16 buf=:cmd=get_appnum
:
system msg for write_line failure : Bad file descriptor
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474):
MPID_Init(152).......: channel initialization failed
MPID_Init(426).......: PMI_Get_appnum returned -1
[cli_26]: write_line error; fd=18 buf=:cmd=abort exitcode=1094415
:
system msg for write_line failure : Bad file descriptor




I would like to ask a question on&nbsp;https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/, but I don't know why the registration failed








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"David A. Bailey"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月26日(星期六) 凌晨0:22
收件人:&nbsp;"CICE-Consortium/CICE"<CICE@noreply.github.com&gt;;
抄送:&nbsp;"玖辛奈"<1838053191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CICE-Consortium/CICE] forcing data (#374)




The new link is here: https://xenforo.cgd.ucar.edu/cesm/index.php#sea-ice.125. They changed the software without giving us more warning. We are in the process of trying to reorganize the forums again.

**Comment by Yukai12345** [comment]
Hello, I can't register on this website(https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/).
May I ask how to solve the problem in the attachment.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Philippe Blain"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上10:37
收件人:&nbsp;"CICE-Consortium/CICE"<CICE@noreply.github.com&gt;;
抄送:&nbsp;"玖辛奈"<1838053191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [CICE-Consortium/CICE] forcing data (#374)





 
@Yukai12345 please ask for help in the CICE Consortium's forum here :&nbsp;https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/
 
You will likely get more help there. (and there is no attachment in you previous message as it's not a real email, it's a GitHub issue (#374 (comment))

**Comment by eclare108213** [comment]
@Yukai12345 
Let me ask for your patience.  Here in the US we are going through a transition to work at home, due to the pandemic.  Once we get ourselves settled in the new working environment, our NCAR people should be able to look at the registration issue for the forum.  In the meantime, your problem appears to be associated with the configuration of your computer, since those errors are coming from the underlying software rather than from the sea ice model itself.  You will likely solve the problem more quickly by contacting your IT services for help.

**Comment by duvivier** [comment]
@Yukai12345  You have not provided us any information about what error you received when attempting to register, so we can't provide guidance. In the meantime, here are the steps to register:

1) go to: https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/
2) In the upper right hand part of the screen there are tabs that say "Log in", "Register", and "Search". Click the Register one.
3) You will be prompted to enter a User Name (your choice), an email address (any valid email), and a password (your choice). You will also need to click the boxes indicating that "I'm not a robot" and "I agree to the terms and privacy policy". 

Once you have done these steps you should have an account. Anyone can register, so there should not be a problem with your email address, as long as it's valid, though you may need to choose a different user name if the one you are selecting is already taken. If you are still unable to register we will need to contact our IT folks because that's a problem with the system. However, without your feedback about what error you are getting we can't provide any useful information to them about what might be going wrong for you. Hundreds of people have registered successfully, so hopefully if you follow the steps above you can successfully register too.

**Comment by duvivier** [comment]
@Yukai12345 I have spoken with our forum admins and they said that they changed the verification method. Please try registering again to ask any further user-specific questions.

**Comment by apcraig** [comment]
Can we close this issue?  Is there anything here that we should carry into another issue or do we need to keep this open for any reason?
