### ISSUE TITLE
CICE and Icepack Namelist Documentation

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#375]
I would like to propose we reorder the namelist documentation in the tables to be alphabetical in each namelist group.  I recognize setup_nml is split into subsections (time/diagnostics, initialization/restarting, and model output).  Maybe those could persist and we could organize them by alphabetical in their subgroups.  I also wonder if we can improve on the formatting, maybe make the namelist groups bold and bigger, maybe reduce the font of the description, maybe make the tables a little clean although not sure how?  I also think it's a little dangerous to have the "also in icepack" column as that is difficult to keep up to date on the cice side and the codes are slowly diverging.  The icepack driver is undergoing little to no updates while CICE is.  The current cice namelist table is here,

https://cice-consortium-cice.readthedocs.io/en/master/user_guide/ug_case_settings.html#table-of-namelist-options

**Comment by eclare108213** [comment]
All good ideas.  Are you proposing the reordering only in the documentation?  It seems like it should match the ordering in the namelist file -- would we want to change that too?  That could be a bit disruptive.

**Comment by apcraig** [comment]
It's a good question.  In CICE standalone, the order is determined by the order in our ice_in default file.  In other applications, it is likely to be different.  In CESM, the order is alphabetical just because that's how the namelist generation script works.  By making the documentation alphabetical, it makes it easier to find information for a given namelist variable name regardless of the order of your ice_in file.  

Separately, I think we could definitely decide to reorder our ice_in namelist to also be alphabetical, but I don't think these two have to go hand-in-hand.  I think the bigger question is whether an order other than alphabetical in the documentation is advantageous for other reasons (like if it groups the tr_ and restart_ variables side-by-side as now).

**Comment by apcraig** [comment]
I am reordering and updating the namelist tables.  I'd also like to propose we remove the column, "also in Icepack" from the CICE namelist table.  I'm not sure it's useful since we have a separate document for the Icepack model these days.  I also think it creates an issue with maintenance between icepack and CICE.  Unless anyone disagrees, I'll proceed.

**Comment by eclare108213** [comment]
Removing that column is fine with me.  I think we say somewhere in the doc, generally, that many of the namelist variables are also in Icepack.

**Comment by apcraig** [comment]
This has been updated in #459 and can be closed.
