### ISSUE TITLE
Change UCAR forum links

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#381]
I'm creating this issue to bring together the discussion around changing our links to the new ucar forum URL : 

https://xenforo.cgd.ucar.edu/

This needs to be done : 
- [ ] For CICE https://github.com/CICE-Consortium/CICE/
- [x] For the CICE wiki https://github.com/CICE-Consortium/CICE/wiki
- [ ] For Icepack https://github.com/CICE-Consortium/Icepack/
- [x] For the Icepack wiki https://github.com/CICE-Consortium/Icepack/wiki
- [ ] For About-Us https://github.com/CICE-Consortium/About-Us/
- [x] For the About-Us wiki https://github.com/CICE-Consortium/About-Us/wiki

I think this is everything...

The easiest way to not forget any link would be to clone each repo and wiki and do : 
~~~
git grep bb.cgd.ucar
~~~

**Comment by phil-blain** [comment]
@dabail10 @duvivier @apcraig @eclare108213

**Comment by phil-blain** [comment]
Also, it would be ideal if old forum posts linked in GitHub issues would be corrected so that the content can be found more easily. I've done this for my own posts (#285 and #275).

**Comment by dabail10** [comment]
I agree, but things are still changing here. I was trying to minimize the amount of work we will have to do.

Dave

**Comment by apcraig** [comment]
I think this points out the benefit to having a single resource list.  As much as possible, we should be pointing users to the resource page and then we just have to make sure links are correct there.  So in all users guides even in the repo home README.md page, we can use "see the resource page" and create a link just to that.  That can be for the bulletin board, release info, documentation, etc.  I think that's partly the reason for the resource page.  I understand there may be some reasons to have the bulletin board linked directly on each pages README.md, but if we don't feel it's critical, pushing all references to other documentation to the resource page is of some benefit.  

If we need to make the resource page more usable, we could consider spending some efforts there.  I prefer to do that than to have to update links in mulitiple places over time.

Just my opinion :)

**Comment by apcraig** [comment]
One other comment.  I would prefer if the CICE-Consortium stuff were not under "CESM" in the bulletin board.  I understand that one bulletin board for CICE is ideal, but the hierarchy of the bulletin board should be different.   I'm not sure it's reasonable to treat everything as falling under "CESM"/DiscussCESM by default.   Shouldn't there be forums for components models and then separately the CESM system?  This applies not just to the consortium, but how about to other linked projects like all the stuff happening in NOAA?

**Comment by proteanplanet** [comment]
I agree with Tony's point here, and it especially resonates from a DOE perspective, although I appreciate it may not be possible to accommodate it within the CESM setup.

**Comment by eclare108213** [comment]
So, it looks like CICE Consortium related items are all dumped into the "sea ice" header, together with CESM specific stuff.  Is that true?  Can we get our own forum?
Also, do we have an ETA for getting this fixed?  All the bb.cgd.ucar links on our wikis are broken.

**Comment by dabail10** [comment]
We just had a presentation on this from the CGD Systems people. They decided to get rid of the subforums and they want to use "tags" now. So, somehow we would group together all of the CICE-Consortium posts with a tag. Then we could use a web link like:

https://xenforo.cgd.ucar.edu/cesm/tags/cice-consortium/

This is definitely not optimal. I am going to ask about a subforum again and see. So, here are the options:

1. Stay with the NCAR xenforo forums and create tags for all of the CICE-Consortium posts. This is not ideal, because a user would have to know to tag their post, or one of us has to do this.

2. Stay with the NCAR xenforo forums and create subforums again. Not sure if this is possible.

3. Move to a separate forum server. There are several out there. The problem is the cost. Most of them are $4 a month. Who would pay for this? 

4. Move to github issues. As we've talked about, this is not ideal for the forum style posts and we would have troubles with non-developers.

I'm happy to have a discussion about this on Thursday. Deciding on which way to go forward will help us determine how long to get things fixed.

Dave

**Comment by dabail10** [comment]
Just an update I can get subforums again. There will be just the two:

CESM CICE
CICE Consortium

Further categorizing under these forums would have to be done with tags.

Dave

**Comment by proteanplanet** [comment]
Thanks Dave.


- Andrew

---
Andrew Roberts
T-3 Fluid Dynamics and Solid Mechanics
Los Alamos National Laboratory
Office: 505-667-7744, Cell: 505-695-4564
afroberts@lanl.gov

**Comment by phil-blain** [comment]
I think having CICE Consortium as a subforum would be the ideal solution, thanks Dave for pushing this.

**Comment by dabail10** [comment]
This has finally been moved and the updated Consortium link is here:

https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/

I'll take a look around for the links and try to update them.

Dave

**Comment by dabail10** [comment]
I updated the links in the Wiki area, but the links in the README.md files need to be updated too. I am back in the office on Thursday.

Dave

**Comment by duvivier** [comment]
Fixed README.md for CICE with PR #391. Working on the other repos now.

**Comment by phil-blain** [comment]
The Icepack README was fixed in CICE-Consortium/Icepack#291

I just checked all 6 repos using the `git grep` command above, and there was one last link that needed to be changed in the About-Us wiki. I changed it :
https://github.com/CICE-Consortium/About-Us/wiki/Contacting-the-Consortium/_compare/ed79ffd77f2d88c71565edc8a946284b5eff197d...404b364601e748d16647c928a2b4a3e707cefed9
