### ISSUE TITLE
MPAS-SI integration as a second dynamical core

### ISSUE THREAD

**Issue by proteanplanet** [CICE-Consortium/CICE#407]
Following the CICE and PCWG workshops two weeks ago, it was clear to me that there is duplication planned across Consortium members and users for C-grid conversions and changes to the EVP rheology to include a Mohr-Coulomb yield curve.  These adaptions are occurring within the existing CICE dycore as well as within MPAS-seaice (MPAS-SI; see https://mpas-dev.github.io).   As a consequence, I would like to open the idea to the consortium of introducing MPAS-SI as a second dynamical core.  The advantage of MPAS-SI over the existing dynamical core for the isotropic rheology is that it is universally applicable to both structured and unstructured grids, so, for example, could be coupled with GFDL's ocean model but also work in three separate finite-volume codes already using CICE column physics.   Anisotropy is currently not available in MPAS-SI.  This is an initial inquiry to find out if Consortium members would like to learn more about this potential option, and its applicability to their particular model configurations.

**Comment by phil-blain** [comment]
@JFLemieux73

**Comment by daveh150** [comment]
I am interested to learn more about MPAS-SI as another dynamical core, and if it would benefit our current setup or future high resolution, regional domains. Also, could it apply to an adaptive grid that changes in time?

 

Thank you,

David

 

David A. Hebert

Ocean Sciences Division, Code 7322 
Naval Research Laboratory 
Stennis Space Center, MS 39529
(228)688-5846; DSN 828-5846 
http://www.nrl.navy.mil <http://www.nrl.navy.mil/>

**Comment by proteanplanet** [comment]
At present, MPAS-SI caters to unstructured and therefore also structured meshes, but its mesh is not adaptive.  Perhaps I present on the capabilities of MPAS-SI and its regional meshing capabilities at an upcoming Consortium leadership meeting.

**Comment by apcraig** [comment]
I'm open to this.  Would this be a new dynamical core in CICE or would it be a new repository in the Consortium organization?  I think we'd need to have further discussion about the details before a decision could be made.

**Comment by JFLemieux73** [comment]
I agree that it would be good to discuss about this. Maybe at the next conf call?

**Comment by proteanplanet** [comment]
This item is being closed as intractable at the current time owing to the FTE required to make it work within the CICE Consortium framework.
