### ISSUE TITLE
scripts: copy cice.settings to ICE_RUNDIR

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#411]
It could be useful if the scripts would copy `cice.settings` to the run directory. 

One of the reason would be so that there exist a back reference to the test case directory (`ICE_CASEDIR`) in the run directory, so that we can easily jump back and forth between a test case (possibly in a test suite) and its run directory. (If we just go back and forth we can use `cd - ` to do that, but if we `cd` someplace else then we can't use this trick anymore). 

Having `cice.settings` in the run directory, one could easily create an shell alias that greps `cice.settings` looking for `ICE_CASEDIR` and `cd`'s there.
Right now I have these:
~~~
$ alias cdrun
alias cdrun='cd ~/local/CICEDIRS/CICE_RUNS/${PWD##*/}'
$ alias cdcase
alias cdcase='cd ~/local/CICEDIRS/cases/${PWD##*/}'
~~~

These work fine for cases and `cdrun` works for standalone tests and tests in a test suite, but once I'm in `ICE_RUNDIR` there's no easy way to go back to `ICE_CASEDIR` if `cd -` does not work because I `cd`'ed somehwere else (eg.  `ICE_RUNDIR/{restarts,compoile,history}`) and then came back to  `ICE_RUNDIR`.

@apcraig

**Comment by apcraig** [comment]
This seems to be related to something mentioned in #412

**Comment by apcraig** [comment]
This can be closed, both the model .settings file and the env machine file are copied to the run directory in Icepack and CICE now.
