### ISSUE TITLE
scripts: add support for launching CICE in a debugger

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#412]
When I want to launch CICE in a debugger (like Totalview), what I do in my case directory is to copy `cice.run` as `cice.debug` and prefix the command for launching cice with the debugger command, i.e.
~~~diff
diff --git 1/picard-1x1-fev2020/cice.run 2/picard-1x1-fev2020/cice.debug
index 8b3fd44..bd7f5a0 100755
--- 1/picard-1x1-fev2020/cice.run
+++ 2/picard-1x1-fev2020/cice.debug
@@ -36,7 +36,7 @@ echo "CICE rundir is ${ICE_RUNDIR}"
 echo "CICE log file is ${ICE_RUNLOG_FILE}"
 echo "CICE run started : `date`"
 
-./cice >&! $ICE_RUNLOG_FILE
+totalview -newui ./cice >&! $ICE_RUNLOG_FILE
 echo "CICE run finished: `date`"
 echo " "
~~~

It would be great if the scripts would support this use case, either through a separate script `cice.debug` or a flag to `cice.run`, i.e. `./cice.run --debug`.

The command to launch the debugger could be added as an `ICE_MACHINE_DEBUGGER` variable in the env file, as well as any `module load` command (or similar) necessary to access it (and we could leverage `ICE_BLDDEBUG` to only execute these commands when compiling/running in debug mode).

This would make it easy to debug CICE, at least in an interactive session, either in serial mode or with a small number of MPI processes. Making it also work for jobs submitted to a cluster would probably be a lot more work if we want it to be generic enough for multiple job schedulers / debuggers.

**Comment by eclare108213** [comment]
I use totalview too.  My workflow is to request an interactive session from the scheduler/queuing system, then cd to the run directory and type 

> totalview mpirun -a -np [numprocs] cice

(or leave out the mpirun part for serial tests)

Seems a lot more straightforward, and then we don't have to worry about users wanting other debuggers.  I often cd to the run directory for other reasons anyhow -- we can't do everything from the case directory.  My wish would be to make that cd easier, rather than trying to increase capabilities in the case directory.  But I'm open to others' opinions about this.

**Comment by phil-blain** [comment]
@eclare108213 when #450 is merged, `cice.settings` will be copied to the run directory, so these aliases would work to go easily from `ICE_CASEDIR` to `ICE_RUNDIR` and back :

**For Bash / compatible**
```shell
alias  cdrun='cd $(\grep "setenv ICE_RUNDIR"  cice.settings | awk "{print "\$"NF}")'
alias cdcase='cd $(\grep "setenv ICE_CASEDIR" cice.settings | awk "{print "\$"NF}")'
```

**For csh / compatible**
```shell
alias  cdrun 'cd `\grep "setenv ICE_RUNDIR"  cice.settings | awk "{print "\$"NF}"`'
alias cdcase 'cd `\grep "setenv ICE_CASEDIR" cice.settings | awk "{print "\$"NF}"`'
```

**Comment by phil-blain** [comment]
we could even document these in the user manual, it was not easy to quote that `$NF` correctly...

**Comment by apcraig** [comment]
I've added this "hint" in the documentation in PR #450

**Comment by apcraig** [comment]
Documentation was added to the user guide in #459.  We decided at the SE telecon on May 26, 2020 that this would be adequate for now.
