### ISSUE TITLE
NOAA JEDI data assimilation

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#419]
I will ask J. Kim to move his request to this issue thread so several of us can take a look at his code.  He writes:

> In NOAA-NCEP, I have been trying to put cice6 into JEDI-based data assimilation framework. Although there are some issues I have to work on, but it seems that stand-alone cice6 data assimilation capability is nicely demonstrated with JEDI-based system. For one thing on cice6 code management side, I noticed that some minor changes to cice git master branch will greatly facilitate to continuously keep update of the JEDI-based cice6 data assimilation to the latest cice6 code release. Pretty much like making some global variables public and nullification of pointers, etc.
> 
> So, could you take a look at the attached a change log file to see if these changes can be merged into master branch? If some of these can be accepted, I will clean up our branch and issue PR.
> Thanks
> 
> -- 
> Jong Kim
> IMSG at NOAA/NWS/NCEP/EMC
> 5830 University Research Ct., Rm 2768
> College Park, MD 20740
> Jong.Kim@noaa.gov

The ChangeLog file is attached (plain text), but it would
 be easier to compare the branches through github. 

[ChangeLog.txt](https://github.com/CICE-Consortium/CICE/files/4376099/ChangeLog.txt)

**Comment by apcraig** [comment]
These all seem pretty reasonable to me.  Nothing there scares me.  If others agree, I'm happy to create a PR with these changes.

**Comment by TillRasmussen** [comment]
This looks ok. Not sure if the "nullify" statement clears a pointer that is used later. It is probably not the case

**Comment by jkbk2004** [comment]
PR for the ChangeLog will be great for future version updates on our side.
Based on cice6.1.0 and icepack1.2.0 (versions realsed on Dec 2019), we are working on feature/ecbuild branches of the following repositories.
https://github.com/JCSDA/Icepack.git
https://github.com/JCSDA/CICE.git

Its based on cmake compile system. We have some minor issue with call ice_shr_reprosumx86_fix_start, But we can handle this issue on our side.

**Comment by eclare108213** [comment]
Is it easy to create a PR from scratch, @apcraig ?  I was thinking that @jkbk2004 could point us to a comparison of the changes on Github, of his branch(es) with our master(s), and maybe make a PR from that, but that might be more complicated.  You two work it out, please...

**Comment by jkbk2004** [comment]
@apcraig I can update my branch to the latest and issue PR from there. But it will take time to go thru JEDI-SOCACICE side. So, if it's not a big issue to work on your side to merge the ChnageLog stuff, it will be great and I can test next time when I update version.

**Comment by apcraig** [comment]
@jkbk2004, I think that's a reasonable proposal.  I will create a PR soon.  If we miss things or need other modifications due to recent changes, we'll just continue to iterate.

**Comment by apcraig** [comment]
The Jedi DA modifications have been merged into CICE with #427.  At some point, someone should confirm they work with Jedi DA.  If we have to create another ticket for another set of modifications, no problem.  For now, I'm going to close this.  If we think it should stay open until we have everything tested and working, feel free to reopen.
