### ISSUE TITLE
Problem with mode installation

### ISSUE THREAD

**Issue by Yukai12345** [CICE-Consortium/CICE#420]
Hello, I found this problem when installing CICE mode. What is the reason?

cli_25]: write_line error; fd=16 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_25]: Unable to write to PMI_fd
[cli_25]: write_line error; fd=16 buf=:cmd=get_appnum
:
system msg for write_line failure : Bad file descriptor
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474):
MPID_Init(152).......: channel initialization failed
MPID_Init(426).......: PMI_Get_appnum returned -1
[cli_26]: write_line error; fd=18 buf=:cmd=abort exitcode=1094415
:
system msg for write_line failure : Bad file descriptor

How to solve this problem？

**Comment by duvivier** [comment]
@Yukai12345 You need to start asking these questions in the CICE community forum. The issues page is not the right place to ask for help for these individual questions. 
 https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/

I provided information for you about how to register in issue #374. If you are having problems with that registration you need to provide more information for us so we can help you register there so you can use that forum. I will close any future issues that you open with these sorts of questions.

**Comment by Yukai12345** [comment]
"Verification" did not show up, so I was unable to register.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alice DuVivier"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上6:32
收件人:&nbsp;"CICE-Consortium/CICE"<CICE@noreply.github.com&gt;;
抄送:&nbsp;"玖辛奈"<1838053191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [CICE-Consortium/CICE] Problem with mode installation (#420)





 
@Yukai12345 You need to start asking these questions in the CICE community forum. The issues page is not the right place to ask for help for these individual questions.
 https://xenforo.cgd.ucar.edu/cesm/forums/cice-consortium.146/
 
I provided information for you about how to register in issue #374. If you are having problems with that registration you need to provide more information for us so we can help you register there so you can use that forum. I will close any future issues that you open with these sorts of questions.

**Comment by duvivier** [comment]
@Yukai12345 Are you saying you don't see the box that has the red circle around it for verification (see picture below)? If you click it you will see an image pop up and it asks you to identify a feature in that image. I have tried this in multiple browsers and am able to see the "Verification" button.

![Picture1](https://user-images.githubusercontent.com/23384844/77638676-27c24800-6f1d-11ea-9127-d52207406de2.png)

**Comment by Yukai12345** [comment]
I really can't see it. Maybe there is something wrong with my network. Could you help me register?

E-mail: 1838053191 @qq.com

User name: yukai

Password is your choice.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alice DuVivier"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上6:51
收件人:&nbsp;"CICE-Consortium/CICE"<CICE@noreply.github.com&gt;;
抄送:&nbsp;"玖辛奈"<1838053191@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [CICE-Consortium/CICE] Problem with mode installation (#420)





 
@Yukai12345 Are you saying you don't see the box that has the red circle around it for verification (see picture below)? If you click it you will see an image pop up and it asks you to identify a feature in that image. I have tried this in multiple browsers and am able to see the "Verification" button.

**Comment by eclare108213** [comment]
@Yukai12345 
We will not register for you -- sharing passwords is a really bad idea.  We will ask the people who run the forum whether they have any ideas or suggestions.

So far, no one watching the CICE Consortium issues has a solution for your setup problem.  As I said in issue #374, this is most likely a problem with the configuration of your computer, not with the CICE code, and we can not help you with your computer configuration.  Please find someone in your local department or institution to help you with that.  Continuing to post your question on our github issues list is not going to help you.  

I'm sorry, this is the best we can do right now.  We will follow up on the forum issue, but the ultimate answer may be the same:  find someone local to help you with your computer configuration.

**Comment by phil-blain** [comment]
Maybe Google - which provides the reCAPTCHA service is blocked in @Yukai12345's origin country ?

**Comment by phil-blain** [comment]
I think that's the case, a quick web search reveals reCAPTCHA is blocked in China if special measures are not used in the code - in this case, Xenforo's code, the forum software that is used. The documentation for recPATCHA https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally reveals it is possible to use an alternate URL so that the reCAPTCHA are not blocked, however this is something that would need to be done in Xenforo's code, and Xenforo is not open-source...

@dabail10 maybe the forum administrators are aware of this and could get in touch with Xenforo's support team to see if how this could be alleviated ? It's kind of unfortunate for all users in China not to be able to register...

**Comment by duvivier** [comment]
@phil-blain Yes, the forum admins have recognized this problem fixed it so that people from China can make accounts. Yukai was able to make an account and post on the forum a while back.
