### ISSUE TITLE
Add ksno namelist in icepack and cice

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#421]
Proposed at CICE Workshop.

**Comment by dabail10** [comment]
So, I am working on this now. I just looked at the example of Cf. The implementation seems to be that there is a hard-coded value of Cf in icepack_parameters, but this can be overridden from the namelist? Is this correct? I'm concerned that this might be a bit confusing.

**Comment by apcraig** [comment]
Generally, that is correct.  We should just set ksno in icepack_parameters to the current hardwired default and then also set the default in the namelist to the same value.  We want to add ksno to both the icepack and cice namelist files.  If ksno is ever not defined in the namelist, it is set to the default value as now.  When could this be confusing?

**Comment by dabail10** [comment]
This is confusing to me because Cf is also set to 17 in ice_init.F90 in CICE. So, we use icepack_query_parameters in some cases, but not others. I was also confused, because it initially wasn't clear to me that Cf was overriding the hard-coded value. This is probably o.k.

**Comment by apcraig** [comment]
OK, so the problem is in the upper layer and how to manage the values and memory.  That's a general issue with the setup.  When we separated icepack, decided many things would be set and stored inside icepack and other things would be passed, and decided everything had to be passed thru interface arguments (no "use"), that can of worms was opened.  There is a default in icepack and that can be changed via an interface.  The namelist has to be read in the driver and there may be a separate default there as well as a place to store the value in the driver.  The top layer needs to decide how to coordinate the value and usage.  I agree it can be confusing.

**Comment by eclare108213** [comment]
I thought that the idea was that icepack would always 'own' its parameters, and the driver would always have to query for them, so no storage in the driver.  I'm sure we aren't consistent about it, but isn't that the goal we are working toward?

**Comment by apcraig** [comment]
Yes, that's the goal we're shooting for, so we should be coding to that standard as we move forward.    @dabail10, if you look in CICE, that is exactly what's happening with Cf.  Because the namelist is read into ice_init, we set a default before we read it, then we pass that value into icepack after reading the namelist.  And Cf is not stored in CICE as far as I can tell.  On the CICE side, I guess we could query the value of Cf from icepack before reading namelist if we wanted.  That would work too.  But in practice, Icepack doesn't really have to dictate that.  The driver default can be implemented however the driver wants and whether Cf comes in thru namelist or not doesn't matter.  The main point is that it should be set in Icepack from the driver.  And if it isn't, icepack does have a default value.

**Comment by apcraig** [comment]
My initial guess would be that you are setting ksno = 0.3 while the default in the columnphysics is 0.30_dbl_kind.   Try setting 

```
  ksno = 0.3d0
```
in icepack_in and see if that fixes the problem.  If not, let me know and I'll look further.  You should be able to take one of the failed tests, modify icepack_in manually, then just submit that test as a quick initial check.  

A separate question is whether this d0 notation is standard and whether we should be using it or not.  Lets first decide whether that's where the problems comes from then discuss further how to move forward.

**Comment by dabail10** [comment]
Good point. I wondered that as all of the namelist values are single precision.

Dave

**Comment by dabail10** [comment]
Same four tests failed with ksno = 0.3d0. Good thinking though.

**Comment by apcraig** [comment]
OK, I'll try to have another look.

**Comment by dabail10** [comment]
No rush. I will try it on a different machine (izumi).

**Comment by apcraig** [comment]
I think the problem could be that your baseline is old.  It looks like you ran the baseline with a codebase last updated Feb 18.  I suspect if you pull the latest code and retest, you'll be OK.  I am running some tests now to confirm.

**Comment by dabail10** [comment]
Sorry, you are right. I forgot to update my master sandbox. I am testing on izumi currently with the right baselines.

**Comment by apcraig** [comment]
@dabail10 are you also working on the same change in CICE?  We'll want to do that as well.  Let me know if you're taking that on or if you want me to do so.  Thanks!

**Comment by dabail10** [comment]
I have it ready to go for CICE. I was waiting for the isotopes to go in first.

**Comment by apcraig** [comment]
@dabail10, sounds great, thanks!

**Comment by dabail10** [comment]
Testing now.

**Comment by apcraig** [comment]
Also addressed in https://github.com/CICE-Consortium/Icepack/pull/311, will close issue.
