### ISSUE TITLE
CU Boulder database

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#429]
Does someone want to take this on?  It looks like NCAR might have made the initial entry, but it might also have been me, many years ago.  We should probably update it for CICE and also add Icepack.

> Dear Elizabeth  -
>  
> As the CSDMS model repository has grown (currently over 300 models and tools!) community members have increasingly requested methods of navigating through the model/tools to find what they need for a specific task.  To that end, the CSDMS IF is making upgrades to the model metadata pages and creating a search mechanism for the software.
>  
> Would you please join your community members in assisting with this effort by providing the activity status of your model/tool and letting us know if there are any required revisions to the model metadata page by completing this (very) brief form: https://forms.gle/b3qVC1CvWX8ezNbb6
>  
> Please submit one form per model/tool.  Your model metadata is available here:
>  
> CICE - https://csdms.colorado.edu/wiki/Model:CICE
>  
> Thank you for your contribution to the CSDMS repository and making your code available to the community!
>  
> CSDMS Integration Facility
> Community Surface Dynamics Modeling System (CSDMS)
> Office: 4001 Discovery Dr. Boulder, CO
> MacAllister Building,Office N141C
> Mailing address: UCB 450, 1560 30th Street, Boulder, CO 80309
> tel: 303-735-5482
> email: csdms@colorado.edu
> web: http://csdms.colorado.edu
>

**Comment by duvivier** [comment]
I just completed entries for both CICE and Icepack. I'll let you know if they contact me requesting any further action.  I added links to the community forum and github repos, but I left @eclare108213 as the "official" contact. Perhaps we should add an update to ask them to remove her info from the entry. Thoughts?

**Comment by eclare108213** [comment]
Thank you @duvivier !  I don't mind being the "official" contact for this - I can always forward to you if anything comes in (which hasn't in the last many years, as far as I know).
