### ISSUE TITLE
Deprecated code features

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#439]
There are some code features that we probably should not continue to maintain, since other, better options are available:  [wiki under construction](https://github.com/CICE-Consortium/CICE/wiki/IN-DEVELOPMENT:-DEPRECATED-CODE-FEATURES)

Note that 3 of the 4 features currently listed are in Icepack, but would also need to be removed from CICE.

This issue is to invite discussion and decide on a time line.  The plan would be to send an email to the cice-users mailing list as a heads-up well before the features are removed from the code, to give users a chance to argue for keeping the options, if they need them.  We could remove the namelist options and documentation first, then remove the rest of the code some months later, in case someone doesn't see the warning email and a change breaks their code - it would be easier for them (and us) to add it back in.

**Comment by eclare108213** [comment]
In general, I would use "less sophisticated" as a reason for deprecating code, although this is in essence the critical point.  

For CESM melt ponds, I might argue that the parameterization is largely based on empirical relationships (from SHEBA) which might not continue to hold in the future, while the other options have more physically based parameterizations and less empirical modeling.

The delta function ITD is less accurate.

The old ridging choices can lead to instabilities, a problem that the new options fixed.

**Comment by eclare108213** [comment]
Another good reason to deprecate upwind advection is that tracers aren't implemented to use it.  See [#267](https://github.com/CICE-Consortium/CICE/issues/267).

**Comment by eclare108213** [comment]
Let's add the old COREII and gx3 bulk forcing to the list of things being deprecated, along with a timeline for each deprecated item.

**Comment by eclare108213** [comment]
I updated the information on the [wiki](https://github.com/CICE-Consortium/CICE/wiki/IN-DEVELOPMENT:-DEPRECATED-CODE-FEATURES) and added potential dates for removing code.  Comments welcome.

**Comment by eclare108213** [comment]
unfortunately the table is too wide and doesn't all show up...

**Comment by eclare108213** [comment]
I have made the [wiki](https://github.com/CICE-Consortium/CICE/wiki/Deprecated-Code-Features) table a little narrower and cleaned up the text.  If no one points out problems with this approach, we will begin implementing it after the next release (likely early next week).  I'm not sure when the documentation should be changed, when the namelist entry is removed from the code or when the full functionality is removed.  For consistency, it's probably best to update the docs at each step.

- [ ] Create a link to the deprecated code wiki page from the resources page
- [ ] Start a thread on the forum for deprecated code discussion
- [ ] Send email to cice-users noting the recent release and future deprecation plans, and invite them to the discussion on the forum
- [ ] Create an issue for each piece of code to be deprecated with the following:
- wait until dates in table have passed to make any changes
- remove namelist entry from the code but leave the functionality in place (also in doc?) 
- later, remove entire functionality from code and documentation

**Comment by eclare108213** [comment]
We discussed this during the June team meeting, and I extended the deadlines in the table.  I will announce this to cice-users to solicit feedback.  We don't have to do this at all, or we could do it on a longer time scale.

**Comment by eclare108213** [comment]
@apcraig @duvivier 
Where do you suggest we link the deprecated code wiki page from existing documentation?
https://github.com/CICE-Consortium/CICE/wiki/Deprecated-Code-Features

**Comment by duvivier** [comment]
@eclare108213 I don't think we want it to be in the main sidebar because it might be confusing. I guess I would suggest in the "CICE Model" section of the Resource Index. Either right above or right below the "CICE Version 5 and Prior" bullet.  @apcraig Do you agree?

**Comment by apcraig** [comment]
I think we can close this?  We seem to have a process in place that we've used several times and will continue to deprecate code using that process as we move forward.
