### ISSUE TITLE
collaboration statement

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#440]
Write a collaboration statement that people can put in proposals that make use of Consortium resources. 

Alice: 

> I can provide the type of statement we have in NCAR proposals, but I have the sense LANL is more strict with this and I don’t know enough about the differences to know exactly how we’ll manage both. It’ll probably require sign off from all member institutions or something, no?

Elizabeth

> I suspect that we already have a statement somewhere on the About-Us wiki, but it's not marked or called out in a noticeable way.  I don't think that LANL has any restrictions on this kind of thing, except that we can not promise a particular amount of FTE time, only that we can help smooth the process as part of our regular Consortium work.

**Comment by eclare108213** [comment]
Here is a draft collaboration statement, please make suggestions.  Is this too much information, or not enough?

With the goal of accelerating scientific sea ice model development and its transfer into operational use, the CICE Consortium is a vehicle for collaboration as the community continues to use and improve the CICE sea ice model and its column physics package, Icepack. Consortium team members are supported through in-kind FTE contributions by their respective agencies, to maintain the current model for existing and new users, and to assist in incorporating and maintaining new research and development.  Community model developers are responsible for following the Consortium’s Software Development Practices, including thoroughly documenting and testing their new and modified code, with guidance from Consortium members.   The Consortium’s codes are open-source with a standard 3-clause BSD license, and a Distribution Policy protects intellectual property rights for shared development code before it is released via a public repository. Scientific review is done by the community in publicly accessible code, leading to further development.

**Comment by duvivier** [comment]
@eclare108213 I think overall this looks pretty good. The first sentence is a bit of a bear, so I might suggest breaking it up. 

Also, the NCAR proposals office often asks us to include a statement like "Please note that UCAR/NCAR participation in this project is contingent on mutually agreed upon terms and conditions." For example, from a proposal I was on as the "free" support (this happens a lot for NCAR): 
I serve as a community liaison for the Community Earth System Model (CESM) Polar Climate Working Group and the CICE Consortium, responsible for developing the CICE sea ice model. Part of my role as liaison is to facilitate polar science in the greater Arctic community. If the proposal submitted by Dr. XXX entitled "XXX” is selected for funding, it is my intent to collaborate and/or commit resources as detailed in the proposal with regards to providing model datasets, assisting with model development, and hosting visiting graduate students. Please note that UCAR/NCAR participation in this project is contingent on mutually agreed upon terms and conditions.

I wonder if we should encourage in there a second paragraph that specifies the project in a proposal, the Consortium member the proposer intends to work with, and the basic "we'll participate as long as rules are followed!" clause. 

Here's what I suggest

>  The CICE Consortium's goal is to accelerate scientific sea ice model development and its transfer into operational use. As such, the CICE Consortium is a vehicle for collaboration as the community continues to use and improve the CICE sea ice model and its column physics package, Icepack. Consortium team members are supported through in-kind FTE contributions by their respective agencies, to maintain the current model for existing and new users, and to assist in incorporating and maintaining new research and development. Community model developers are responsible for following the Consortium’s Software Development Practices, including thoroughly documenting and testing their new and modified code, with guidance from Consortium members. The Consortium’s codes are open-source with a standard 3-clause BSD license, and a Distribution Policy protects intellectual property rights for shared development code before it is released via a public repository. Scientific review is done by the community in publicly accessible code, leading to further development.
>
>As a member of the CICE Consortium, if the proposal submitted by Dr. XXX on the proposal entitled "XXX" is selected for funding (I or Institution's name?) intend to collaborate and/or commit resources as detailed in the proposal. Please note that (Institution name) participation in this project is contingent on mutually agreed upon terms and conditions, including adherence to the Consortium Software Development Practices by the Community Model Developer.

WDTY?

**Comment by eclare108213** [comment]
I like your changes to the first paragraph.  The second paragraph I'm less sure about.  I don't think we should encourage proposers to call out particular people or institutions.  Without that, is there anything in the second paragraph that isn't already captured in the first, other than "contingent on mutually agreed upon terms and conditions" (which I like)?

**Comment by duvivier** [comment]
So maybe this (note I rearranged some of the sentences, but I'm not dead set on those):

The CICE Consortium's goal is to accelerate scientific sea ice model development and its transfer into operational use. As such, the CICE Consortium is a vehicle for collaboration as the community continues to use and improve the CICE sea ice model and its column physics package, Icepack. Consortium team members are supported through in-kind FTE contributions by their respective agencies, to maintain the current model for existing and new users, and to assist in incorporating and maintaining new research and development. The Consortium’s codes are open-source with a standard 3-clause BSD license, and a Distribution Policy protects intellectual property rights for shared development code before it is released via a public repository. Scientific review is done by the community in publicly accessible code, leading to further development. Community model developers are responsible for following the Consortium’s Software Development Practices, including thoroughly documenting and testing their new and modified code, with guidance from Consortium members. Consortium team member participation is contingent upon mutually agreed upon terms and conditions.

**Comment by eclare108213** [comment]
I like this, except I'd add a phrase to the last sentence, 

> Consortium team member participation in community code development is contingent upon mutually agreed upon terms and conditions.

**Comment by duvivier** [comment]
I think that looks good! Now the question is where to put it. What about here:
https://github.com/CICE-Consortium/About-Us/wiki/Contributing
Maybe we can add a new section titled: "Consortium Collaborations on Community Code Development"

**Comment by eclare108213** [comment]
Here is the complete statement under consideration.  The remaining question is where to put it.  See @duvivier's comment above for a suggestion.

> The CICE Consortium's goal is to accelerate scientific sea ice model development and its transfer into operational use. As such, the CICE Consortium is a vehicle for collaboration as the community continues to use and improve the CICE sea ice model and its column physics package, Icepack. Consortium team members are supported through in-kind FTE contributions by their respective agencies, to maintain the current model for existing and new users, and to assist in incorporating and maintaining new research and development. The Consortium’s codes are open-source with a standard 3-clause BSD license, and a Distribution Policy protects intellectual property rights for shared development code before it is released via a public repository. Scientific review is done by the community in publicly accessible code, leading to further development. Community model developers are responsible for following the Consortium’s Software Development Practices, including thoroughly documenting and testing their new and modified code, with guidance from Consortium members. Consortium team member participation in community code development is contingent upon mutually agreed upon terms and conditions.

**Comment by duvivier** [comment]
@eclare108213 Do you want me to move forward here with my suggestion? Or are you just going through items for Thursday's agenda and it can wait till after then?

**Comment by eclare108213** [comment]
I've added this to the agenda for discussion.  Thanks!

**Comment by duvivier** [comment]
I've put the statement up here: https://github.com/CICE-Consortium/About-Us/wiki/Contributing

Note that there is a new section with the statement under the contributing to development section. We can of course tweak it.

**Comment by eclare108213** [comment]
Thanks @duvivier !
