### ISSUE TITLE
Adding ICE_CPPDEFS (and ICE_SLIBS) in cice.settings

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#445]
I would like us to consider adding the environment variables `ICE_CPPDEFS` and `ICE_SLIBS` to `cice.settings`.
This would allow using the present case/test configuration mechanism (`set_env.*` in `configuration/scripts/options/`) to add preprocessor macros and linker flags.

The reason I'm asking is that in the initial implementation of the implicit solver I'm working on, LAPACK is used for the accelerated algorithm (the Anderson solver), but it is not needed for the regular implicit solver (the Picard solver).

So I was thinking of adding a `CICE_USE_LAPACK` preprocessor macro so that the model can still be compiled without LAPACK, and one could opt to define this macro if they want to test the accelerated solver and compile with LAPACK. 

This could be done by manually editing the `Macros.machine_compiler` file in the case directory, modifying `CPPDEFS` and `SLIBS`, but it would be more user friendly to be able to do 
```
./cice.setup -m <machine> -c /path/to/anderson-case -s dynanderson,lapack
```

and to have a file `configuration/scripts/options/set_env.lapack` with content 
```
setenv ICE_CPPDEFS -DCICE_USE_LAPACK
setenv ICE_SLIBS -llapack -lblas
```

This would only require minimal changes to `cice.setup` and `cice.build` (I think) and I would be happy to do that, but I would like to make sure it's something we want to support before spending time doing it.

@apcraig @JFLemieux73 

---

Note that I'm planning on **not** requiring LAPACK for the final implementation of the accelerated solver. As discussed at the tutorial, I would like to first merge a version of the implicit solver that features:
1. The traditional Picard solver (usable in serial or parallel)
2. The accelerated Anderson solver (usable only in serial)

This is almost ready for submission. In a second step I would work on the parallelization of the Anderson solver and remove the dependency on LAPACK.

**Comment by phil-blain** [comment]
Sidenote: I think we could create a "Build system" label for this kind of issues. I don't have permission to do that.

**Comment by apcraig** [comment]
I think this is an excellent idea.  There are a few ways to support this.  This could just be a change in cice.settting and the Makefile, but I don't favor that.  It could be a change in cice.settings and the Macros file.  That might work well.  And maybe there is a mod needed in cice.build, not sure.  I think we want to keep ICE out of the Makefile, so it's a matter of how to get the build env variables into the Makefile via the Macros file.  @phil-blain, I'll assign you to the task, but let me know if I can help.  I'm happy to create a quick PR to address it, it should not be a big deal.

I will add a build label.  That's also a good idea.  I think I have been using Porting for that category, but a separate build label makes sense.

**Comment by phil-blain** [comment]
Thanks. I'll prototype something.
