### ISSUE TITLE
Compiler standard conventions check

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#455]
Check whether icepack and cice meet fortran standard coding conventions using the --std=[f95, f2003, f2008, f2018, gnu, legacy] option with the gnu compiler or --stand [f90,f95,f03,f08,f18] with the intel compiler.  We can then decide whether we want to add this as a part of our standard test suite.

**Comment by phil-blain** [comment]
I'd maybe add that it could be a good idea to compile CICE with `-Wall` and go through each warning (there is a ton of them).
