### ISSUE TITLE
Improve CICE namelist logging

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#456]
Improve CICE namelist logging where possible.  This should at least include adding text to integer options like kitd and ktherm.  

It might be worth considering changing these integer options to text strings, but this will create issues with backwards compatibility in existing namelists as well as break the long history of the values, so that's probably not a practical idea at this point.  Would it be possible to support both integer and character values somehow and have them overlap?

**Comment by eclare108213** [comment]
Is this a different issue from #403?

**Comment by apcraig** [comment]
I think it is.  #403 is more about the community being able to store namelist files used in experiments and providing a repository for that.  This issue is about simply improving transparency and usability in the code itself in namelist and the ice log file.  Instead of "kdyn=1" being reported in the log file, we want something more like "kdyn=1 (evp)".  It's a pretty minor and simple issue, but is probably pretty useful overall.

**Comment by apcraig** [comment]
A lot of work was done in #468.  Should we close this?

**Comment by eclare108213** [comment]
We might want to do this for Icepack but could make an Icepack issue for that.
