### ISSUE TITLE
add to namelist in CICE and Icepack

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#472]
Pstar, Cstar, floediam, hfrazilmin

See also #468

**Comment by apcraig** [comment]
Pstar and Cstar have been added with #475.  floediam and hfrazilmin require an update to Icepack parameters interface then a call from CICE.

**Comment by apcraig** [comment]
Icepack is updated, https://github.com/CICE-Consortium/Icepack/pull/342, will now work on CICE.

**Comment by eclare108213** [comment]
CICE is updated, #536
