### ISSUE TITLE
history output

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#48]
Setting f_hi = 'md' did not produce monthly output.  (Need to check if this is really a bug or if I just didn't have the various history flags set correctly.)

**Comment by rallard77** [comment]
This worked for me. I ran a gx3 60-day smoke test using the following settings:
histfreq       = 'd','m','x','x','x'
histfreq_n     =  1 , 1 , 1 , 1 , 1
f_hi           = 'md'
It produced daily history files and monthly files for January, February 1998

**Comment by eclare108213** [comment]
Thanks Rick!  I must not have had it set up correctly.
