### ISSUE TITLE
JRA forcing initialization/spinup

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#481]
Continuing the discussion from the June 11, 2020 meeting notes:

> To generate new initial conditions for the tripole grid using JRA forcing, Dave B has spun up CICE on the tripole grid for 60 years using the CORE forcing; we only have 5 years of JRA.  The other grids’ initial conditions were created from the CORE forcing, so this might be okay.  Alternatively, David H can interpolate existing data to the tripole grid using a python script, a tool we might want to share more broadly.

What's the status?

**Comment by dabail10** [comment]
I have tested the latest file from @daveh150 and it worked fine. I never heard what the vote was. The options are:

1. Use a CORE forced tx1 initial state after 60 years.

2. Use the gx1 initial file remapped to tx1. Where did the original gx1 come from?

**Comment by eclare108213** [comment]
The original gx1 restart came from a long COREII/AOMIP spinup I did for a publication many years ago - I don't remember which one at the moment!  It might have been my original AOMIP forcing paper with Marika (2007).  But the salinity and enthalpy for mushy are in it now, so maybe it's more recent. Suffice it to say it was with an older, buggier version of the code.  As an initial condition, though, it hasn't been too bad. 

Please remind me the reason why we aren't doing a JRA-55 spinup.   I believe the options for that were to create a restart using the full JRA-55 cycle in a CESM configuration, or for @daveh150 to create a tx1 restart from gx1?  Is there not a JRA-55 spinup on gx1?  Maybe the forcing hasn't been made for the full cycle?  (It's all fine, I'm just trying to get the full picture)

**Comment by dabail10** [comment]
The JRA55 forcing is not available for a full cycle in tx1 format. Also, I have not created a mapping file to do this in CESM.

**Comment by eclare108213** [comment]
@dabail10,  your test with @daveh150's i.c. file "worked fine".  What does that mean, exactly?  It runs...  If they are pretty similar (expected if they're just interpolated versions of each other), then I don't see any reason why that file wouldn't work.  Have you also created a CORE-forced tx1 i.c.?  If so, does the output look reasonable from that restart?  What do the restart fields themselves look like, compared with the existing gx1 restart fields?

**Comment by dabail10** [comment]
Sorry for the vagueness. The initial file he gave me produced some snow energy initialization warnings. The new file did not produce the warnings. Both runs completed 5 days successfully. I can run it longer to see what it looks like after a year.

**Comment by aekiss** [comment]
Apologies if this is irrelevant, but FYI [COSIMA](http://cosima.org.au) is doing a spinup under JRA55-do v1.4.0 with CICE5.1 coupled to MOM5.1 on a nominally 0.1 deg tripolar global grid, starting in 1958. It's up to 1990 so far but will extend to 2019.

**Comment by eclare108213** [comment]
Cool!  That information might be useful for NCAR as they also move toward coupling with MOM.  Thanks for letting us know.

**Comment by dabail10** [comment]
Thanks Andrew. We have several JRA forced high res runs with CICE5 and MOM6 at NCAR as well. This is for the low-res tripole grid which is nominally 1-degree. Most groups do not use this for science. It is generally for testing.

**Comment by eclare108213** [comment]
@dabail10 @rallard77 @daveh150 @CICE-Consortium/devteam 
Let's decide how to move forward with creating JRA55 initialization files for all of our grids.  Decision points are

**1.  Which method should we use?**
Options seem to be 

- spin up CICE v6 in CESM, letting CESM interpolate the JRA55 data - would this be on the same grids we distribute?
- spin up CICE v6 in standalone mode - this would require interpolating the data offline for each grid.
- interpolate the current gx1 initial condition to the other grids, and then spin up for a shorter (?) period of time using JRA data

**2.  How long should the spinup be?**
My preference in this case would be for a full JRA cycle, or at least up to the beginning of the first year of our standard 1- or 5-year forcing (2005).  The spinup should be for a minimum of 10 years, in my opinion, but I'm open to other suggestions.

**3.  Which model configuration should we use?**
My preference would be the set of parameters that produces the most "realistic" results, although that's not well defined.  Instead, my approach in the past has been to start with the parameters and namelist options from CESM's latest configuration and tune them for stand-alone runs.  However CESM doesn't have a lot of experience with CICE v6 yet.  For basic comparison purposes, we could just run with our current default set and see what happens - perhaps a bit dangerous.  I don't think we should get into a big tuning exercise.

**4.  Who does the work?**  
This is partly determined by the options above.

Note: this is one step in fully replacing the forcing for our tests, #249 - we can discuss other aspects there.

**Comment by rallard77** [comment]
NRL recently completed a GOFS 3.1 reanalysis (with data assimilation) 
for the period of 2000-2019. We can offer up to use those CICE fields 
for any start date/year to initialize for the JRA55 runs.

Rick

**Comment by eclare108213** [comment]
That's an interesting idea, to start from a reanalysis product instead of a spinup.  I'm willing.  But this must have been with an older version of CICE?

**Comment by rallard77** [comment]
[JRA55_CICE6_Retrievals.docx](https://github.com/CICE-Consortium/CICE/files/5341495/JRA55_CICE6_Retrievals.docx)
Here is documentation on how to retrieve JRA55 file for use in CICE. Let me know if the documentation is clear. If someone wants to try downloading a dataset, that would be great.
The second part of the documentation will provide information and a Python script on interpolating the data to the gx1 grid.

**Comment by eclare108213** [comment]
Was there a decision on what to do about the initialization?

**Comment by apcraig** [comment]
Can this be closed?

**Comment by eclare108213** [comment]
Yes.  #350 #408 #435 #533 #562 #566 #582
