### ISSUE TITLE
Send fswthru by categories to coupler

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#482]
This will involve adding the variable fswthrun_ai to ice_flux.F90 and a logical namelist flag, send_i2x_per_cat.

**Comment by apcraig** [comment]
Is this complete?  See https://github.com/CICE-Consortium/Icepack/pull/320 and #479.

**Comment by dabail10** [comment]
This is not complete. This is a different animal. I am wanting to send the broadband fswthru (not components) but for each category (fswthrun).
