### ISSUE TITLE
melts diagnostic bug

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#484]
In the last part of the thickness_changes, when the sea ice completely melts away, the snow melt here is not added to melts. This is mostly diagnostic and likely will not change answers as the ice is going away for these points. It will change the history output and budgets that rely on melts.

**Comment by apcraig** [comment]
Is this https://github.com/CICE-Consortium/Icepack/pull/328?

**Comment by dabail10** [comment]
Yes it is. I put the issue in the CICE Issues. Should it be in Icepack issues? I am currently working on running the QC tests with this fix.

**Comment by apcraig** [comment]
It could be in Icepack, but also fine here.  Glad to hear testing is proceeding, update the PR when you have some more results.  Thanks!

**Comment by apcraig** [comment]
This was fixed in Icepack but has not yet been merged into CICE.
