### ISSUE TITLE
shortwave redistribution

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#485]
The changes are in a pull request here, but this adds a namelist option and parameters for shortwave redistribution from the internal layers to the surface. This was in icepack_therm_bl99.F90, but not in icepack_therm_mushy.F90.

**Comment by eclare108213** [comment]
See #479

**Comment by apcraig** [comment]
I think this is not #479, I think it's https://github.com/CICE-Consortium/Icepack/pull/326.  We need to create a CICE PR that updates Icepack, adds namelist to CICE, and adds calls to Icepack parameters to set the new Icepack variables.
