### ISSUE TITLE
Bug in log output for atmbndy.

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#493]
I believe this logic is incorrect for atmbndy.

         if (trim(atmbndy) == 'constant') then
            tmpstr2 = ': stability-based boundary layer'
            write(nu_diag,1012) ' highfreq         = ', highfreq,' high-frequency atmospheric coupling'
            write(nu_diag,1022) ' natmiter         = ', natmiter,' number of atmo boundary layer iterations'
            write(nu_diag,1006) ' atmiter_conv     = ', atmiter_conv,' convergence criterion for ustar'
         elseif (trim(atmbndy) == 'default') then
            tmpstr2 = ': boundary layer uses bulk transfer coefficients'
         endif

That should be if atmbndy = 'default'.

**Comment by eclare108213** [comment]
Ok.  Maybe the next person who puts in a PR can fix this, or add it to a current one.

**Comment by dabail10** [comment]
I could do this, but I don't have a CICE PR coming up.

**Comment by apcraig** [comment]
I'm fixing this in a PR now.  Just to clarify, the if tests just need to be switched?  The first if should be "default" and the second should be "constant"?

**Comment by dabail10** [comment]
That's correct. Thanks Tony.

**Comment by apcraig** [comment]
Fixed in #494
