### ISSUE TITLE
improve PR template

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#50]
Let's make the templates (both CICE and Icepack) a little less cryptic and hopefully a little more useful.

**Comment by eclare108213** [comment]
My recommendation (other suggestions are welcome):

[Remove this and add a short summary line]:
Developer(s):
Is the documentation being updated with this PR? (Y/N):
If not, does the documentation need to be updated separately? (Y/N)
Are the code changes bit for bit, different at roundoff level, or more substantial?:
Please suggest code reviewers in the column at right. 
Other Relevant Details:

**Comment by eclare108213** [comment]
My edits to the comment above are not showing up correctly, so I'll try again in a fresh comment:

[Remove this and add a short summary line]:
Developer(s):
Are the code changes bit for bit, different at roundoff level, or more substantial?:
Is the documentation being updated with this PR? (Y/N):
If not, does the documentation need to be updated separately? (Y/N)
"Documentation" includes information on the wiki and .rst files in doc/source/, which are used to create the online technical docs at https://cice-consortium.github.io/CICE/ .
Please suggest code reviewers in the column at right. 
Other Relevant Details:

**Comment by eclare108213** [comment]
The comment still isn't coming through correctly.  I'll make a PR and we can discuss it there.

**Comment by dabail10** [comment]
I took a look and I think it is fine. I reviewed and approved it.

**Comment by duvivier** [comment]
I agree with Dave. I confirmed the change through the PR a few days ago. We can close this issue.
