### ISSUE TITLE
Improve colormap ticks for QC test generated figures 

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#501]
I noticed that the third figure generated by the Python QC test (the difference between "base" and "test") could use a tweak so that the ticks of the colorbar appear in scientific notation, since these values are usually small.

Example:

![ice_thickness_daley_intel_smoke_gx3_8x1_medium_qc qc_minus_daley_intel_smoke_gx3_8x1_dynpicard_medium_qc qc](https://user-images.githubusercontent.com/44212482/84541228-fad43480-acc4-11ea-873f-24cf0c39c9eb.png)

@mattdturner

**Comment by mattdturner** [comment]
@phil-blain I just created a PR to address this (#506 )

**Comment by phil-blain** [comment]
#506 mas merged, closing this.
