### ISSUE TITLE
debug regression test fails in ufs-s2s-model

### ISSUE THREAD

**Issue by DeniseWorthen** [CICE-Consortium/CICE#502]
We are bringing CICE6 into ufs-s2s-model. One Regression test is the 6h debug test. We compile the entire coupled system in debug mode (components as well as esmf debug library). The test failed for cice6 with this error:
<img width="745" alt="Screen Shot 2020-08-15 at 6 32 27 PM" src="https://user-images.githubusercontent.com/40498404/90334067-df252d00-df98-11ea-96bf-b555d5da9157.png">

We had previously fixed this in emc-cice5; a comparable fix in cice6/icepack is shown
[here](https://github.com/CICE-Consortium/Icepack/compare/master...DeniseWorthen:feature/cice6debug)

**Comment by dabail10** [comment]
Ok. I will fix this in CICE6 as well. Good catch.

**Comment by dabail10** [comment]
I'm not sure your fix is the best way to go. Can you post some details of the configuration of the test that is failing? Is it ncat=1? How is your ITD set up here? This is in the ice log file. Look for hin_max here.

**Comment by DeniseWorthen** [comment]
Let me get it repeated on Hera and I can provide both the information and a run directory for you to look at.

**Comment by DeniseWorthen** [comment]
There is a run directory on Hera:

/scratch1/NCEPDEV/stmp2/Denise.Worthen/S2S_RT/rt_199411/cpld_fv3_ccpp_mom6_cice_cmeps_cold_debug

The output log is in "out" and the err in "err". 

This is our "cold start" run, using a C96 atm and the 1/4 degree MOM6+CICE5, so the we're just starting up from initial conditions in a sequential run sequence. 

We are using the restart file generated from CFSR (using the ncl script you wrote long ago) with ncat=5.

**Comment by dabail10** [comment]
Great, thanks. Here is the fix I would propose for this:

             denom = max(puny,hicen_init(n+1) - hicen_init(n))
             slope = (dhicen(n+1) - dhicen(n)) / denom

where denom is a new variable. This limits the situation as denom goes to zero.

**Comment by DeniseWorthen** [comment]
Hi Dave,

I made your change [here](https://github.com/CICE-Consortium/Icepack/compare/master...DeniseWorthen:feature/cice6debug)  and it passes our debug regression test so I'm happy with it. I only left out the description of the denom variable in the declaration. Any suggestions?

**Comment by dabail10** [comment]
It is the denominator for computing the slope in the hbnew calculation.

**Comment by DeniseWorthen** [comment]
I thought there might have been specific rules for describing variables (like w/ MOM6).

**Comment by dabail10** [comment]
Oh no. This is what I am submitting in the PR:

         denom        , & ! denominator in hbnew calculation

**Comment by DeniseWorthen** [comment]
Do you need me to change anything? Sounds like you'll PR from your own fork.

**Comment by dabail10** [comment]
I will send the PR to the CICE Consortium and you can update from there. Thanks for testing it though.
