### ISSUE TITLE
bug in icepack_therm_mushy

### ISSUE THREAD

**Issue by TillRasmussen** [CICE-Consortium/CICE#503]
In icepack_therm_mushy dt_rhoi_hlyr (line 261) is defined and used but there is no value set. This results in a warning.

Should it be defined as in CICE/icepack/columnphysics/icepack_therm_bl99.F90 ?

dt_rhoi_hlyr = dt / (rhoi*hilyr)  ! hilyr > 0

**Comment by dabail10** [comment]
Good catch here as well. I copied the code from icepack_therm_bl99.F90, but likely forgot this. I will fix it.
