### ISSUE TITLE
Doc for box2001

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#509]
The doc says that coriolis=0 for this test case. It should be f=1.46e-4. I am testing this right now and the code is fine and consistent with Hunke 2001.

**Comment by phil-blain** [comment]
Indeed, the option file for `box2001` has `coriolis = 'constant'` : 

https://github.com/CICE-Consortium/CICE/blob/e5ff1f2431ff2df5acbe132c88de9cdb027f4f16/configuration/scripts/options/set_nml.box2001#L22

and this is hardcoded to 1.46e-4:
https://github.com/CICE-Consortium/CICE/blob/e5ff1f2431ff2df5acbe132c88de9cdb027f4f16/cicecore/cicedynB/dynamics/ice_dyn_shared.F90#L172-L173

I can do a quick PR to fix the doc.

**Comment by JFLemieux73** [comment]
Please do.
