### ISSUE TITLE
Wind stress components are not multiplied by aiu in box2001 experiment

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#516]
I am running a 'modified' box2001 exp for a special project (I have turned on advection and ridging compared to the standard box2001 exp). The model crashes. I think this is due to the fact that strairx and strairy are not multiplied by aiu (aice at u-point). Note that the components of the water stress are correctly multiplied by aiu.

**Comment by JFLemieux73** [comment]
We should also check other experiments with calc_strair = .false.

**Comment by JFLemieux73** [comment]
@eclare108213 I would need your input before I try to fix this issue.

I think the best place to fix this is in dyn_prep2. It could be something like:

if (trim(atm_data_type) == 'box2001') then
  forcex(i,j) = aiu(i,j)*strairx(i,j) + strtltx(i,j)
  forcey(i,j) = aiu(i,j)*strairy(i,j) + strtlty(i,j)
else
  forcex(i,j) = strairx(i,j) + strtltx(i,j) ! strairx and strairy already include aiu
  forcey(i,j) = strairy(i,j) + strtlty(i,j)
endif

The problem with this is that it does not take into account other experiments that have calc_strair=.false. and ktherm<0 (are there any other experiments?).

So I think it should be 

if (.not. calc_strair .and. ktherm < 0) then
  forcex(i,j) = aiu(i,j)*strairx(i,j) + strtltx(i,j)
  forcey(i,j) = aiu(i,j)*strairy(i,j) + strtlty(i,j)
else
  forcex(i,j) = strairx(i,j) + strtltx(i,j) ! strairx and strairy already include aiu
  forcey(i,j) = strairy(i,j) + strtlty(i,j)
endif

Let me know

**Comment by eclare108213** [comment]
@JFLemieux73 thanks for following up.  In my opinion, our variables should always mean the same thing, not change during a calculation or mean different things for different configurations.  I know the code already has some of these problems, and there's an issue flagging some of them.  This question is only partly rhetorical:  can we begin to fix them now, or does it make the most sense to kludge this and implement a better design later?

For strairx/y, what are the configuration combinations that are problematic?  calc_strair=T includes the factor and calc_strair=F doesn't?  If it's different for various atm_data_types, then can we make those all consistent?

**Comment by TillRasmussen** [comment]
@eclare108213 @JFLemieux73 Would it be more natural to put it in the get_forcing
When is ktherm < 0. Does that disable thermodynamics?
Would it be natural to make this adjustment in prepare forcing (ice_forcing.F90)? and leave corrections like that out of the evp method?

**Comment by JFLemieux73** [comment]
Thanks @eclare108213 and @TillRasmussen. Yes if ktherm<0 then thermodynamic is disable. The problem is that merge_fluxes is not called neither (the strair are summed for all the partial concentrations in merge_fluxes). To solve this issue we need to take care of calc_strair, ktherm and the specific experiments. I will investigate more and get back to you.

**Comment by eclare108213** [comment]
I see.  Having the strair calculation in the thermodynamics has always been a problem when running dynamics-only tests.  The best solution for this type of configuration, in my opinion, would be to create all of the forcing in ice_forcing.F90.  There could be a special routine there that takes care of what the thermo would normally do, or if the code is small, include it in existing routines.  Since aice is changing, there might be a mismatch due to the points during the timestep that things are calculated and used, but for testing maybe it's okay.

**Comment by apcraig** [comment]
See #525 

Should this now be closed?
