### ISSUE TITLE
for grid_type=tripole, ice_init prints garbage for ns_boundary_type

### ISSUE THREAD

**Issue by DeniseWorthen** [CICE-Consortium/CICE#520]
When ice_init finds ``grid_type=tripole``, it next tries to document the ``ns_boundary_type`` as being either on the U or T grid points. It does this by writing the ns_boundary_type variable as ``tmpstr2``. This variable does not seem to have been set at this point however, because it prints a garbage character string.

**Comment by apcraig** [comment]
This is fixed in #532.
