### ISSUE TITLE
Consider distributing useful shell aliases/functions with the repo

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#523]
Following the discussion we had earlier this year about the useful `cdrun`/`cdcase` shell aliases that are now [documented](https://cice-consortium-cice.readthedocs.io/en/latest/user_guide/ug_running.html#overview), I'd like to share additional aliases and functions that I'm using. These are mostly for Bash but could be easily converted to csh syntax.

I was also thinking that we could, if we wished, mention them in the documentation, or even provide  `.cice-helpers.sh` and `.cice-helpers.csh`  files in the CICE repo that users could then simply source in their shell startup files.

Anyway here are my CICE aliases:

**`~/.tcshrc`**:
```csh
# From a case or run directory, source the necessary environment files to run CICE
alias cice_env 'source env.*; source cice.settings'
# Go from case directory to run directory and back (see https://stackoverflow.com/a/34874698/)
alias cdrun  'set rundir=`\grep "setenv ICE_RUNDIR" cice.settings | awk "{print "\$"NF}"` && cd $rundir'
alias cdcase 'set casedir=`\grep "setenv ICE_CASEDIR" cice.settings | awk "{print "\$"NF}"` && cd $casedir'
```

**`~/.bashrc`**:
```bash
## Aliases
# From case/test directory, go to run directory
alias cdrun='cd $(cice_var ICE_RUNDIR)'
# From run directory, go to case/test directory
alias cdcase='cd $(cice_var ICE_CASEDIR)'
# monitor current cice run (from ICE_RUNDIR directory)
alias cice_tail='tail -f $(ls -1t cice.runlog.* |head -1)'
# open log from last CICE run (from ICE_CASEDIR directory)
alias cice_lastrun='$EDITOR $(ls -1t logs/cice.runlog.* |head -1)'
# open log from last CICE build (from ICE_CASEDIR directory)
alias cice_lastbuild='$EDITOR $(ls -1t logs/cice.bldlog.* |head -1)'
# show CICE run directory when run in the case directory
alias cice_rundir='cice_var ICE_RUNDIR'
# open a tcsh shell and source env.* and cice.settings (useful for launching CICE in a debugger)
alias cice_shell='tcsh -c "cice_env; tcsh"'
# From a CICE suite directory, get the testid
alias cice_testid="\grep 'cat' results.csh|head -1|sed -e 's/cat .*\.\(.*\)\/test_output >> results\.log\.*/\1/'"

## Functions
# Print the value of a CICE variable ($1) from cice.settings
cice_var() {
\grep "setenv $1" cice.settings | awk "{print "\$"3}"
}
# Ensure that ICE_CLEANBUILD is set to false
cice_buildincremental () {
[ $(cice_var ICE_CLEANBUILD) == "true" ] && ./casescripts/parse_settings.sh cice.settings $(cice_var ICE_SCRIPTS)/options/set_env.buildincremental
}
# Ensure that ICE_BLDDEBUG is set to true
cice_builddebug () {
[ $(cice_var ICE_BLDDEBUG) == "false" ] && ./casescripts/parse_settings.sh cice.settings $(cice_var ICE_SCRIPTS)/options/set_env.debug
}
# Change number of procs ($1) and recreate/modify necessary files
cice_setnprocs () {
nprocs=$1
# cice.settings
./casescripts/parse_settings.sh cice.settings <(echo "setenv ICE_NTASKS $nprocs")
# cice.run
tcsh -c 'cice_env && ./casescripts/cice.run.setup.csh cice.run'
# ice_in
./casescripts/parse_namelist.sh ice_in <(echo "nprocs = $nprocs")
}
```

**Comment by eclare108213** [comment]
Many of these look very useful.  Others, like changing the number of processors, might be confusing to users - wouldn't we want them to just create a new case for that?

**Comment by apcraig** [comment]
I have somewhat mixed feelings about putting these scripts in the repository for a few reasons, mostly related to general usefulness and maintenance.  But I don't have a problem adding some of this to the documentation.  Maybe we should create a new section in the documentation called something like "Useful Shell Aliases" or something?

**Comment by phil-blain** [comment]
Yes, I agree, just in the doc would be good. Or, in the wiki somewhere, though I tend to prefer in the doc.

A new section would be good, I think.

**Comment by eclare108213** [comment]
I like the idea of adding these to the doc.  If others request it, we could consider making a 'helpers' script later, although I think that could become confusing and more difficult to document and maintain.

**Comment by apcraig** [comment]
A new section was added to the user guide to provide some examples of aliases.  This can evolve over time, but will close this for now.
