### ISSUE TITLE
updates needed for verbose diagnostic output

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#534]
I have scanned the [‘verbose’ output](https://github.com/CICE-Consortium/CICE/pull/468) in the log files for base_suite.  Here are some suggested updates:

- [x] move bathymetry_format one space to the left
- [x] kevp_kernel=0 should be labeled “original EVP solver”, correct?  And the other value (in alt01) is “vectorized EVP solver”?
- [x] do we need both “advection” and “ktransport” once upwind is deprecated?
- [x] atmiter_conv appears to be 0 all the time.  Maybe the formatting should be the same as is used for dSdT_slow_mode.
- [x] new namelist variables should be added to the verbose diagnostic prints, e.g. floeshape, floediam, hfrazilmin?
- [x] I don’t think close_boundaries should be printed, since there’s not really an option there.  (?)
- [x] sw_redist, sw_frac, sw_dtemp should be listed under Radiation instead of Thermodynamics, and sw_frac and sw_dtemp should only be listed when sw_redist=T.
- [ ] Many of our tests aren’t highlighted in the verbose diagnostics (i.e., the verbose diagnostics are incomplete)
- [x] The VP namelist parameters should be added to the verbose diagnostics when kdyn=3 (and printed depending on the configuration e.g. fgmres, pgmres etc)
- [x] Nothing is printed when thermo is turned off.  When ktherm=-1, print “Thermodynamics off”, and don’t print the Radiation block since it's irrelevant.  (e.g. gbox80_1x1_box2001)
- [x] ns_boundary_type formatting is bad for tx1_40x4_dsectrobin_medium - wasn’t this fixed already?

**Comment by apcraig** [comment]
Working on a branch called swnml to fix these issue.  Many are straight-forward.  I have a sandbox and will create a PR soon to support further discussion.  A few questions,

- "verbose diagnostics are incomplete".  Are there some obvious things we know we need to add?  The alternative is to go thru all the namelist and figure out which we're not writing out.  Suggestions?

- The vp namelist were printed but in the "other namelist" section.  I have moved them into the dynamics.  It could be that more "if" checks need to be added for printing.  If we want to do that, some guidance would be helpful about how to organize the vp namelist into appropriate groups.

- The ns_boundary_type is not yet defined in ice_init.  It is read in domain_nml which happens later.  I have removed the ns_boundary_type output.  It is written out to the log file when it's read in later.  If we need to move ns_boundary_type from domain_nml to grid_nml, let me know.  But I recommend against that (for backwards compatibility) at this point.  For now, I'll leave it in domain_nml.

**Comment by eclare108213** [comment]
Cool, thanks.

> * "verbose diagnostics are incomplete".  Are there some obvious things we know we need to add?  The alternative is to go thru all the namelist and figure out which we're not writing out.  Suggestions?

This is not necessarily something we need to fix right away, but if it's easy then we could make some headway.  I noticed it because I was only reading through the verbose diagnostics section of the log files when checking whether the various base_suite settings made sense with one another, and in some cases, there was no indication in that section of what the test was doing - it only listed the default settings, so I had to diff the log file with one from a 'real' default run (or else look at Tony's spreadsheet).  This is not surprising, since I prioritized what went into the verbose section based on what I thought a user writing a general-purpose description of the model would want to include in a journal article.   This is low priority IMHO, although it means I might have missed some conflicting physics in my review.

> * The vp namelist were printed but in the "other namelist" section.  I have moved them into the dynamics.  It could be that more "if" checks need to be added for printing.  If we want to do that, some guidance would be helpful about how to organize the vp namelist into appropriate groups.

Maybe @JFLemieux73 and @phil-blain can help with this.  There are some parameters that are only used for VP, some only for EVP or EAP, some maybe for both...

> * The ns_boundary_type is not yet defined in ice_init.  It is read in domain_nml which happens later.  I have removed the ns_boundary_type output.  It is written out to the log file when it's read in later.  If we need to move ns_boundary_type from domain_nml to grid_nml, let me know.  But I recommend against that (for backwards compatibility) at this point.  For now, I'll leave it in domain_nml.

Agreed.

**Comment by apcraig** [comment]
There is a draft PR, #540 with these changes.  I am testing now.  But I am also happy to make additional changes.

With regard to the "verbose diagnostics incomplete".  It sounds like it might be helpful to put a * (or something) next to namelist that are not set at default values.  That would take quite a bit of work and I think should be a standalone effort.  Or am I missing the point?

The vp outputs are pretty well highlighted in the diff.  As I said, I moved them from "other" to dynamics.  I think they are only written if kdyn=3.  Again, happy to introduce additional refinements if it's helpful.
