### ISSUE TITLE
move shortwave parameters from thermo namelist to shortwave namelist

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#537]
sw_redist, sw_frac and sw_dtemp are in the wrong namelist, in both CICE and Icepack

**Comment by dabail10** [comment]
I am fine with this, however I put it in the thermo namelist as this is where the code is (ice_therm_vertical.F90).

**Comment by eclare108213** [comment]
Thanks for the explanation @dabail10.  I generally think of the namelist sections as capabilities rather than locations in the code, since some capabilities are spread out in many places.  Radiation is one of those...  Of course, the dEdd_algae parameter is in the BGC namelist.  It's a complex, highly intertwined system!
