### ISSUE TITLE
timeseries plotting errors

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#538]
The timeseries plotter appears to be picking up values that it should not.

These issues were noted in #533, for nonstandard plots (so the problem might be my editing of the timeseries script, rather than a problem originally in the script).  They occur with all types of forcing (JRA, CORE, NCARbulk).  I'm attaching two examples, one for sst and one for the area-weighted total energy plots.
[examples.zip](https://github.com/CICE-Consortium/CICE/files/5653726/examples.zip)

In the sst example,

```
grep sst cice.runlog* > sst_gx1_jra_all
grep "sst (C)" cice.runlog* > sst_gx1_jra_C
diff sst_gx1_jra_all sst_gx1_jra_C > diff_sst
less diff_sst

<  min/max sst, frzmlt
<   min, max, sum =  -1.96869665044293        32.9603346231369        1525878.86583381      sst
33d30
<   min, max, sum =  -1.90458264992426        32.7596970527221        1530936.61448477      sst
64d60
<   min, max, sum =  -1.90458264992426        31.7854126938785        1534787.65564628      sst
95d90
<   min, max, sum =  -1.90458264992426        31.9466864214512        1526806.43659672      sst

```

The last values (~1.5e6) in the latter four lines in the diff_sst file appear to correspond with the four spikes in the plot.  The timeseries plot was created with timeseries_all.csh, which greps on the "ssh (C)" form, so I don't think it should be picking up these values.  But maybe I don't understand how the script works.  Could this be a line-continuation problem?

A similar thing seems to be happening in the arwt_tot_energy plot (but not for the arwt_tot_energy_chng plot).

I didn't try the python script.

Also, it might be nice to add options for plotting more variables to the script (or add scripts).  Just a thought.

**Comment by mattdturner** [comment]
@rallard77 Had contacted me last week about a similar issue.  I think I have a quick fix for both the `timeseries.csh` and `timeseries.py` scripts that should resolve the issue with these fields.  I'm testing it now, and will create a PR once I'm satisfied with the change.

> Also, it might be nice to add options for plotting more variables to the script (or add scripts). Just a thought.

A while back I briefly tried adding an option to allow users to pass variables as command line arguments.  I forget the issues that I ran into, but I can look at it again.
