### ISSUE TITLE
Step therm1 using vertex velocity instead of cell velocity

### ISSUE THREAD

**Issue by mattdturner** [CICE-Consortium/CICE#544]
There was a recent [bugfix PR in MPAS-seaice](https://github.com/MPAS-Dev/MPAS-Model/pull/773) that addressed an issue in step therm1 where the vertex velocities were being used instead of cell center velocities.  Per that PR:

> This bug involves Step therm 1 using the vertex ice velocity rather than the interpolated cell ice velocity. This has been there since the code was written and follows what CICE does:
https://github.com/CICE-Consortium/CICE/blob/master/cicecore/cicedynB/general/ice_step_mod.F90#L327
This is much less of a problem with CICE since the vertex velocity of the same indices is always close (one of the cell vertices) to the cell velocity of the same indices. That is not true for MPAS-Seaice where a vertex velocity of a given index might be on the other side of the partition from the cell velocity of the same index. A consequence of this for CICE is that CICE is not invariant for a transformation of the grid that leaves the physical cell positions unchanged but alters the indices used to label those cells.

**Comment by eclare108213** [comment]
Thanks for pointing that out @mattdturner 
This does not need to be fixed in Icepack itself, only the fields that are passed to it from CICE.

**Comment by proteanplanet** [comment]
@eclare108213 Please can you create a pull request to fix this - I'm up to my arms in E3SM work at present.

**Comment by eclare108213** [comment]
@mattdturner @proteanplanet
Do I understand correctly that the assumption here is that the wind components arrive in the cell centers rather than on the vertices, since the ice velocities are only used to compute the wind stress components?  Do we need to be more careful here that the ice and atmo velocities are consistent, located in the same place in the cell?

Related question for @rallard77 @daveh150:  are the JRA vector quantities colocated with the temperatures etc?

**Comment by proteanplanet** [comment]
> @mattdturner @proteanplanet
> Do I understand correctly that the assumption here is that the wind components arrive in the cell centers rather than on the vertices, since the ice velocities are only used to compute the wind stress components? Do we need to be more careful here that the ice and atmo velocities are consistent, located in the same place in the cell?
> 
> Related question for @rallard77 @daveh150: are the JRA vector quantities colocated with the temperatures etc?

In principle, yes.  An inherent assumption is that Icepack is being coupled to other models or data only at the scalar (tracer) grid points, and that our column is spatially unaware.  However, fixing this is a bigger issue than can be addressed in this one circumstance, and therefore the PR you submitted is sufficient for now.  But it's an issue.  We are making the implicit assumption that scalar coupling has low diffusivity, while dynamic coupling is strongly diffusive as we do it now.

**Comment by daveh150** [comment]
The JRA55 model is run on a Reduced Gaussian grid. As far as I can tell they are all co-located (i.e., no staggering). The NetCDF’s we receive only have one set of Lat/Lon coordinates 

 

Also, In the python method we made, all JRA quantities are interpolated to the “TGRID”. I did not interpolate vector quantities to the “UGRID”. Please advise if that is not correct and I will update to use UGRID for winds.

 

Thanks,

David

**Comment by eclare108213** [comment]
@daveh150 this is fine, thank you.  We just need to know (maybe make this explicit in the documentation), and then make sure that our tests are configured for vector forcing coming in on the T grid.  I think that's the case but we should check.
