### ISSUE TITLE
JRA forcing 1996 to 1997

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#558]
I am tracking this down, but I have an issue as follows.

1. I start a 5 year run in 1995 with the JRA forcing I created.
2. The run aborts on Dec 31st of 1996 with bad air temperature values.
3. Seems to be related to leap_years = .true. and the JRA forcing.
4. When I do a continue run from January 1st, 1996 and run 5 years it goes fine.

**Comment by phil-blain** [comment]
Might be related to what I documented in https://github.com/CICE-Consortium/CICE/issues/343#issuecomment-525863547 and later comments in that issue...

**Comment by apcraig** [comment]
There was a bug in the JRA55 forcing implementation that was fixed in #562.  See also #343.
