### ISSUE TITLE
Implement new grounding parameterization for landfast ice

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#559]
This new approach calculates the probability of contact between ridges (determined from the ITD) and the seabed. From this probability of contact (and assuming isostatic balance), the parameterization calculates the seabed stress for the momentum equation.

Note that we think that seabed stress is a better expression than basal stress. So the code and documentation will be modified to reflect this. The old parameterization is referred to as seabed1 and the new one as seabed2.

**Comment by JFLemieux73** [comment]
I have implemented the new approach in the latest code. In gx3 simulations, the seabed1 method (with changes to the code) is BFB with the same gx3 simulation with the reference code (before my changes). 

seabed2 runs (gx3) and does not crash. I need to evaluate it in gx1 simulations and compare the results with seabed1.

**Comment by JFLemieux73** [comment]
@eclare108213 I have a question regarding use_bathymetry in ice_in. I was testing the grounding schemes and did not understand what was going on until I realized that use_bathymetry is by default set to .false. Can we have something like if basalstress=.true. then use_bathymetry=.true.???

**Comment by eclare108213** [comment]
@JFLemieux73  We've generally moved away from automatically resetting namelist flags based on other namelist flags -- we either abort or else print out a warning.  When basalstress was first implemented, we didn't have bathymetry files for our test grids.  We (you!) added that (for all of them?), but code users might still want to run the code in an unfinished configuration, just getting things set up.  So my suggestion would be to just print out a warning.  If you think that isn't enough, we could abort with a message.

**Comment by JFLemieux73** [comment]
Thanks @eclare108213. I have the impression that a warning might not be noticed. How about it is by default set to  use_bathymetry=.true. ? If someone tries to model landfast ice and does not have a bathymetry file then the code aborts  (or course) but with a message saying that the user could still test it by setting use_bathymetry=.false.

**Comment by eclare108213** [comment]
For cases like this, the -s option files can be useful - they aren't just for testing!  Create one that includes your preferred basalstress/bathymetry/etc default settings, understanding that it can be combined with other -s configuration options that aren't specific to landfast ice, and then point out in the landfast ice documentation that it exists?

**Comment by JFLemieux73** [comment]
Ok! I will look into that.

**Comment by JFLemieux73** [comment]
Ran 1yr of seabed1 and seabed2 on gx1 grid. The figures show the mean of tauby in April. 
For seabed1:
[tauby_seabed1.pdf](https://github.com/CICE-Consortium/CICE/files/5895826/tauby_seabed1.pdf)
For seabed2:
[tauby_seabed2.pdf](https://github.com/CICE-Consortium/CICE/files/5895827/tauby_seabed2.pdf)

**Comment by JFLemieux73** [comment]
The zones of grounding are similar with both schemes (good). Both schemes show non zero taub in regions where we expect grounding (coast of Alaska, East Siberian, Laptev). Note that seabed2 has less grounding in Laptev. This probably depends a lot on x_kmax. It is set to x997 based on optimization with CICE-NEMO 0.25 degree hindcasts.

**Comment by dupontf** [comment]
Good progress JF! The distribution looks a bit different but maybe for a good reason, like you said.

**Comment by JFLemieux73** [comment]
I realized sigma_b was not set properly in seabed2 (0.5 instead of 2.5 m). This likely explains why there was less grounding than expected. I also used k1=7.5 instead of 8 for seabed1 (to be consistent with Dupont et al, in prep). I ran again gx1 for seabed 1 and 2. Here is tauby (mean for April), capped at + and - 0.01 Nm-2. 

![tauby_seabed1_k1_7p5](https://user-images.githubusercontent.com/31927797/107697705-90272e80-6c81-11eb-9009-fec179b38b47.png)

for seabed2:

![tauby_seabed2_sigb2p5](https://user-images.githubusercontent.com/31927797/107697760-a59c5880-6c81-11eb-8463-4d05bd5029f3.png)

**Comment by JFLemieux73** [comment]
I have retested both methods after changes requested for the PR. The results are the same as shown above.

**Comment by apcraig** [comment]
I think this was addressed in #565, can we close?

**Comment by JFLemieux73** [comment]
Yes we can close it.
