### ISSUE TITLE
Bathymetry file for tx1 grid

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#563]
@dabail10 I created an issue to document what I am doing (I guess I should have done that for the gx and gx1 bathymetry files...)

**Comment by JFLemieux73** [comment]
I have followed the same approach I used to produce the gx and gx1 bathymetry files. 

see here:
/users/dor/armn/jfl/cetus3/CICE6_Dev_and_test/CICE6_bathy/BATHYgx3_gx1. (see README_bathy)

For the new grid:
/users/dor/armn/jfl/cetus3/CICE6_Dev_and_test/CICE6_bathy/BATHYtx1

I started with the ORCA12 bathymetry and interpolated it on the ORCA025 grid (nearest neighbor) using the cstintrp (see bathyorca12_orca025.ksh). 

Using the matlab routine createBathy.m, I interpolated the ORCA025 bathy to the tx1 grid (nearest neighbor). The minimum depth is set to 10 m. As the tx1 (same for gx3 and gx1) is kind of low resolution for landfast ice I have "manually" modified a few cells to avoid grounding at some places (e.g. make sure the ice flows through Bering Strait...). This was done with the routine polish_tx1.m.  

note: to write the tx1 bathy in a netcdf file, I used the command nc_varput. Strangely it is not working with the version of matlab (R2020b) on galois. I had to use matlab at McGill (R2020a).

**Comment by eclare108213** [comment]
If we eventually offer grid generation scripts, then including this functionality would also be nice.  That's probably a long way off...

**Comment by dabail10** [comment]
I have tested this file and it is working within CICE.

**Comment by JFLemieux73** [comment]
Thanks @dabail10.  I will close the issue.
