### ISSUE TITLE
review dynamics namelist parameters

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#575]
We have several more namelist parameters controlling various aspects of the dynamics, such as rheology, solver, basal stress term, etc.  The namelist flags need to be consistent, but we also need to maintain backward compatibility, if possible.

**Comment by eclare108213** [comment]
I reviewed **dynamics_nml** for rheology and solver choices.  I think it is fine the way it is.

`kdyn` chooses the rheology (EVP, EAP, VP) or turns the dynamics off.  For EVP there are solver choices (`kevp_kernel`, `revised_evp`, several parameter values).  For VP there are also solver choices (`precond`, `ortho_type`, etc).  There is also a `yield_curve` namelist flag, which isn't being used now (it's always 'ellipse') but is ready for Mohr-Coulomb.

`kevp_kernel` is 0 for the standard EVP (2D) solver.  I suggest using `kevp_kernel=1` for the 1D solver.  Change the "not fully validated" comment in the dynamics_nml documentation, when that is fixed.

Also, as long as someone is editing that doc file, please fix the spelling of Gram-Schmidt for `ortho_type`.

**Comment by phil-blain** [comment]
@eclare108213  writes in https://github.com/CICE-Consortium/CICE/pull/566/files#r584937968:
> This should be in a different PR, but can we come up with something better than 'algo_nonlin' for this, which indicates what part of the model it's referring to? Maybe VPsolver
