### ISSUE TITLE
Rename "master" as "main".

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#584]
This is a recent trend on github.com to use a more inclusive term for the main development branch and because the name "master" can be considered offensive to some.

**Comment by apcraig** [comment]
github has been moving this way for a year,

   https://www.bbc.com/news/technology-53050955
   https://github.com/github/renaming

and they seem to be taking care of some of the issues under the covers.  It seems like they're building in some backward compatibility, but we'll still probably need to move master to main and delete main manually, but I think it's clear how to do that,

  https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

with many other sites confirming this process.  It seems many projects are making the change.  Main is the new default and I think we should use that naming convention as well.

I agree we should move forward.  I will try to do a bit more research and testing then we should pick a day to make the switch.  We may need to provide some documentation about how to update forks as well.  If anyone has done this already and wants to share their process, that's great too.

**Comment by apcraig** [comment]
This was done on Oct 3, 2021.  An email was sent thru the CICE DevTeam to announce the change.  I will close this now and we'll address any issues as they arise.
