### ISSUE TITLE
CESM ocean forcing - hmix division by zero

### ISSUE THREAD

**Issue by TillRasmussen** [CICE-Consortium/CICE#585]
In icepack_ocean.F90 line 103.
   sst = sst + dt * ( &
            (fsens_ocn + flat_ocn + flwout_ocn + flw + swabs) * (c1-aice) &
          + fhocn + fswthru)         &  ! these are *aice
          / (cprho*hmix)
hmix is zero when using standard ocean forcing (CESM) in standalone simulation.
This is initialized beginning line 4394 in ice_forcing.F90
Below is a hard coded fix (hmix=c20) instead of the value from the forcing file.
        do j = 1, ny_block
          do i = 1, nx_block
            if (n == 2) sss    (i,j,:) = c0
            if (n == 3) hmix   (i,j,:) = c0
            if (n == 4) uocn   (i,j,:) = c0
            if (n == 5) vocn   (i,j,:) = c0
            if (n == 6) ss_tltx(i,j,:) = c0
            if (n == 7) ss_tlty(i,j,:) = c0
            if (n == 8) qdp    (i,j,:) = c0
            do iblk = 1, nblocks
              if (hm(i,j,iblk) == c1) then
                if (n == 2) sss    (i,j,iblk) = work1(i,j,iblk)
                if (n == 3) hmix   (i,j,iblk) = c20  !!work1(i,j,iblk)
                if (n == 4) uocn   (i,j,iblk) = work1(i,j,iblk)
                if (n == 5) vocn   (i,j,iblk) = work1(i,j,iblk)
                if (n == 6) ss_tltx(i,j,iblk) = work1(i,j,iblk)
                if (n == 7) ss_tlty(i,j,iblk) = work1(i,j,iblk)
                if (n == 8) qdp    (i,j,iblk) = work1(i,j,iblk)
              endif
            enddo
          enddo
        enddo
      enddo

**Comment by dabail10** [comment]
Good catch. I will work on a fix. It should be a max(c20,work1(i,j,iblk)).
