### ISSUE TITLE
Fix input data wiki and zenodo entries

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#592]
The metadata for forcing input data on zenodo needs to be made consistent. 

We need to decide on a convention for linking related datasets.  Consider 

- linking individual grid/IC entries with particular forcing data sets
- connecting later entries with the original series DOI (particularly gx3 grid/IC, gx1 grid/IC)
- linking forcing files by year to the original single-file entries.

Check whether we can unlink (hide) buggy datasets.  If not, then provide information about that in the description field.

Convention for original data sets: 

- The dataset preparation date is in the entry name, e.g. 2020.03.20.
- Author = CICE Consortium

File name | okay/fix | DOI and download link | compatible code versions | date added(+)/ deprecated(-) | what to fix |
----|:---:|:---:|:---:|:---:|:---:|
|**gx3 Datasets**| | | | | |
| CICE gx3 grid and initial condition files | fix | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4660174.svg)](https://doi.org/10.5281/zenodo.4660174) | CICE6.1.1+ | +04/2021 | 3/2020 DOI 3728358 (series 3728357); check author; link to zenodo CICE community |
| CICE gx3 JRA55 forcing files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3728364.svg)](https://doi.org/10.5281/zenodo.3728364) | CICE6.0.2+ | +10/2019 | |
| CICE gx3 WW3 forcing files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3728360.svg)](https://doi.org/10.5281/zenodo.3728360) | CICE6.1.0+ | +12/2019 |  |
| CICE gx3 NCAR_bulk forcing files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3728362.svg)](https://doi.org/10.5281/zenodo.3728362) | All | |  |
|**gx1 Datasets**| | | | |
| CICE gx1 grid and initial condition files | fix | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4660164.svg)](https://doi.org/10.5281/zenodo.4660164) | CICE6.1.1+ | +04/2021 | fix date in title; 3/2020 DOI 3728583 (series 3728582); intermediate DOI 4623715 (series 4623714); check author; link in table is wrong |
| CICE gx1 JRA55 forcing files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3731014.svg)](https://doi.org/10.5281/zenodo.3731014) | CICE6.1.1+ | +3/2020 |  |
| CICE gx1 JRA55 forcing files by year | fix | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4601646.svg)](https://doi.org/10.5281/zenodo.4601646) | CICE6.1.1+ | +3/2020 | add file creation date to entry title; check author |
| CICE gx1 WOA forcing files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3728600.svg)](https://doi.org/10.5281/zenodo.3728600) | All | |  |
| CICE gx1 COREII forcing files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3731012.svg)](https://doi.org/10.5281/zenodo.3731012) | All | |  |
| CESM slab ocean forcing | fix | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4660188.svg)](https://doi.org/10.5281/zenodo.4660188) | CICE6.1+ | +04/2021 |  orig DOI 4633898 (series 4633897); add file creation date to entry; check author |
|**tx1 Datasets**| | | | |
| CICE tx1 grid files | okay | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3728356.svg)](https://doi.org/10.5281/zenodo.3728356) | CICE6.0.2+ | +9/2019 |  |
| CICE tx1 JRA55 forcing files | fix | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3822650.svg)](https://doi.org/10.5281/zenodo.3822650) | CICE6.1.1+ | +5/2020 | link in table is wrong |
| CICE tx1 JRA55 forcing files by year| fix | [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4495069.svg)](https://doi.org/10.5281/zenodo.4495069) | CICE6.1.1+ | +5/2020 | DOI 4495070 (series 4495069); link to zenodo CICE community; link in table is wrong |

**Comment by eclare108213** [comment]
I've listed the earlier DOIs for linking purposes.  If a dataset isn't backward compatible, then perhaps it shouldn't be linked too far back?  I'm not entirely sure what happens if you try to link zenodo entries that weren't originally linked, e.g. using 'is related to' types of options vs being part of a series.

**Comment by dabail10** [comment]
Ok. I believe I have fixed everything on Zenodo and linked appropriately from the Wiki table. Please let me know if you find problems. I ended up leaving the SOM forcing file with two versions and added some explanation.

**Comment by eclare108213** [comment]
I made a few corrections to the links on the wiki - it all looks good now.  Thank you for getting on top of this!
