### ISSUE TITLE
bug in gather_global_ext in ice_gather_scatter.F90

### ISSUE THREAD

**Issue by TillRasmussen** [CICE-Consortium/CICE#595]
@phil-blain @apcraig @dabail10 
In ice_gather_scatter.F90 there is an interface gather_global_ext,.
This gathers data from all blocks and fills the interior first. After this it fills out the ghost cells to the east, west, south or north.
This is done when of of the below conditions are fulfilled
this_block%iblock == 1, this_block%iblock == 1, this_block%jblock == nblocks_y, this_block%iblock == nblocks_x
The corners are filled when two of the above conditions are fulfilled. E.g 
this_block%iblock == 1 and this_block%iblock == 1 will fill the south western corner of the ghost cells.
If this block is masked out nothing will be done and the value will be whatever the compiler chooses. 
This happens in test freya_gnu_smoke_gx3_16x2x1x1x800_debug_droundrobin_run2day where each block has a size of 1x1

The 1d evp solver requires a global gather in order to run parts on the master task.
With the gnu compiler I forced an initialization to NAN, which for the velocities caused an initialization to NAN. This spreads out to the rest of the array during the iterations and fails when it is used to calculate indexes in the transport routine.
I found two solutions. I have tested number 1

1/  initialize the global array to the special value.
I replaced 
   if (present(spc_val)) then
      special_value = spc_val
   else
      special_value = spval_dbl
   endif

with

  if (present(spc_val)) then
      special_value = spc_val
   else
      special_value = spval_dbl
   endif
ARRAY_G=special_value._
 
2/ This is not tested but in the same function there is a cpp flag CICE_IN_NEMO
I think that the code in here will fix the issue as well as it handles masked cells the same way as unmasked cells.

Questions
Do you prefer solution 1 or 2 (if 2 works)
@phil-blain Are you using this code in nemo_cice. I cannot see any references to it in the rest of the code nor in the NEMO4 code.What I want to is to delete this if we aim for solution 1. If it is solution 2 I would remove the cpp flag

**Comment by phil-blain** [comment]
Apart from the multiple calls in **`ice_dyn_evp_1d`**, all calls to `gather_global_ext` are in subroutines that are only called if `restart_ext = .true.` in the namelist. I think none of our configurations use this setting, but I'll confirm with people that know more about this.

**Comment by daveh150** [comment]
Will this issue affect regional CICE runs? We have been seeing what appears to be either zero velocity or uninitialized/ignored umask on the north and east boundaries of regional setups. I wrote a routine to specifically apply ice velocity to the halo cells but am not 100% sure the code reads these values, or computes dynamics on the halos. 

 

I’ll try to put together some slides and maybe an idealized test to show the group.

 

Thanks,

David

**Comment by TillRasmussen** [comment]
The interior of the global domain is not affected.
The boundary/halo is

It will affect all runs that have masked blocks on the boundary of the domain. The normal blocks fill the boundary/halo zone whereas the masked blocks don't.
This means that all blocks that have masked blocks in this_block%iblock == 1, this_block%iblock == 1, this_block%jblock == nblocks_y, this_block%iblock == nblocks_x will be affected as the values on the boundary/halo is set to the choice of the compiler or it is uninitialized.

At least the evp solver tmask extents into the halo on the northern and the eastern boundary.

Option 1 initialize all and overwrites with values from normal blocks
Option 2 (removing the cpp flag) will do the same thing with if statements as it is done for the normal blocks. At least as I read it.

**Comment by eclare108213** [comment]
Option 1 seems a lot more elegant than option 2.  There seem to be 3 different applications that this might affect:  1) @TillRasmussen's tests, 2) @apcraig's tests, and 3) @daveh150's regional configuration.  @apcraig and @daveh150, could you try the Option 1 modification (it's just adding 1 line of code, I think, but possibly in multiple subroutines), and see if it fixes your issues?  Fingers crossed!  

If this works for MPI, then we'll need to check the serial code to see if it's needed there too.  

Thank you @TillRasmussen !

**Comment by TillRasmussen** [comment]
I think that the serial case would work both with and without the changes and have identical results. There are no masked blocks.
The interface includes 3 subroutines. Each one of them need the line.

**Comment by apcraig** [comment]
I ran the 1x1 block size test case, cheyenne_intel_smoke_gx3_16x1x1x1x800_droundrobin, with and without option 1 code changes and the results are bit-for-bit identical.  Basically, I added

`   ARRAY_G = special_value
`

in 4 places in cicecore/cicedynB/infrastructure/comm/mpi/ice_gather_scatter.F90.  Was this correct?  I assume if the answers don't change, it isn't addressing whatever problems we have in the 1x1 case.   Have I tested this correctly?

Separately, I will setup some test cases for the 1x1 block size with serial implementations and see what happens.  More soon.

**Comment by apcraig** [comment]
I ran the following test suite on cheyenne with the following results.  All tests run to completion.  What we are looking for is what is bit-for-bit and what isn't.  To keep thing simple, all tests have OpenMP turned off.  There are 5 tests and I ran those 5 tests twice, once with debug off then on.  The results are as follows

> 11. PASS cheyenne_intel_smoke_gx3_8x1x25x29x2_diag1_droundrobin_run1day test 
> 12. FAIL cheyenne_intel_smoke_gx3_16x1x1x1x500_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_8x1x25x29x2_diag1_droundrobin_run1day different-data
> 13. PASS cheyenne_intel_smoke_gx3_1x1x25x29x16_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_8x1x25x29x2_diag1_droundrobin_run1day
> 14. FAIL cheyenne_intel_smoke_gx3_1x1x1x1x8000_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_8x1x25x29x2_diag1_droundrobin_run1day different-data
> 15. FAIL cheyenne_intel_smoke_gx3_4x1x1x1x2000_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_16x1x1x1x500_diag1_droundrobin_run1day different-data


> 21. PASS cheyenne_intel_smoke_gx3_8x1x25x29x2_debug_diag1_droundrobin_run1day test 
> 22. FAIL cheyenne_intel_smoke_gx3_16x1x1x1x500_debug_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_8x1x25x29x2_debug_diag1_droundrobin_run1day different-data
> 23. PASS cheyenne_intel_smoke_gx3_1x1x25x29x16_debug_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_8x1x25x29x2_debug_diag1_droundrobin_run1day
> 24. FAIL cheyenne_intel_smoke_gx3_1x1x1x1x8000_debug_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_8x1x25x29x2_debug_diag1_droundrobin_run1day different-data
> 25. PASS cheyenne_intel_smoke_gx3_4x1x1x1x2000_debug_diag1_droundrobin_run1day bfbcomp cheyenne_intel_smoke_gx3_16x1x1x1x500_debug_diag1_droundrobin_run1day


I have numbered the tests so I can more easily describe them.  Tests are labeled 1[1-5] (debug off) and 2[1-5] (debug on).  Tests 11 and 21 are the baseline cases and are running MPI with a 25x29 block size.  Test 12 and 22 use mpi with 1x1 blocks.  Test 13 and 23 use serial with 25x29 blocks.  Test 14 and 24 use serial with 1x1 blocks.  Test 15 and 25 use mpi with 1x1 blocks but with a different mpi count vs test 13 and 23.  These are my conclusions

- MPI and serial produce bit-for-bit results for regular size blocks (25x29 in this case).
- The 1x1 block size cases are not bit-for-bit
   - 1x1 MPI or serial is not bit-for-bit vs 25x29 (12 vs 11), (14 vs 13), (22 vs 21) and (24 vs 23)
   - 1x1 MPI vs 1x1 serial (14 vs 12) and (24 vs 22).  This difference is not explicitly shown but I manually diffed the files, they are not bit-for-bit.
   - 1x1 MPI with 4 tasks and 1x1 MPI on 16 tasks (15 vs 13) except when DEBUG is on (25 vs 23)
- The 1x1 results are reproducible.  I ran case 12 twice and got bit-for-bit results, so the 1x1 results are not just producing random results, they are reproducible.

So I understand there are a lot of results here, but 

- The problems with 1x1 are not simply in MPI.  Serial also has the same issues.  That suggest this goes beyond the halo (maybe).
- 1x1 does not get the same answers with different pe counts/decomps (this is one place we could focus some initial debug effort).
- Reducing compiler optimization with 1x1 blocks fixes something

It's hard to know how much overlap there is with the issues in evp1d and 1x1 blocks.  There may be some, but it's not clear.

**Comment by apcraig** [comment]
Just a quick followup.  I ran the above 10-test suite with 2x2 and 3x3 blocks.  The 2x2 cases fails the same as 1x1 except 15 is bit-for-bit with 13 is 2x2 but not 1x1.  The 3x3 cases all pass are are all bit-for-bit.  So 2x2 has most of the same problems as 1x1 while 3x3 is fine.

**Comment by eclare108213** [comment]
Is this problem limited to roundrobin or more general?  My experience on badger (intel) is that the roundrobin tests sometimes fail for no apparent reason, intermittently, with the standard block size.  The other decompositions seem to be fine.

**Comment by apcraig** [comment]
I don't think the roundrobin plays a role, but I can run some additional checks.

**Comment by TillRasmussen** [comment]
> I ran the 1x1 block size test case, cheyenne_intel_smoke_gx3_16x1x1x1x800_droundrobin, with and without option 1 code changes and the results are bit-for-bit identical. Basically, I added
> 
> ` ARRAY_G = special_value`
> 
> in 4 places in cicecore/cicedynB/infrastructure/comm/mpi/ice_gather_scatter.F90. Was this correct? I assume if the answers don't change, it isn't addressing whatever problems we have in the 1x1 case. Have I tested this correctly?
> 
> Separately, I will setup some test cases for the 1x1 block size with serial implementations and see what happens. More soon.

I added ARRAY_G = special_value. 3 places in ta gather_global_ext interface.
Remember the solution is only affected when using either ice_dyn_evp_1d or ice_read_write.F90. All calls to ice_read_write.F90 have spec_val = c0. And if it is only used with netcdf if is required that restart_ext is true. Therefore it is likely that the compiler initialize to this value unless you force it to initialize to NaN. This was the way I found the bug.

**Comment by eclare108213** [comment]
@apcraig @TillRasmussen 
Is it worth debugging one/some of these 1x1 block configurations to understand what it happening, or just fix it with
`ARRAY_G = special_value` in ice_gather_scatter.F90 as described above (both MPI and serial)?

**Comment by apcraig** [comment]
Just a quick followup.  I think I've sorted out the issues with the 1x1 and 2x2 blocks now.  It did not have anything to do with the global_gather_ext.  I hope to create a PR soon.  It seems to be related to a subtle bug in land block elimination at the equator.  It turns out the 1x1 and 2x2 blocks were probably always bit-for-bit (as they should be), but that the test results could not tell because of a difference in land block elimination at the equator (where no ice forms).  The log files were not bit-for-bit because we have "non bfb" global sums by default.  If you turn on the ddpdd bfbflag, then the log files are bit-for-bit even without the land mask fix.

Getting back to the global_gather_ext.  I understand that it may be bad to have uninitialized data, but I don't understand how these uninitialized eliminated blocks spread into the rest of the solution.  Why did the model fail when initialized with NANs but work fine when initialized with special_values or uninitialized.  If the uninitialized values do spread to the solution, then we would see irreproducibility, but we don't.  Is this just a technicality in the sense that the NANs lead to a debug float overflow trap?

If we set ARRAY_G = special_value at the start, then it seems like we can get rid of all the code that sets ARRAY_G to special value later on (in the "else if (src_dist%blockLocation(n) == 0) then" block).  I think that's a benefit assuming it works fine.  I will do some testing.  @TillRasmussen, do you agree?
