### ISSUE TITLE
'decomp' test is not re-runnable

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#601]
I've noticed the 'decomp' test in the base suite does not work well if the suite is submitted more than once, i.e. 
~~~bash
./cice.setup --suite base_suite ...
# wait for all tests to finish
cd $suite_dir
./suite.submit
~~~

I haven't investigated further but I suspect it's something to do with the shell globbing in the test script. When the test is re-run I get a weird arboresence in the run directory where the `restart` folder is re-created inside each already existing `restart.$decomp` folder...

It's not too important but I thought I'd mention it anyway...

@apcraig

**Comment by phil-blain** [comment]
I forgot I had already mentioned that here: https://github.com/CICE-Consortium/CICE/issues/524#issuecomment-714701319

**Comment by phil-blain** [comment]
I tried simply `cd`-ing to the run directory, removing `restart*`  directories (and `history`, just to be sure) and it does the trick. So presumably a simple addition at the end of the test script like the following would be sufficient:
~~~diff
diff --git i/configuration/scripts/tests/test_decomp.script w/configuration/scripts/tests/test_decomp.script
index 40b84d0..a08629b 100644
--- i/configuration/scripts/tests/test_decomp.script
+++ w/configuration/scripts/tests/test_decomp.script
@@ -129,6 +129,7 @@ foreach decomp (${decomps})
 end
 
 cp ice_in.0 ice_in
+rm -rf ${ICE_RUNDIR}/restart*
 #-----------------------------------------------------------
 
 # turn off general test features, these are done above for this test
~~~

**Comment by apcraig** [comment]
Just a quick note that the rm seemed to work, but it was added at the top of the script instead of the bottom.  We don't want to remove the restart files before the "generate" step is done because then we lose regression testing.  If we put it at the top of the script, it deletes old restarts before a re-run rather than after a run is complete.  Thanks @phil-blain for coming up a solution.
