### ISSUE TITLE
Smoke test should abort early if the run fails

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#608]
The `smoke` test does not exit with failure when the CICE run fails, it simply write the `FAIL` result to the `test_output` file:
https://github.com/CICE-Consortium/CICE/blob/1c6c225ec6bd0635025d9aef969a1c25f5c74204/configuration/scripts/tests/test_smoke.script#L6-L7
[...]
https://github.com/CICE-Consortium/CICE/blob/1c6c225ec6bd0635025d9aef969a1c25f5c74204/configuration/scripts/tests/test_smoke.script#L23-L29

In contrast, the `restart` test does `exit 99`:
https://github.com/CICE-Consortium/CICE/blob/1c6c225ec6bd0635025d9aef969a1c25f5c74204/configuration/scripts/tests/test_restart.script#L10-L22

This makes more sense in my opinion. If the initial run fails it makes no sense to go on and try to do the baseline generation, baseline comparing and BFB compare step, no ?

This can lead to misleading "missing data" results when in fact it is the data for the current test that is missing (because the run failed) and not the data for the run which we are comparing against.

**Comment by apcraig** [comment]
Thanks for catching this @phil-blain.  What you propose makes sense.  I can include this fix in my next PR unless you create a PR first.

**Comment by phil-blain** [comment]
You can go ahead. Might be worth it to check the other tests at the same time. From quick look the  `decomp`, `logbfb` and `unittest` tests have the same behaviour.
