### ISSUE TITLE
Re-running selected cases in suites

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#609]
Is there a script option to re-submit only the failed tests in a suite, without having to redo the entire suite?  That would be super handy.  E.g. base_suite currently has 328 tests and takes a long time to get through the queue; 74 of the tests are failing in my current development sandbox and I'm wondering how many of them will start working when I fix something.

**Comment by apcraig** [comment]
Let me look into it.  We already have the capability to create and/or build and/or submit the tests separately.  It seems like we might be able to create another script that took the test suite results and then generated a new script that would rebuild and resubmit the failed runs.  One issue is that we reuse binaries to save build time, so we'd have to make sure we address that issue.

A couple other ideas might be to parse the test suite output and generate a list of tests that failed.  That could then be passed into cice.setup cleanly for a whole new test suite.  I don't think that would take much more time than rebuilding and resubmitting existing tests.

The test suite continues to grow, I guess that's the point and is good.  I know you're running the full suite, but if it makes sense to consolidate some of the testing or even to break some of the suite apart further, we could.  For instance, we could have a quick, base, and extendedbase suite (in addition to some of the other suites that we already have).  I know that might not be helpful in this case.
