### ISSUE TITLE
CICE input data missing `cice62_gx1_wghtmask`, needed for `decomp_suite`

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#615]
Hi @apcraig,

> - there is a new file for testing the wghtfile decomposition option, CICE_data/grid/gx1/cice62_gx1_wghtmask.nc. This file is on cheyenne and I will move it to a few other testing platforms, but maybe it should be added to the gx1 input files. This file represents the number of months that ice existed at any grid point during the 2005-2009 gx1 production test run and is used to allocate blocks to procs at gx1 with the wghtfile test decomposition. The maximum value is 120 and these values are read and normalized during the decomposition step in CICE.

This should indeed be added to the gx1 input files, since it is used in the `decomp_suite` . I've just ran that suite and the  `daley_intel_restart_gx1_64x1x16x16x10_dwghtfile` test failed because it's missing that file.

_Originally posted by @phil-blain in https://github.com/CICE-Consortium/CICE/issues/602#issuecomment-860818756_

---

I'm opening a separate issue just so we don't forget and keep the discussion focused.

**Comment by apcraig** [comment]
Thanks for adding the issue.   This is known.  This test was added recently to extend coverage of decompositions.  I was waiting for a few new CICE "snow" input datasets and figured we could update the input data version then.  This file has been manually added to a few test platforms, so it's being covered in our weekly testing and it only affects this one specific test.

**Comment by apcraig** [comment]
Also need to add new snicar datasets from snow PR, #621.

**Comment by eclare108213** [comment]
I approved the snow data addition to zenodo.  Is that all that's needed for those?  Need to check that it's listed on the wiki forcing page.

**Comment by dabail10** [comment]
I should have added these to the Wiki page, but let me know if you find something missing. The weight file is just under the gx1 initial condition and grid file area.

**Comment by apcraig** [comment]
I'll close this.  @dabail10, if you can update the wiki pages that would be great.  thanks.
