### ISSUE TITLE
lonu_bounds uninitialized

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#63]
the NAG compiler reports lonu_bounds is uninitialized for iconrner=1, iblk=1, at line 1912 of ice_grid.f90. 
(issue reported by DMI collaborators)

**Comment by dabail10** [comment]
This is will be fixed in a new PR coming soon. Since these are just history variables, we don't use the ghost cells. None-the-less, it is still good to initialize these.

Dave

**Comment by dabail10** [comment]
This is addressed in PR #180.

**Comment by dabail10** [comment]
Resolved in PR #191.
