### ISSUE TITLE
Make implicit solver code more consistent with recent changes to rheology

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#646]
I have made the modifications and just performed the end-to-end testing procedure. 

340 measured results of 340 total results
335 of 340 tests PASSED
0 of 340 tests PENDING
0 of 340 tests MISSING data
5 of 340 tests FAILED

I expected the test with kdyn=3 to FAIL (small roundoff errors) due to reordering the calculations. It does fail. I expected the ones with kdyn=1 or 2 to be BFB. All of them are BFB except for 

COPY daley_intel_smoke_gx3_4x1_debug_icdefault_snwITDrdg_snwgrain build
FAIL daley_intel_smoke_gx3_4x1_debug_icdefault_snwITDrdg_snwgrain run -1 -1 -1
FAIL daley_intel_smoke_gx3_4x1_debug_icdefault_snwITDrdg_snwgrain test

COPY daley_intel_restart_gx3_8x2_icdefault_snwITDrdg_snwgrain build
FAIL daley_intel_restart_gx3_8x2_icdefault_snwITDrdg_snwgrain run
FAIL daley_intel_restart_gx3_8x2_icdefault_snwITDrdg_snwgrain test

**Comment by apcraig** [comment]
Thanks for the clarification @JFLemieux73.  So the ncdiff and the cmp were not done on the same sets of files?  That explains things.  This all seems reasonable to me.

**Comment by JFLemieux73** [comment]
Well actually when I did ncdiff on the restarts, I looked at the volumes and velocities...when these are the same the solution is the same (which is the case). I just didn't look at stressp (diagnotic). So basically cmp and ncdiff give us the same conclusion.
