### ISSUE TITLE
C-grid test suite

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#654]
Use B-grid forcing to begin with, averaging as needed, and eventually (i.e. lower priority) develop a C-grid forcing data set.

The test suite can include
- regression tests for all dynamics and advection options on the B-grid
- unit tests for new infrastructure components
- box configuration(s) with an interesting land mask (single-cell island, single-cell-wide strait, periodic grid with edge intersected by land in various orientations, etc).  This can be used to test boundary conditions using basic operators like averages, and also to test averaging of arrays (including forcing) between B- and C-grids.  CICE’s standard box tests can also be used to compare B- and C-grid discretizations for momentum, stress and advection.
- standard gx3 tests for a more ‘realistic’ development configuration
- standard gx1 tests (including 5-year QC configuration) for ultimate testing

**Comment by eclare108213** [comment]
@daveh150 writes:
what is needed for the forcing items? Or at least what I can contribute? Tony mentioned the unit tests are working, and for the gx1,gx3 cases we have the JRA55 forcing on the T-Grid. Do we need updated box tests that have the interesting land configurations? Rick and I talked about that this morning, is having one grid 10x10 (or something) with a different land mask file something that would work? Or is the intent to have separate forcing routines in addition to ‘box2001’?

**Comment by eclare108213** [comment]
For the forcing, we need to be able to average from the B-grid to the appropriate locations and have infrastructure (e.g. namelist flags) for those choices, and test(s) to check that the forcing is being shifted as expected.  @apcraig is doing this.  

We'll also need various other types of forcing for various box tests.  Some of this is already implemented.  

E.g. Let's check the symmetry of the new discretizations using square boxes with land all the way around, running with forcing purely in the x direction and again with forcing purely in the y direction, and check that the results are BFB with a 90-degree rotation.

I've made a (rough!) sketch of an "interesting" land mask that has potential troublesome cases.  There might be others that should also be drawn in, like diagonal straits with both ends open for through-flow (they are embayments in the drawing).  I'd use one of the standard box sizes.  For forcing, we can use the box2001 standard forcing (averaged to C-grid locations upon initialization, as needed), and also uniform forcing in the x, y and diagonal directions.  So the standard forcing might need to be pulled out into its own subroutine for multiple uses?  The ice initial condition should probably just be a thin slab to begin with, and then we can make it more complicated as needed.  This mask can also be used for checking the values of the new land masks (which will need to be added to the history output @dabail10).

I hope this makes sense!
![Landmask](https://user-images.githubusercontent.com/8173983/140523928-589b5d67-c74d-47a8-aad6-4468f1ff864c.jpeg)

**Comment by eclare108213** [comment]
Another thing to do:  Clearly document the various box test configurations.  This could be in the form of a table, e.g. taken from https://docs.google.com/spreadsheets/d/18t5uPAizY6lxNOuBXt-BCrfg8xI7vZBm4qKFG-g82bQ/edit?usp=sharing (protected - requires permission to access).  This exercise might also reveal how the available test options could be refactored for better versatility.

**Comment by eclare108213** [comment]
We need to add the boxnodyn test to the gridsys test suite.  It is supposed to check that with completely zero forcing there is no ice motion (or maybe we have to look at the output manually?).

**Comment by daveh150** [comment]
I added boxnodyn test for both B and CD grids. The suite passed for boxnodyn. I submitted pull request to Tony's cgridDEV branch.

**Comment by eclare108213** [comment]
Can we close this issue or are there other things that can/should be done?

**Comment by apcraig** [comment]
I think there are still some things to do once the C/CD is working and once the box tests we want are ready.  I suspect we'll continue to update the test suites as development continues but that's addressed in the C-grid project tasks.  I think we can close this.
