### ISSUE TITLE
C-grid output

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#655]
_We will need proper C-grid output early on in the development process, for checking our test results._

**History Files**
The grids supported by history files will need to be expanded.  This is defined in ice_history_shared (i.e. tcstr2D).  ice_history_write will also need to be expanded to write the new grids as well as support the new vcoord values.  Unfortunately, this will need to be done in the binary, netcdf, and pio versions separately and then tested.  

History variables will need to be associated with the appropriate grid and this will probably depend on the grid system for some variables.  

There is likely an opportunity to refactor some of the history implementation to provide greater flexibility for adding fields/grids and improving code reuse, but this may also be a big distraction.  We will take a simpler, direct approach to expand features, for now.  

- [x] Determine scope of history output changes needed
- [X] Define and write new grids, etc
- [x] Associate history variables with the appropriate grid (use grid system namelist flag)
- [x] Review current grid settings for history variables (uatm, vatm), which might be buggy.
- [ ] Review documentation and alter as necessary.

**Diagnostics and budgets**
The current implementation of global sums and other reductions should be directly usable on the N and E grids.  Individual diagnostics need to be reviewed and may require distinct implementations for the B-grid and C-grid as a result of different staggering of quantities.  The grid_system variable can be used to control diagnostic computations that are different.

Diagnostics associated with budget conservation is a larger concern.  As new algorithms are implemented in CICE, diagnostics associated with conservation and the general budget will need to be revised.  It’s strongly recommended that the budget diagnostics be modified as the C-grid solvers are implemented.  The grid_system namelist can be used to trigger different budget diagnostic implementations.

- [x] Determine scope of diagnostic and budget output changes needed
- [ ] Check conservation diagnostics
- [ ] Modify diagnostics as needed (use grid system namelist)
- [ ] Review documentation and alter as necessary.

**Comment by eclare108213** [comment]
Some notes on diagnostics:
- Total kinetic energy of ice+snow is calculated using (uvel, vvel) incorrectly (mass and velocity are not co-located). The T-cell area is used, which is fine.  Velocity should be interpolated to T-cell centers.  _**NOTE:  use vector averages (magnitude and direction) rather than averaging components!**_
- Maximum ice speed assumes uvel and vvel are co-located.  This is okay for the CD grid, but we'll need to take the maximum over all of the N and E edges.
- Likewise, there is a root mean square ice speed diagnostic.
- All other uses of grid cell areas (tarea over the northern and southern hemispheres) are for T-cell-centered variables, including conservation diagnostics.  These should not be affected by the choice of grid, as long as mass and thermodynamic variables are centered in T cells.
- Once forcing begins to arrive on the C-grid, we will need to average some of it (e.g. ocean velocities) to T-cell centers for thermodynamic flux and FSD calculations, but this should not affect the diagnostics unless we add new ones that distinguish among the grids.

Conclusion:  we need to fix the TKE diagnostic for both B- and C-grids, and we need to expand the max(velocity) and RMS(velocity) calculations to all edges.  I don't think there's much else to do for the diagnostics unless we want to add new ones. @apcraig was there something else that you saw, which caused concern?

**Comment by eclare108213** [comment]
@dabail10
Is updating documentation the only thing left to do here, other than testing that the output is correct?

**Comment by dabail10** [comment]
I believe so. I assume we are waiting until we merge with CICE Consortium main here?

**Comment by apcraig** [comment]
I think we should document as we go when it's reasonable.  Some documentation has been updated (like from the initial infrastructure PR), some documentation has been partly updated, some is still to do.  We should do the stuff that is easy and relatively "done".  For stuff that could still change, it could be deferred.  I don't think we should wait until the end to do all the documentation.

**Comment by eclare108213** [comment]
I agree with @apcraig, we should document as we go as much as possible.  It's going to be hard to catch it all, once time has passed and memory fades.  The history documentation is not very detailed now, and so I hope you can document the basic changes without worrying too much about what details might get cleaned up in the code later.

**Comment by dabail10** [comment]
Also, the TKE computation on T cells is still needed.

**Comment by apcraig** [comment]
#784 fixes the KE diagnostics, rms ice speed, and max ice speed.

I briefly reviewed the documentation.  I didn't see anything that needed to be updated in general, but maybe we need to add a section.  Others should review the documentation.  If I can contribute/help with additions or corrections, let me know.

**Comment by eclare108213** [comment]
@dabail10 
Could you review the documentation and output-related tasks identified in this issue, to make sure everything is consistent and figure out what's left to do, if anything?  I'd like to make sure these items are finished before the next release.  Thanks!

**Comment by dabail10** [comment]
Can we take care of #707 with this? I'll have a look at the documentation.

**Comment by dabail10** [comment]
Looking at the documentation I see that we do not provide a full table of namelist variables for icefields_nml. Also, the index of primary variables is not all inclusive. So, I don't think we necessarily need to add anything about C grid specific variables?


https://cice-consortium-cice.readthedocs.io/en/main/user_guide/ug_case_settings.html#tabnamelist

**Comment by dabail10** [comment]
I believe this can be closed.
