### ISSUE TITLE
Spurious 'max ice volume' for South hemisphere causes output conversion error in ice_diagnostics on gbox128

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#669]
I got another output conversion error, this time in CICE. In contrast to https://github.com/CICE-Consortium/Icepack/pull/378, I'm not sure what's the best way to fix this one. It happens for these tests in the base_suite:
- `*_*_restart_gbox128_4x2_boxnodyn_debug_short`
- `*_*_smoke_gbox128_4x4_boxrestore_debug_short`

Here is the backtrace from GDB (same for both):
~~~
(gdb) bt
#0  0x0000152d8b3e637f in raise () from /lib64/libc.so.6
#1  0x0000152d8b3d0e7e in abort () from /lib64/libc.so.6
#2  0x0000000001bf05d0 in for.issue_diagnostic ()
#3  0x0000000001bf61db in for.signal_handler ()
#4  <signal handler called>
#5  0x0000152d8b3e637f in raise () from /lib64/libc.so.6
#6  0x0000152d8b3d0db5 in abort () from /lib64/libc.so.6
#7  0x0000000001bf05d0 in for.issue_diagnostic ()
#8  0x0000000001bef838 in for.io_return ()
#9  0x0000000001c475bf in for_write_seq_fmt_xmit ()
#10 0x0000000000624259 in ice_diagnostics::runtime_diags (dt=3600) at /.../cice3/cicecore/cicedynB/analysis/ice_diagnostics.F90:943
#11 0x000000000041bf0d in cice_runmod::ice_step () at /.../cice3/cicecore/drivers/standalone/cice/CICE_RunMod.F90:378
#12 0x0000000000419d11 in cice_runmod::cice_run () at /.../cice3/cicecore/drivers/standalone/cice/CICE_RunMod.F90:83
#13 0x000000000040de40 in icemodel () at /.../cice3/cicecore/drivers/standalone/cice/CICE.F90:49
(gdb) f 10
#10 0x0000000000624259 in ice_diagnostics::runtime_diags (dt=3600) at /.../cice3/cicecore/cicedynB/analysis/ice_diagnostics.F90:943
943             write(nu_diag,900) 'max ice volume     (m) = ',hmaxn,  hmaxs
(gdb) p hmaxn
$1 = 1.9962409428228371
(gdb) p hmaxs 
$2 = -1.7976931348623157e+308
~~~

`hmaxs` comes from this global max earlier in `runtime_diags`:

https://github.com/CICE-Consortium/CICE/blob/2b851261b59a9fae63a96b4e52aea3b96a0ec5d9/cicecore/cicedynB/analysis/ice_diagnostics.F90#L372-L374

So I'm not sure how we get this spurious  -1.7976931348623157e+308 for the South hemisphere... maybe `lmask_s` is not correct for box128 ? because `vice` itself seems to be correctly zero-initialized on the whole grid:

https://github.com/CICE-Consortium/CICE/blob/2b851261b59a9fae63a96b4e52aea3b96a0ec5d9/cicecore/cicedynB/general/ice_init.F90#L2352-L2359

I did not have time to dig further...

**Comment by eclare108213** [comment]
This issue was addressed in apcraig/CICE#57
