### ISSUE TITLE
Adding options (`cice.setup -s`) for amount of memory needed

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#674]
I'm porting CICE to our new machines and I'm running into a new situation. On some machines, nodes are shared (jobs do not have exclusive use of a node) and because of that we need to reserve _some_ amount of memory in our job request, or else the job crashes.

I set 5 GB as a first try and most of the base_suite passed, but some tests need higher amounts of memory, up to 20 GB.

I could just ask for 20 GB in cice.batch.csh for all jobs on that machine, but it would be a smarter use of resources if we had options for the amount of memory needed, just as we have for the walltime (`-s short,medium,long`). This way we could add these options to the base suite definition file, and it would only affect machines which choose to ask for a specific amount of memory in cice.batch.csh.

I hope this is  clear enough...

/cc @apcraig

**Comment by apcraig** [comment]
@phil-blain, that makes sense.  This should not be difficult to do.  Thanks.
