### ISSUE TITLE
C-CD TEST: 1 grid cell wide channel

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#687]

**Comment by JFLemieux73** [comment]
Here is the pdf document for the one grid cell wide channel analytical solutions. 

[1cell_channel.pdf](https://github.com/CICE-Consortium/CICE/files/8092534/1cell_channel.pdf)

**Comment by dabail10** [comment]
./cice.setup --case boxchan --mach cheyenne --env intel -s gridcd,debug,boxchan --grid gbox12

**Comment by JFLemieux73** [comment]
Merci Dave! Here is my python code for calculating the analytical solution (the parameters might not be exactly the same than in the test case).

**Comment by JFLemieux73** [comment]
# -*- coding: utf-8 -*-
#!/usr/bin/env python

import numpy as np
import math

#---- input ----

rhoa=1.2
rhow=1026.0
Cda=1.2e-3
Cdw=5.5e-3
a=1.0
h=1.0
Pstar=2.75e4
Cstar=20.0
Dmin=2e-9
er=2.0
Dy=20000

ratio=rhoa*Cda/(rhow*Cdw)
ratioinv=1.0/ratio
P=Pstar*h*math.exp(-1.0*Cstar*(1.0-a))

uastar=math.sqrt(ratioinv*(0.5*er*Dmin*Dy)**2 + P/(a*rhoa*Cda*er*Dy))

print('Plastic regime: wind needs to be larger than')
print(uastar)

ua=2.0*uastar
uplast=math.sqrt(ratio*(ua**2)-P/(a*rhow*Cdw*er*Dy))
print('Plastic regime: ua=2uastar, u=')
print(uplast)

ufreedrift=math.sqrt(rhoa*Cda*(ua**2)/(rhow*Cdw))
print('The freedrift velocity is in this case:')
print(ufreedrift)

ua=0.5*uastar
uvisc=-P/(a*rhow*Cdw*(er**2)*(Dy**2)*Dmin) + math.sqrt((P/(a*rhow*Cdw*(er**2)*(Dy**2)*Dmin))**2 + ratio*(ua**2))
print('Viscous regime: ua=0.5uastar, u=')
print(uvisc)

ufreedrift=math.sqrt(rhoa*Cda*(ua**2)/(rhow*Cdw))
print('The freedrift velocity is in this case:')
print(ufreedrift)

**Comment by dabail10** [comment]
Excellent. I am having troubles getting the channel to run. The block/pe layout is not working. There are only 12 active cells, so I assume the problem is with land block elimination.

**Comment by dabail10** [comment]
This layout works:

    nprocs = 12
    nx_global         = 12
    ny_global         = 12
    block_size_x      = 12
    block_size_y      = 1
    max_blocks        = 1

for the gbox12.

**Comment by dabail10** [comment]
Sorry, this is the standard channel. I need to figure out the 1 grid point wide channel.

**Comment by dabail10** [comment]
Ok. I have something coded up for this. It is not submitted as a PR yet as there are some subtle aspects. However, the solution after 5 days in the one-grid point wide channel is 0.0841281 m/s everywhere. The ice area is 0.5. I am playing around with the code you have. I don't think the parameters in your code are quite what we have in this case. However, if I manually set Pstar to 0 and uastar to 2.5, hence ua = 5.0 it gets pretty close. However, we are setting Pstar to the 27500 value ... so I am confused.

**Comment by JFLemieux73** [comment]
It looks like some multiplication (*) got lost when I copied the code. I will send it to you by email. Dave we could have a zoom tomorrow to discuss about this if you want.

**Comment by dabail10** [comment]
Yeah, it is github formatting. The asterix characters are still there. If you edit the comment you will see them. I was able to get the code by editing the comment. One is supposed to be able to enclose the code in back quotes (`` ``) to get what you want, but it is not working for me.

**Comment by dabail10** [comment]
We can chat about it if you would like. I'm free all day except from 12-1pm EST.

**Comment by dabail10** [comment]
I think I see the differences. We can still talk about it.

In your code, cda = 1.2e-3. However, in CICE this is computed in icepack_atmo.F90. Initially it is (vonkar/log(zref/iceruf))^2. This is a bit bigger at 1.25e-3. Note that zlvl = zref = 10m, so the rd coefficient is the same as rdn. Cdw in the code is actually 5.36e-3. In the channel case, the wind (ua) is 5 m/s. Also, in the channelone case, aice=0.5 and h = 1. However, is h actually vice here? Or, should it be h/aice? Anyhow, I played around with the values a bit and the freedrift velocity in the python code is around 0.098. Still a bit higher than 0.084.

**Comment by dabail10** [comment]
@JFLemieux73 and I talked about this and feel that we should not bother supporting this one-gridpoint wide channel in the standard code. We believe the 2001 test case from Elizabeth's paper is probably good enough. I will keep testing the one gridpoint case that I have and compare against the numbers from the python code analytical solution.

**Comment by dabail10** [comment]
So, we went through the parameters and set them exactly as in the code. So, the box channel case with a=0.5 and h=1, gives us the plastic solution of 0.0841 precisely both in the model and the python code. I added stress12U to the history file and I get -0.312125 and the analytical solution is exactly the same. Now stressmU is zero, but stresspU is -1.2485. Is this right? I thought that stresspU and stressmU should both be zero?

**Comment by dabail10** [comment]
stresspU = zetax2U*divU - rep_prsU

= (P/Delta)*(du/dx) - P

So, stresspU = -P in this case? This agrees with -P in both the python code and the channel run.

If I bump aice up to 0.8 we get:

stresspU = -P = -805.888
stress12U = -201.47
uplas = 0.036979
ufree = 0.0842

The code gives exactly the same answers.

**Comment by JFLemieux73** [comment]
Dave I agree with you that stresspU should not be zero and equal to -P. Are you using a different h than 1m to get 805.888? I would expect stresspU=-503.68 with aice=0.8 and h=1m.

**Comment by dabail10** [comment]
Yes, sorry. I set h to 1.6. (2*aice).

**Comment by JFLemieux73** [comment]
Results are consistent with analytical solution.
