### ISSUE TITLE
C-CD TEST: kmtislands

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#688]

**Comment by dabail10** [comment]
./cice.setup -c kmtislands -m cheyenne -e intel -s gridcd,debug,boxsyme -g gbox80

This is to create a kmtislands case. However, one also has to set:

kmt_type = 'boxislands'

in ice_in. Then I had to modify the code to use 0.5 concentration instead of one. One could do 0.8 here as well.

diff --git a/cicecore/cicedynB/general/ice_init.F90 b/cicecore/cicedynB/general/ice_init.F90
index c3e8c58..99b1416 100644
--- a/cicecore/cicedynB/general/ice_init.F90
+++ b/cicecore/cicedynB/general/ice_init.F90
@@ -2760,7 +2760,7 @@ subroutine set_state_var (nx_block, ny_block, &
                sum = sum + ainit(n)
             enddo
             do n = 1, ncat
-               ainit(n) = ainit(n) / (sum + puny/ncat) ! normalize
+               ainit(n) = p5 * ainit(n) / (sum + puny/ncat) ! normalize
             enddo

**Comment by apcraig** [comment]
I think we should close this.  Anyone disagree?

**Comment by eclare108213** [comment]
Since the namelist choices have changed, I'll close this one.
