### ISSUE TITLE
C-CD TEST: boxwallblockp5 noise

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#689]
From #682 

 ./cice.setup --test smoke -m cheyenne -e intel -g gbox80 -p 16x1 -s boxwallblockp5,diag1,gridcd --testid cG03

in ice_in, set

```
    npt_unit       = 'd'
    npt            = 100
    histfreq       = 'd','x','x','x','x'
    hist_avg       = .false.
    ktransport      = 1
    distribution_type = 'roundrobin'
```

-boxwallblockp5 (an aice=0.5 box on the east wall with east forcing) with advection after 3 months is as follows.  This case has noise in both the C and CD cases.  The block is being push against the wall and spreading.  

![hi_block_3mon_B](https://user-images.githubusercontent.com/8182814/153687776-9f2c3d38-0783-4e09-bf9a-592ff666d65e.gif)
![hi_block_3mon_C](https://user-images.githubusercontent.com/8182814/153687778-d929782a-a459-4589-9f96-ee1ca33284c5.gif)
![hi_block_3mon_CD](https://user-images.githubusercontent.com/8182814/153687779-4ead7032-eb90-491f-b7c8-3acd7c2bbf89.gif)

**Comment by apcraig** [comment]
Changing the timestep of these test cases to 900s (from 3600s).  Results look largely the same.

![hi_B_ts900](https://user-images.githubusercontent.com/8182814/154783519-48804173-2510-4c04-89ea-72227b4a3aa6.gif)
![hi_C_ts900](https://user-images.githubusercontent.com/8182814/154783532-74992ebd-db3f-4194-9983-1ef34bd18811.gif)
![hi_CD_ts900](https://user-images.githubusercontent.com/8182814/154783537-983c320a-a0db-46ce-affe-55e78497b57c.gif)

**Comment by dabail10** [comment]
Note there is only boxwall or boxwallp5 here.

Dave

**Comment by dabail10** [comment]
Here is sigP for the three runs. I have set ice_data_type to 'uniformp5'

VP:
![Screen Shot 2022-03-04 at 4 22 42 PM](https://user-images.githubusercontent.com/12142035/156855335-fed8a8c4-bc7a-45e7-8729-6d63ee934605.png)
B-grid
![Screen Shot 2022-03-04 at 4 22 50 PM](https://user-images.githubusercontent.com/12142035/156855341-9830d715-219e-48b0-8fc4-8ac13b7725a3.png)
CD-grid
![Screen Shot 2022-03-04 at 4 22 58 PM](https://user-images.githubusercontent.com/12142035/156855348-9f2cb043-cf64-49a2-b216-12653a81b492.png)

The velocity fields for each look very similar. Very close to 0.0842 on the western side and decreasing to zero on the right.  The B and the C sigP look very similar, but both are quite different from the VP. Going to try the revp for the B and CD.

**Comment by dabail10** [comment]
I am looking at the Bouillion paper and I am not sure which set of parameters I should use. Here is what I think needs to change in the namelist?

    revised_evp     = .true.
    evp_algorithm   = 'standard_2d'
    brlx            = 300.0
    arlx            = 300.0

In his paper he talks about alpha and beta as

Exp1 40, 3000
Exp2 98, 122
Exp3 126,947
Exp4 40, 300

It looks like to me from the ellipse plots that Exp1 and Exp3 are the best?
