### ISSUE TITLE
ice:vertical thermo error appears after assimilation

### ISSUE THREAD

**Issue by duranmm** [CICE-Consortium/CICE#690]
Hi everyone,

I am using the CICE model and I am getting the **ice:vertical thermo error**. This is what is written in the cice_nu_diag file:

>  Starting thermo, zTsn > Tmax
>  zTsn=   158.594491927825
>  Tmax=  0.000000000000000E+000
>  istep1, my_task, i, j:      319681           5           3           2
>  zqsn  0.000000000000000E+000  -110220000.000000        110220000.000000
>  istep1, my_task, iblk =      319681           5           1
>  category n =            1
>  Global block:           6
>  Global i and j:           2         136
>  Lat, Lon:   72.2873226107424       -16.6938509959529
>  aice:  0.579343404620886
>  n:            1 aicen:   5.895479768514633E-002
                                                  

I did a free run with the model, and I didn't encounter this issue. But then I did assimilation, in the assimilation process the model files are modified and when using them again as initial files for my run I get the ice error. I did some post-processing in the post-assimilation files (for ocean and ice), mainly to correct the range of values of certain variables and put to zero certain variables when aicen was equal to 0. However, I keep getting this ice:vertical thermo error which seems to be due to something in the **ice initial file**, but I am a bit lost on what else I could modify.

Does anyone of you have any idea on how to solve this? 

Any advice is welcome! Thank you!

Best regards,

Marina

**Comment by duranmm** [comment]
Hi Jean-Francois,

Thanks a lot for your quick reply and for the information! I will contact him

Best regards,

Marina

**Comment by eclare108213** [comment]
It would be helpful to move this question and discussion to the forum,
https://bb.cgd.ucar.edu/cesm/forums/cice-consortium.146/
so that others in the community can see and participate in the conversation.

**Comment by duranmm** [comment]
Yes, good point! I will open the same question on the forum, I didn't have access before but I can now. I will also write in the forum if I found a solution for it!
