### ISSUE TITLE
C grid boxsym tests: Kimmritz et al. 2016 C1 configuration

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#697]
The Kimmritz et al. C1 config has capping=0, deltaminEVP=2e-9 and visc_coeff_method='avg_zeta'. See table 1 at the end of the following document for details:

https://www.overleaf.com/project/620295ed9e158f02d60771f7.

The only thing missing in the code is the calculation of the square of the shear strain rate at the T point from the square values at the U points (proposed by Bouillon et al.  2013 = B2013). I have made small modifs to our C grid code to have this: my branch is DEVshearUtoT.

**Comment by JFLemieux73** [comment]
Here is the process I use for testing this. 
-produce reference (ref) B-grid implicit (VP) solution with kdyn=3. 
-compare B-grid EVP solution to the ref.
-if B-grid EVP is close to the ref -- produce C-grid EVP and compare to ref
-if B-grid EVP is too noisy -- reduce Pstar and restart the process

**Comment by JFLemieux73** [comment]
Here is the ref for Pstar=2.75e4 (standard value
![B_vp](https://user-images.githubusercontent.com/31927797/157455609-7ee101f4-2a9a-432b-9c6e-3e7fcf35e277.png)
)

**Comment by JFLemieux73** [comment]
The problem is really stiff...the max uvel is 0.00073 m/s. Here is the B-grid EVP solution:
![B_evp](https://user-images.githubusercontent.com/31927797/157455932-2e287265-ab30-4afa-a173-cd4d0e4893d4.png)

**Comment by JFLemieux73** [comment]
The B-grid EVP solution is a bit noisy. Here is the ref solution with Pstar=1e4:
![B_evp_pstar1e4](https://user-images.githubusercontent.com/31927797/157466769-dfa18bd0-15b4-4556-ba06-fc19092f5603.png)

**Comment by JFLemieux73** [comment]
and here is the B-grid EVP solution (again for Pstar=1e4):
![B_evp_pstar1e4](https://user-images.githubusercontent.com/31927797/157467098-696fa370-bb02-470e-b845-4843d60d10a3.png)

**Comment by JFLemieux73** [comment]
Finally the C-grid EVP sol (uvelE) is:
![C_evp_pstar1e4](https://user-images.githubusercontent.com/31927797/157468130-a5038069-d993-429a-ba99-7b9cb664184a.png)

**Comment by JFLemieux73** [comment]
Conclusion: both B and C grid EVP sol are very close to the ref with pstar=1e4 and do not exhibit a lot of noise (at leats in duvu field). I am going to repeat this for the other boxsym tests.

**Comment by eclare108213** [comment]
@JFLemieux73 this looks great!  Maybe increase pstar enough that they start to show some noise, so that we can judge how bad it is?  Are these results with the squared shear calculation or without that?

**Comment by JFLemieux73** [comment]
I have increased Pstar to 1.5e4. Let's look only at divu (range set to -0.1 to 0.1). Here is the ref VP sol:
![div_B_vp_pstar1p5e4](https://user-images.githubusercontent.com/31927797/157484335-c1dfffe1-4473-42a4-87f8-96ae0f3e9e61.png)

**Comment by JFLemieux73** [comment]
Now the B-grid EVP sol:
![div_B_evp_pstar1p5e4](https://user-images.githubusercontent.com/31927797/157484465-b6ffebb1-0e77-41f0-ae5e-4d17e64b7552.png)
 and finally the C-grid EVP sol:
![div_C_evp_pstar1p5e4](https://user-images.githubusercontent.com/31927797/157484544-debbcb99-b38f-47d5-bb31-996828b78d6c.png)

**Comment by JFLemieux73** [comment]
Hum this is interesting...there is less noise in the C-grid EVP than in the B-grid. Let's look for Pstar=2e4.

**Comment by JFLemieux73** [comment]
The range is further decreased (-0.01 to 0.01). Ref VP:
![div_B_vp_pstar2e4](https://user-images.githubusercontent.com/31927797/157488459-170c717b-f613-4a6a-9294-b776ddae3b0b.png)

B-grid EVP:

![div_B_evp_pstar2e4](https://user-images.githubusercontent.com/31927797/157488555-abd20152-e580-48f8-bc79-f0814a0bb8bb.png)

C-grid EVP:
![div_C_evp_pstar2e4](https://user-images.githubusercontent.com/31927797/157488621-933160bd-7bc2-4717-a444-e966ac9233b3.png)

**Comment by JFLemieux73** [comment]
With Pstar=2e4...it is now the C-grid EVP that has more difficulties...I will verify the results for Pstar=1.5e4 (shown above). I have mixed the B and C grid graphs?

**Comment by JFLemieux73** [comment]
Everything is ok. The results for Pstar=1.5e4 are ok.

**Comment by eclare108213** [comment]
You might have discovered something that will make EVP on B-grid work better too.

**Comment by JFLemieux73** [comment]
It looks like there is an issue with the damping of elastic waves and that the B-grid and C-grid implementations behave differently. Keeping Pstar=2e4 I set eyc to 0.18 instead of 0.36. This leads to a damping time scale twice smaller. The B grid EVP sol (divu) is similar to what we have above with 0.36:
![div_B_evp_pstar2e4_eyc0p18](https://user-images.githubusercontent.com/31927797/157497852-f87a5aa1-18ec-420d-a674-e1c6769e159b.png)

while the C grid solution is really improved:
![div_C_evp_pstar2e4_eyc0p18](https://user-images.githubusercontent.com/31927797/157497914-cf27c296-b349-4e98-a41a-99b510e6bafe.png)

**Comment by JFLemieux73** [comment]
Let's look at Pstar=2.75e4 (standard) if we use eyc=0.18.
B grid EVP sol
![div_B_evp_eyc0p18](https://user-images.githubusercontent.com/31927797/157499765-a6a7a976-d8a6-41de-acb1-62e2853b1c17.png)

and the C grid EVP sol:
![div_C_evp_eyc0p18](https://user-images.githubusercontent.com/31927797/157499838-300afeaa-3fbc-42f9-80b3-d2b604c9d082.png)

**Comment by JFLemieux73** [comment]
Let's further decrease eyc...eyc=0.09. I also increase ndte to 2400:

B-grid EVP sol:

![div_B_evp_eyc0p09](https://user-images.githubusercontent.com/31927797/157501525-1ddcdb80-6784-4f34-9452-16fbbdaf3767.png)

C-grid EVP sol:
![div_C_evp_eyc0p09](https://user-images.githubusercontent.com/31927797/157501631-a2da3e64-d180-4467-aceb-ac0d30a4ad38.png)

**Comment by JFLemieux73** [comment]
So it works well for both B and C grid EVP with eyc=0.09 and ndte=2400.

**Comment by JFLemieux73** [comment]
I keep the same settings and want to check symmetry of the C-grid sol. 
atm_data_type = 'uniform_west'

![div_Cw_evp_eyc0p09](https://user-images.githubusercontent.com/31927797/157508104-d7b1c679-b4d6-41b1-95d7-64c69c2fefad.png)

atm_data_type = 'uniform_south'

![div_Cs_evp_eyc0p09](https://user-images.githubusercontent.com/31927797/157508715-72de9a87-ff77-456c-b6c0-c9cf08ec3c73.png)

atm_data_type = 'uniform_north'

![div_Cn_evp_eyc0p09](https://user-images.githubusercontent.com/31927797/157508821-8148c755-fd1e-47c7-9908-2e65e91dd778.png)

**Comment by JFLemieux73** [comment]
Testing this commit: https://github.com/apcraig/CICE/commit/012e21bff8540efd9b3bf95a8535307115bb7bb4

visual comparisons:
results for Pstar=1e4 are same as above

**Comment by JFLemieux73** [comment]
The results are also reproduced for B,C EVP for Pstar=1.5e4, 2e4.
The results are also reproduced for B,C EVP for Pstar=2e4 and eyc=elasticDamp=0.18.
I have not tested the rest but I think it is ok.

**Comment by JFLemieux73** [comment]
Testing this commit: https://github.com/apcraig/CICE/commit/2fb3310e587fa6e4a1ebf2868b17d8489ea22c39

visual comparisons:
results for Pstar=1e4 are same as above for uvel and divu. The VP solution looks good also although I would to verify that the solver behaves as before (see issue #703).

**Comment by JFLemieux73** [comment]
B and C grid results are similar. Results are also consistent whether the wind blows from the south, north, east or west.
