### ISSUE TITLE
C grid boxwallblockp5 tests: Kimmritz et al. 2016 C1 configuration

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#701]

**Comment by JFLemieux73** [comment]
Hi  @apcraig ,

I tried to setup the boxwallblockp5 test case and got this error
./cice.setup: ERROR, /fs/homeu1/eccc/mrd/rpnenv/jfl001/CompGX3/configuration/scripts/options/set_[nml,env].boxwallblockp5 not found

Do you have the set_nml file for this? Thanks!

**Comment by apcraig** [comment]
I don't think there is an option yet to set boxwallblockp5.  What configuration are you trying to setup?

You can try -s blockwallp5 and then set 

ice_data_type  = 'medblocke'

But I think that will be ice thickness of 1.0.  

As I've been saying, we really need to figure out what box configurations we want and then make sure we can set them up.  I also think we need to add namelist so we can separately define the mask, the location of ice, and the thickness of the ice.  Maybe I'll work on that next.  But again, if we can clarify what configurations are useful for testing first, that will help a lot!

**Comment by dabail10** [comment]
./cice.setup -c boxwallp5 -m cheyenne -e intel -s debug,boxwallp5,gridc -g gbox80

This sets atm_data_type to 'uniform_east' and ice_data_type to blockep5. This is a 0.5 concentration block on the east side of the domain. Advection is off here, so you might try ktransport = 1?

**Comment by apcraig** [comment]
Not sure off the top of my head what blockep5 was.  But it should be easier to set now.  You can see the options in the user guide.  p5 and uniform are correct.  The ice_data_type is "eastblock" for a block in the east and "easthalf" for ice in the right half.

**Comment by dabail10** [comment]
The stresspT and stressp_1 are very comparable and have a similar range of -5600 to 0. Now stressmT is quite a bit more negative than stressm_1.

B-grid:

![Screen Shot 2022-04-07 at 9 45 52 AM](https://user-images.githubusercontent.com/12142035/162245499-2e090357-0f46-47f6-9da8-f42f4865e468.png)

C-Grid:

![Screen Shot 2022-04-07 at 9 46 02 AM](https://user-images.githubusercontent.com/12142035/162245540-e6a5686a-52a6-4fc3-9416-5766b1c17fff.png)

**Comment by JFLemieux73** [comment]
Hi Dave,

Do you use the settings to have the Kimmritz C1 config?

I suggest the following:

ndte=1200
elasticDamp = 0.12d0
capping=0
deltaminEVP=2e-9
visc_coeff_method='avg_zeta'

**Comment by dabail10** [comment]
I do not. I will try that.

**Comment by JFLemieux73** [comment]
If you get weird results I suggest also to put very thin/loose ice around the block of ice. As I mentioned before I am not sure our ice edge boundary condition (u=0 when there is no ice) is correct. I think we should have u=ufreedrift.

**Comment by dabail10** [comment]
So, I updated to these settings and ran only one day. The stress12 terms are still different. The B-grid has a symmetry while the C-grid does not. I've set the bounds from -3.13 to 3.13 here. The C-grid does not have the positive blob.

B-grid:
![Screen Shot 2022-04-07 at 11 12 59 AM](https://user-images.githubusercontent.com/12142035/162259624-f2b766f8-0a2d-4306-a49a-aa7c8dacc22b.png)

C-grid:
![Screen Shot 2022-04-07 at 11 13 09 AM](https://user-images.githubusercontent.com/12142035/162259754-595e28ff-d997-477b-bd4a-43e11ee0e38e.png)

**Comment by dabail10** [comment]
So, when I change the C-grid coeff_method to 'avg_strength', then I get the symmetric points as in the B-grid. Not quite as big (-2.8 to 2.8) but much better looking. So, I am harping again on the interpolation method here. Averaging zeta/eta is doing something funky to the stresses.

**Comment by JFLemieux73** [comment]
Thanks Dave. Could you please show the thickness field (after a few days) for both methods (avg_zeta, strength)? Are they symmetric?

**Comment by JFLemieux73** [comment]
Dave,
There is no reason for avg_zeta not to give something symmetric. We use it in the McGill model and we can get perfect symmetry. We have a small bug somewhere. I could help to investigate...I am curious to see what is going on.

jf

**Comment by dabail10** [comment]
I had a great chat with Bill Lipscomb yesterday. One thing he was asking about was the interpolation of Delta. For the C-grid, we compute divT, tensionT at the T points and shearU at the U points. What does this mean for Delta? I remember we would interpolate to get shearT from shearU? Anyhow, I need to look at the code. However, interpolating zeta is effectively interpolating P / Delta. You are right this should work, but I agree that we must have a bug here.

**Comment by JFLemieux73** [comment]
I just ran a similar exp using avg_zeta. I set the initial conc to 0.8 (to have larger stresses). Note that advection and ridging are off for the figure below. Here is sigP after one day:

![sigP_C_avg_zeta](https://user-images.githubusercontent.com/31927797/162470734-d92aee57-380a-44e8-af0c-e2f08de698f1.png)

The other fields (e.g. uvelE, divu) are also symmetric. Why do I get different results that what you got? Note that I run on only one proc (haloupdate issue?). I will test with advection on.

**Comment by apcraig** [comment]
I believe results are bit-for-bit with different decomps and pe counts, but we should confirm.  @JFLemieux73, can you run the same tests on multiple pes and/or multiple blocks?  We check that with many B+evp cases, but not yet automatically with other dycores and C cases.  Lots of tests still need to be added in general.

**Comment by dabail10** [comment]
The thickness is symmetric in my runs. Here is the avg_zeta thickness:

<img width="318" alt="Screen Shot 2022-04-08 at 9 19 11 AM" src="https://user-images.githubusercontent.com/12142035/162472424-4042e1b6-3739-480e-aaa0-6aab9ab2c11f.png">

Here is the avg_strength thickness:

<img width="319" alt="Screen Shot 2022-04-08 at 9 18 17 AM" src="https://user-images.githubusercontent.com/12142035/162472492-1cf5a03e-a38f-40f1-9187-c6814e233eac.png">

In the interior it is one metre. Then it goes to about 1.3 in the yellow and 1.5 against the wall. This is only a two day simulation. I do wonder if there is a halo problem.

**Comment by JFLemieux73** [comment]
If all the fields are symmetric I think stress12 should also be. Is it possible it is only your special code for outputting stress12?

**Comment by dabail10** [comment]
I guess I didn't realize we were still calling strain_rates_U for the C grid. This uses the D grid velocities. So, we get divergU, tensionU, and shearU at the U-points first. Which means Delta is also all at the U point. Then we compute strain_rates_T using shearUsq to get shearT. This gives us Delta at the T point and stressp and stressm at the T point. Then stress12 is at the U point and uses the divergU, tensionU and shearU from the strain_rates_U. The etax2 is interpolated for avg_zeta, otherwise strength is interpolated for avg_strength. I don't see any obvious bugs, but I guess I worry about interpolating P/Delta when Delta is very small at some of the points. This is fine when P is zero, but when P is small and Delta is small ...

**Comment by dabail10** [comment]
It is possible that the history output is wrong, but I suspect not given that it is symmetric with avg_strength.

**Comment by JFLemieux73** [comment]
With avg_zeta there are some unnecessary calculations in strain_rates_U (a legacy of the CD grid...to be improved). Look in the subroutine stressC_U. Only shearU is needed (divergU, tensionU, and DeltaU are not needed).

**Comment by dabail10** [comment]
Right. I was forgetting that aspect. So, one thing I noticed is that the avg_zeta approach is essentially interpolating P / Delta from the T points. Where DeltaT used the shearT interpolated from the shearU. This is kind of double interpolation in the Delta. What if we instead interpolated divT and tensionT to the U points to form DeltaU?

**Comment by JFLemieux73** [comment]
I turned on advection + ridging. The pressure is now larger as the ice piled up at the wall. It is still symmetric:
![sigP_C_avg_zeta_adv](https://user-images.githubusercontent.com/31927797/162477930-e2284ab3-66bd-4138-a481-7c0217eb8647.png)

I will now test a different decomposition.

**Comment by dabail10** [comment]
This might be nice to have divT, tensionT, shearT, and divU/tensionU/shearU to add to the history. Note that I added stresspT, stressmT, and stress12U to the history for the C-grid. I can commit that code if you would like.

**Comment by JFLemieux73** [comment]
Yes it would be nice to have stresspT, stressmT, and stress12U in the outputs. Thanks.

So I setup the same experiment but with -p 8x1 (max_blocks=2). It is BFB with -p 1x1 (max_blocks=1). Dave I will think about your question for DeltaU...I will be back after lunch.

**Comment by dabail10** [comment]
Actually, what is happening in the avg_strength case with DeltaU? It looks like it uses the divU and tensionU from strain_rates_U right?

**Comment by apcraig** [comment]
Just FYI, we do test gx3 C cases for bit-for-bit with different pes/blocks for the out-of-the-box C evp setup.  That is bit-for-bit.  It could some non-standard options (avg_strength, etc) are not bit-for-bit.  We aren't testing all options, but we should start doing that if we can identify exactly what needs to be tested.

**Comment by JFLemieux73** [comment]
Dave, you are right. It uses divU and tensionU from strain_rates_U...another legacy of the CD grid. In their C2 method (equivalent of our avg_strength method), Kimmritz et al. calculate divU**2 from divT**2 values (same idea for tensionU**2). Look at p. 61 in their paper. We don't do that in McGill model (the avg_strength method is similar to what we currently have). 

I would not change that. Kimmritz et al. suggest to use avg_zeta instead. This is also what Martin Losch told me a few weeks ago. I think our avg_zeta method is exactly like in Kimmritz et al. (C1 method).

**Comment by dabail10** [comment]
Sending an email on this.

**Comment by JFLemieux73** [comment]
Dave,

I set a simpler test case with gbox12

./cice.setup -c boxwallblockp8 -m daley -e intel -p 1x1 -s debug,boxwallp5,gridc -g gbox12

ice_data_type   = 'eastblock'
ice_data_conc   = 'c1'
ice_data_dist   = 'uniform'
close_boundaries = .true.

visc_method     = 'avg_zeta'
    elasticDamp     = 0.12d0
    deltaminEVP     = 2e-9
    deltaminVP      = 2e-9
    capping         = 0.

I added prints in the code. I can't reproduce the problem. Everything is symmetric. With this problem, the two ice corners (u points) at the wall are (11,4) and (11,9). After a few subcycles I get stress12U(11,4) = 2485.81706719440 = -stress12U(11,9).

The two values just before the wall are also ok:

stress12U(10,4) = 514.335087628805 = -stress12U(10,9).

**Comment by dabail10** [comment]
Maybe this is a history variable problem. I'll look more.

**Comment by dabail10** [comment]
Sorry. I reran with avg_zeta and it is symmetric. Not sure where I got that earlier. I cannot reproduce it ... sigh. Oh well, nevermind.

**Comment by eclare108213** [comment]
if you increase or decrease the size of your ice block by one grid cell, is it still symmetric?  Likewise if you change the domain size by one grid cell?

**Comment by JFLemieux73** [comment]
Results are symmetric and consistent with what is expected (build up of pressure at the eastern wall).
