### ISSUE TITLE
Add option to have history file timestamp at middle of interval.

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#705]
This was a request from CESM, but also from other CMIP models. Basically it involves averaging the time_bounds values.

**Comment by dabail10** [comment]
I have a similar issue here with the names for the different streams. I see that using h, h1, h2, causes problems for RASM post-processing, but can we add a namelist option that allows us to use h1, h2, etc.?

**Comment by phil-blain** [comment]
> This was a request from CESM, but also from other CMIP models. Basically it involves averaging the time_bounds values.

Hi @dabail10, if I understand correctly this is what was done in https://github.com/CICE-Consortium/CICE/pull/839 right?

and regarding your second comment: 

> I have a similar issue here with the names for the different streams. I see that using h, h1, h2, causes problems for RASM post-processing, but can we add a namelist option that allows us to use h1, h2, etc.? 

This is essentially #854, right ?

So all in all I think this here issue could be closed?

**Comment by dabail10** [comment]
Yes, this can be closed.
