### ISSUE TITLE
Principal stress  calculation does not work for C grid 

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#707]
The problem is that stress12T is used by principal_stress subroutine but it is never calculated (it is zero) for the C grid. 

This affects sig1 and sig2 (as diagnotics). sigP is ok.

**Comment by apcraig** [comment]
I can help fix this.  Can anyone provide guidance?

**Comment by apcraig** [comment]
On the C grid, it looks like we compute stress12U.  I assume that's on the U point.  Should I just do an "average" of stress12U to get stress12T?  Or is there a computation I can do directly on the T grid point?

**Comment by JFLemieux73** [comment]
The simplest and cheapest approach is to average the stress12U but I think the best approach (slightly more expensive...no issue for scaling) is to calculate stress12T inside the subcycling loop. You could just copy the calculation for stress12T in stressCD_T into stressC_T. 

If we choose the averaging approach, it would be good to first compare the two approaches (i.e., plot the states of stress with ellipse).

**Comment by apcraig** [comment]
Thanks @JFLemieux73, I now see how to copy the stress12T calc into stressCD_T.  I agree that's better.  More soon.

**Comment by JFLemieux73** [comment]
Hum...more complicated than I thought. I think we need the correct sign for shearT. So sqrt(shearT) does not work. 

The problem if we want to calculate in stran_rates_T is that we don't have vvelE and uvelN to easily compute dvdx and dudy at the T point. Let me look a bit more closely.

**Comment by apcraig** [comment]
vvelE and uvelN are computed at the end of each subcycle.  They are just a 4 pt average of vvelN and uvelE respectively.  I don't know if that's good enough or not.

shearTsqr is really just an average of shearU**2.  Maybe it's reasonable/correct to compute stress12T as an average of stress12U?

**Comment by JFLemieux73** [comment]
Or in stressC_T we also calculate shearT from the shearU values (similar to shearTsqr). 

shearT=(shearU(i,j)* uarea(i  ,j ) + ...

That's the method I would suggest. If we go with stress12T as an average of stress12U it would be good again to compare the states of stress with the other method.

**Comment by apcraig** [comment]
Just to clarify,

```
 shearT = (shearU(i  ,j  ) * uarea(i  ,j  )  &
                    + shearU(i  ,j-1) * uarea(i  ,j-1)  &
                    + shearU(i-1,j-1) * uarea(i-1,j-1)  &
                    + shearU(i-1,j  ) * uarea(i-1,j  )) &
                    / (uarea(i,j)+uarea(i,j-1)+uarea(i-1,j-1)+uarea(i-1,j))
```

in stressC_T?  And shearTsqr /= shearT**2, that's OK, right?

**Comment by JFLemieux73** [comment]
Yes in stressC_T. 

And shearTsqr /= shearT**2, that's OK, right? ...you are right

Dave you are probably right but I would test both...I just want to make sure the average of the stress12U leads to stresses on and inside the yield curve.

**Comment by apcraig** [comment]
OK, I'll try both.  I'll run C-grid cases with gx3 for 5 days.  Is that enough?  What do I need to output and plot?

**Comment by JFLemieux73** [comment]
@phil-blain you have some python code to plot the states of stress on the ellipse, right? Could you please make it available to Tony? Merci!

**Comment by apcraig** [comment]
I can make some elliptical plots, remind me what the two fields are I'm plotting.  Is it sig1 vs sig2?

**Comment by phil-blain** [comment]
unfortunately I do not (Amélie had such a script which I did not copy in time before her account was deleted!)

**Comment by eclare108213** [comment]
I have an ancient one written in IDL - let me dredge it up

**Comment by eclare108213** [comment]
[ellipse.pro.txt](https://github.com/CICE-Consortium/CICE/files/10145001/ellipse.pro.txt)
This is ancient indeed.  Are you familiar with IDL?  Let me know if any of it is not understandable.  Basically it defines and plots an ellipse with x and y axes, then reads in sig1 and sig2 and scatter-plots them on top.
The vectors xa and xb = [1, 2, ..., 300]/100 - 2.
imt, jmt are the array dimensions from the netcdf file (so 100, 116 for the gx3 grid).
The resulting plot will look something like this:

![ellipse_sample](https://user-images.githubusercontent.com/8173983/205405747-78c69bf3-932d-43a9-8a3f-a16119401b06.png)

**Comment by apcraig** [comment]
OK, I have some plots.  sig1 vs sig2.
- B grid
- C grid with shearT = avg(shearU)
- C grid with stress12T = avg(stress12U)

The shearT average which then goes into a stress12T computation is better.  Its on/inside the ellipse.  There are also points I don't show that are way off the domain of the plot for the avg(stress12U) case.  So we should go with avg(shearU).  It will be a little more expensive, but it's better and based on one test, looks like it won't increase cost by more than 0.5%.

![ep bgrid](https://user-images.githubusercontent.com/8182814/205405322-02929e9d-d625-474b-bb95-285ce9060cce.gif)
![ep shearavg](https://user-images.githubusercontent.com/8182814/205405341-3c1ac787-c7e4-4dd4-9832-7c7bbd4955e7.gif)
![ep stress12avg](https://user-images.githubusercontent.com/8182814/205405352-7f39472e-591a-4a3a-8114-337a34ae4414.gif)

**Comment by JFLemieux73** [comment]
Thanks Tony. It's good to see that the points are on and inside the ellipse. Could you please try it with avg_strength instead of avg_zeta?

**Comment by apcraig** [comment]
One more plot
- C grid with shearT = avg(shearU) with visc_method=avg_strength

![ep shearTavg_avgstr](https://user-images.githubusercontent.com/8182814/205454956-86b7cfbb-b834-4bdd-a692-7f9af57a1e3c.gif)

**Comment by JFLemieux73** [comment]
Great! Thanks again Tony. Having the stresses inside and on the ellipse is a good indication that what we coded is ok.
