### ISSUE TITLE
Investigate thick ice in C-grid simulations

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#708]
gx3 simulations show thicker ice with C-grid (compared to B-grid). See issue #702. Many idealized test cases show comparable results between C and B grid. Why is it not the case for gx3? Here are a few things to investigate:

-Coriolis
-advection
-deformations (used for redistribution)
-thermo
-gx 3 restart

I will use commit bffe4e8797f4d166d179df8df8ccc44a42295b13. I will use a combination of test cases to investigate this.

**Comment by JFLemieux73** [comment]
boxsyme with:
ndte=1200
capping=0
visc_method     = 'avg_zeta'
deltaminEVP =2e-9
Pstar=1e4
elasticDamp=0.36 (default)

I finally set coriolis='constant'. Here is the uvel field after one day for the B grid:

![B_cor_uvel_1_02-00000](https://user-images.githubusercontent.com/31927797/160869766-f6fb4c90-509f-41c6-bbb9-c13ff48e4acc.png)

and the uvelE field (C grid)

![C_cor_uvelE_1_02-00000](https://user-images.githubusercontent.com/31927797/160869881-11f63121-6879-4895-a188-e52d2e2b26eb.png)

**Comment by JFLemieux73** [comment]
The vvel and vvelN fields are respectively:

![B_cor_vvel_1_02-00000](https://user-images.githubusercontent.com/31927797/160870027-d6baf4a5-936a-4ef5-94e7-212259eb2e03.png)


![C_cor_vvelN_1_01-03600](https://user-images.githubusercontent.com/31927797/160870064-f9bc2891-be64-4b03-bdeb-46521422a32e.png)

**Comment by JFLemieux73** [comment]
The patterns are similar but not exactly the same. Note that the 4 figures above are steady-state solutions (after one day). Same fields after one time step (1 hour) are also  very similar (not shown).

**Comment by JFLemieux73** [comment]
I now want to test advection:
./cice.setup -c boxwallp5 -m daley -e intel -s debug,boxwallp5,gridc -g gbox80
ndte=1200
capping=0
visc_method = 'avg_zeta'
deltaminEVP =2e-9
Pstar=1e4
elasticDamp=0.1 (I decreased it...)
I have set close_boundaries=.true. and ktransport=1. 

@eclare108213 does it make sense to have ktransport = 1 if kridge = -1 ?

**Comment by JFLemieux73** [comment]
Thanks. Ok I will use kridge=1. Here is the B grid hi after 7 days (hist_avg=.true., daily outputs)

![B_hi_07](https://user-images.githubusercontent.com/31927797/160910172-2f50be82-b0b0-4db4-b4b0-75a6012dabd3.png)

and the C grid hi after 7 days:

![C_hi_07](https://user-images.githubusercontent.com/31927797/160910220-432ed3f6-4f57-4f08-bef6-5f827cf606bd.png)

**Comment by JFLemieux73** [comment]
It looks like there is some noise in both south-east north-east corners in the C grid solution. I change the range of values: 1.5 to 1.80.

![C_hi_07_b](https://user-images.githubusercontent.com/31927797/160910995-7be9b9f7-5e08-41da-b867-51b1c71f2e96.png)

**Comment by JFLemieux73** [comment]
So we see the noise in both corners. This might be the problem we are seeing in the gx3 simulations (there are a lot of corners...). Is it due to advection or ridging?

**Comment by JFLemieux73** [comment]
aice does exceed 1.0 during the first three days. I want to separate the effect of advection and ridging. Below is hi after 3 days with ktransport=1 but kridge=-1. I set the range to 1.0 to 1.7 m. For the B grid:

![B_kridgeoff__hi_03](https://user-images.githubusercontent.com/31927797/160917395-8b928716-dcc2-4aa4-a4da-8f435ff7f764.png)

and for the C grid:

![C_kridgeoff__hi_03](https://user-images.githubusercontent.com/31927797/160917436-59f55b46-0ff9-48e7-a829-dad1fd1a2d62.png)

**Comment by JFLemieux73** [comment]
The patterns are the same. For both the thick band on the wall is 1.6626 m thick. Note however that the thickest ice is ~1.68 m for B and ~1.72 for C (is that an issue?). My impression though is that the problem is in the ridging...probably in the deformation_T subroutine. Note that we dont calc DeltaT in deformationT the same way we calc DeltaT for the viscosities (Bouillon approach). This is a legacy of the CD grid...I guess this is what we need to fix.

**Comment by JFLemieux73** [comment]
Hum...but the ridging should not change hi (mean thickness). Most of the tests done for the C grid are with uniform conditions. Is it possible there is a problem when aice, hi (and strength) vary spatially?

**Comment by JFLemieux73** [comment]
It is kstrength=1 (complicated formula) in gx3 while it is kstrength=0 (Hibler) here. I could test both.

**Comment by dabail10** [comment]
I'm looking here at deformations_T. Have you updated to the latest code where Tony has refactored these? I think it is doing the right thing for the C grid. It calls strain_rates_T which is now a module procedure that includes two versions of this. The one that should be called for the C grid is strain_rates_Tdtsd. This computes divT, tensionT, shearT, and DeltaT.

**Comment by JFLemieux73** [comment]
Yes but it computes shearT as:

       shearT(i,j) = (dxT(i,j)**2)*(uvelN(i,j)/dxN(i,j) - uvelN(i,j-1)/dxN(i,j-1)) &
                     + (dyT(i,j)**2)*(vvelE(i,j)/dyE(i,j) - vvelE(i-1,j)/dyE(i-1,j))

That's not the Bouillon approach that we use for DeltaT for the viscosities at the T point.

**Comment by JFLemieux73** [comment]
In fact we don't even need to recalculate the strain rates as they are already stored. I will try that.

**Comment by JFLemieux73** [comment]
Not sure if this helping...

**Comment by JFLemieux73** [comment]
I also ran it with upwind advection. 

B grid:
![Bupwind_hi_11-00000](https://user-images.githubusercontent.com/31927797/161147984-48f341e4-5397-4e7c-a82d-552f45b7c154.png)

C grid:
![Cupwind_hi_11-00000](https://user-images.githubusercontent.com/31927797/161148043-e8c3a12c-2b4b-4c01-a41a-68ae903c1ca3.png)

**Comment by JFLemieux73** [comment]
So it is thicker with the C grid. I am going back to the first few time levels to see what is going on at the beginning.

**Comment by JFLemieux73** [comment]
I have coded a new deformations_T subroutine for which DeltaT is calc using shearTsqr (the avg of the shearU**2). As expected this does not change the volume. I ran the same test as above with upwind and the hi field is the same.

**Comment by JFLemieux73** [comment]
Here is dvidtd (change of volume due to dynamic) for the B grid after one time step (1 hour):

![B_dvidtd_1_01-03600](https://user-images.githubusercontent.com/31927797/161283060-ac5d8bda-3b07-4814-aaee-fc92741b3aff.png)

C grid:

![C_dvidtd_1_01-03600](https://user-images.githubusercontent.com/31927797/161283142-f9cd42ac-06e7-49dd-9dd7-b5067d9fcb3b.png)

Note that this is with upwind. We already see a difference...

**Comment by JFLemieux73** [comment]
But I guess with remap it should be very similar:
B grid:

![B_remap__dvidtd_1_01-03600](https://user-images.githubusercontent.com/31927797/161290016-93608884-e6ac-4cc8-8cdc-8296e5205a29.png)

C grid:
![C_remap__dvidtd_1_01-03600](https://user-images.githubusercontent.com/31927797/161290088-4aa34184-db67-4105-85da-ff6b9b830d73.png)

**Comment by JFLemieux73** [comment]
Going back to the 80x80 boxwallp5 test case. I want to see the impact over longer sims. Here is hi after 29 days with upwind advection.
B grid:
![B_upwind__hi_29](https://user-images.githubusercontent.com/31927797/161324796-76cd0a8f-2fe8-4039-839b-7118f1f84c87.png)

C grid:

![C_upwind__hi_29](https://user-images.githubusercontent.com/31927797/161324824-c1e45e69-867d-4071-a3e4-82abdc018677.png)

**Comment by JFLemieux73** [comment]
Here are also the pressure (sigP) fields after 29 days:
B grid:

![B_upwind_sigP_29](https://user-images.githubusercontent.com/31927797/161325415-d97847a0-cce4-4b11-864e-ffd716237294.png)

C grid:


![C_upwind_sigP_29](https://user-images.githubusercontent.com/31927797/161325452-1145d5aa-a739-4253-a68f-71dc6097159a.png)

**Comment by JFLemieux73** [comment]
They look good. The pressure increases toward the coast to balance the wind stress. I am going to do the same thing with the remapping scheme.

**Comment by JFLemieux73** [comment]
Here is hi (C-grid) after 29 days with remapping:

![C_remap_hi_29](https://user-images.githubusercontent.com/31927797/161333172-e0ab3e04-7def-4178-aa9d-8de5660d6841.png)

**Comment by JFLemieux73** [comment]
It's a bit less smooth near the corners but it's hard to tell if something is wrong. I think I should focus on gx3 simulations. I will use issue #702 for this.

**Comment by JFLemieux73** [comment]
I also tested a northeast forcing. Here is the B grid hi after one month:
![B_hi_01](https://user-images.githubusercontent.com/31927797/161583254-a8770b9f-be1b-4822-85a6-841460e850e2.png)

and C grid hi:
![C_hi_01](https://user-images.githubusercontent.com/31927797/161583291-ea7fc073-ce0d-44e5-a6fd-e6abef592b93.png)

They are very similar.

**Comment by JFLemieux73** [comment]
Idealized test cases do not show this thickening. This should be investigated in gx3 and gx1 simulations (see issue #702).
