### ISSUE TITLE
Impact of namelist parameters

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#712]
I want to see the impact of some parameters in the namelist so that we can set default values. The reference simulation (gx3) is:

ndte=1200,
kstrength=0,
visc_method = 'avg_zeta'
elasticDamp = 0.12d0
deltaminEVP = 2e-9
capping = 0.

Here is the impact of deltaminEVP (2e-9 versus 1e-11) for the B-grid:

![volume_B_dmin2e_9_B_dmin1e_11](https://user-images.githubusercontent.com/31927797/165529984-aa621084-6117-4baa-8752-92feb4077f62.png)

and the C-grid:

![volume_C_dmin2e_9_C_dmin1e_11](https://user-images.githubusercontent.com/31927797/165530039-c9ef8468-23a1-4644-9e1d-e653148398cf.png)

**Comment by JFLemieux73** [comment]
Here is the effect of the capping. The blue curve is the ref solution (as above) with capping=0. The effect is again very small (same idea for the B-grid...not shown).

![volume_C_cap0_C_cap1](https://user-images.githubusercontent.com/31927797/165566619-656bf627-18ff-4d7b-8fda-a96627acf800.png)

**Comment by eclare108213** [comment]
Are you sure they're different?

**Comment by JFLemieux73** [comment]
They are. The last line of the diag file for capping = 0 is:

total ice volume (m^3) =    2.27639676857355273E+13   3.05920987634240430E+12

for capping=1:

total ice volume (m^3) =    2.27109412040723437E+13   3.03732563085688965E+12

**Comment by JFLemieux73** [comment]
And now the impact of the method for calculating eta at the U point. The ref is again in blue (avg_zeta). The red curve is for avg_strength.

![volume_C_avg_zeta_C_avg_strength](https://user-images.githubusercontent.com/31927797/165599197-a59dce43-5466-4de7-980f-a68a076d73c0.png)

I just verified and they are slightly different again ! :)

**Comment by JFLemieux73** [comment]
Ok I have also compared the reference run to a similar run but with elasticDamp=0.36 and ndte=240 (the current default values). Again the blue and red curves are on top of each other for the B and C grids (not shown). So basically it looks like the  numerical parameters have a very small effect for gx3 runs. Good! I will now repeat these experiments with gx1.

**Comment by eclare108213** [comment]
Thanks for being so thorough, JF.  All of this is really helpful to see.  Good!

**Comment by JFLemieux73** [comment]
Here are the first results for gx1. The C-grid code is slower so the runs are for 3 years instead of 5. Again the ref solution is with

ndte=1200,
kstrength=0,
visc_method = 'avg_zeta' (affects only C-grid)
elasticDamp = 0.12d0
deltaminEVP = 2e-9
capping = 0.

Here is the impact of deltaminEVP (2e-9 versus 1e-11) for the B-grid:

![volume_B_ref_B_dmin_1e_11](https://user-images.githubusercontent.com/31927797/166056814-b750db6c-a712-4d51-a383-9905c487f243.png)

**Comment by JFLemieux73** [comment]
The differences are very small. It is the same conclusion for the C-grid (not shown).

**Comment by JFLemieux73** [comment]
As for gx3, setting capping=1 or to use avg_strength or to set ndte=240 and elastdamp=0.36 have very little impact on the total volume (not shown).

**Comment by JFLemieux73** [comment]
At this spatial resolution, it looks like 240 subcycles is ok (with elastdamp=0.36). Even with 120 subcycles the curve is on top of the ref solution (ndte=1200, elastdamp=0.12), not shown. This is true for both B and C grids. I also tested 60 subcycles. We start to see differences which are a bit bigger for the C grid than for the B grid. Here is the volume for 60 subcycles for the B grid compared to the ref solution:

![volume_B_ref_B_60sub](https://user-images.githubusercontent.com/31927797/166470292-69f253e2-79f1-4472-a3ba-39bcda465c55.png)

And for the C grid:

![volume_C_ref_C_60sub](https://user-images.githubusercontent.com/31927797/166470346-b7260533-c577-40b7-9efd-9a15cb142cf1.png)

**Comment by eclare108213** [comment]
These results are consistent with Urrego-Blanco et al (2016), whose UQ study indicated that the primary sensitivities in CICE are to radiative parameters and snow and ice densities.  For dynamics parameters, there is some sensitivity to dragio, and slight sensitivity to ecc and Cs.                     
[Jorge_UQ.pdf](https://github.com/CICE-Consortium/CICE/files/8682667/Jorge_UQ.pdf)

**Comment by JFLemieux73** [comment]
It was decided to keep the same default parameters and to add an advice in the documentation to increase ndte for high resolution applications (see pull request #722).
