### ISSUE TITLE
provide C-grid results to community as part of next release

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#741]

**Comment by JFLemieux73** [comment]
Hi Elizabeth, I don't have more material than what is already shown in the issues (e.g. issue #702).

**Comment by eclare108213** [comment]
I had just found #702!  I can use the gx3 runs there, but if any of you have higher-res or other configuration comparisons, please share.  Thx

**Comment by JFLemieux73** [comment]
You could check issues #697, #699 and #708.

**Comment by eclare108213** [comment]
Yes, those are all box tests.  The gx3 will do, for now.  Thanks!

**Comment by dabail10** [comment]
I did run gx1 tests with C and D. I didn't do any plots beyond the QC test though. We are not running C-grid in CESM.

**Comment by eclare108213** [comment]
How's this look?  Happy to make changes, emphasize different things, etc.
[Cgrid.pdf](https://github.com/CICE-Consortium/CICE/files/9914041/Cgrid.pdf)

**Comment by DeniseWorthen** [comment]
I only tested C-grid in the context of why it wasn't reproducing the B-grid for the nuopc cap coupling. There is some validation being done w/ the C-grid by someone at GFDL. I'm not sure on how mature those efforts (and I can't find the relevant github user name). I can email you the contact info if you're interested.

**Comment by apcraig** [comment]
Moved to #870
