### ISSUE TITLE
Read the Docs `latest` links still points to master, so is not the latest

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#759]
See the bottom of the column on the right of https://readthedocs.org/projects/cice-consortium-cice/:

> **Latest version**
> master

This means that https://cice-consortium-cice.readthedocs.io/en/latest/ is not the latest version of the documentation as we have stopped updating the `master` branch since the switch to `main`.

**Comment by apcraig** [comment]
I fixed this, it points to "main" now.  The language was vague about what the default setting was.  I thought it was the default branch which I set to main several months ago.  But apparently it's more or less hardcoded to master.  Fixed now.

**Comment by eclare108213** [comment]
Thanks for noticing it and pointing it out, @phil-blain, and thanks for fixing it @apcraig!  Lots of little details need lots of eyes on them.

**Comment by phil-blain** [comment]
Thanks!
