### ISSUE TITLE
Document CICE scripts

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#77]
especially ICE_RUNLENGTH

**Comment by eclare108213** [comment]
The CICE documentation still has create.case instead of cice.setup, with the old flags.  That should be fixed soon!

**Comment by duvivier** [comment]
Oops, I just changed that all. Will do a PR soon.

**Comment by duvivier** [comment]
Just adding to this (as a list for my reference): 
- The quickstart, user's guide, and developer's guides all need to be thoroughly tested and updated with the correct documentation in the *rst files.

**Comment by eclare108213** [comment]
If ICE_RUNLENGTH has been documented, this issue can be closed.  I don't remember seeing that.  ??

**Comment by apcraig** [comment]
ICE_RUNLENGTH is documented and I will close this, but we will need to review documentation before every release.
