### ISSUE TITLE
Test variable grid spacing for C grid - part2

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#791]
See also issue #786.

**Comment by eclare108213** [comment]
I checked the discretization in the overleaf document.  It looks okay to me, just one question about a sign in the replacement pressure, which should not affect symmetry.  

There might be a typo in the translation from the document to the code.  There, we should be able to replace i with j and j with i (which will change off-diagonal array elements but not the diagonal i,j and i+1,j+1 elements), and come up with the same discretization for each term but rotated 90 degrees and probably flipped in sign for some of them.

**Comment by JFLemieux73** [comment]
Thanks for checking the discretization. Is the error in the code or the document?

**Comment by eclare108213** [comment]
The comment is in the document.  Not sure whether it's an error.

**Comment by JFLemieux73** [comment]
Ok I will have a look. Thanks!

**Comment by JFLemieux73** [comment]
Let's start with the uniform grid (dx=constant). For some reason my VP run finished successfully but the last output files are not there. So I will look at 2005-01-26 (after 25 days). I used 100 nonlinear iterations.  Here is the hi field:

![Bvp_NE_cdx_hi_2005-01-26-00000](https://user-images.githubusercontent.com/31927797/201996294-6ff17b70-6878-4f94-815a-e4e53223b677.png)

**Comment by JFLemieux73** [comment]
Ok the issue with the missing outputs was just the walltime allowed not set properly. No worries. Here is the B grid EVP solution:

![Bevp_NE_cdx_hi_2005-01-26-00000](https://user-images.githubusercontent.com/31927797/202010490-1e033d52-8863-49d9-8efe-e7bcbb0e35af.png)

and for the C grid EVP:

![Cevp_NE_cdx_hi_2005-01-26-00000](https://user-images.githubusercontent.com/31927797/202010546-177ecbde-ef9a-4ab4-9825-29c623a07f04.png)

**Comment by JFLemieux73** [comment]
It is weird for the C grid. Is it due to the fact that P*=2.75e4? I have seen problems before with stiff problems (e.g. issue #697). Let's try with P*=1e4.

**Comment by JFLemieux73** [comment]
Ok there is clearly something going on in the corners. Here is aice after 2 weeks (range is between 0.9 and 1.0). I don't think it is related to the EVP; the pattern is symmetrical. 

![Cevp_NE_cdx_P1e4_aice_2005-01-15-00000](https://user-images.githubusercontent.com/31927797/202016998-ea41f762-cc89-40bb-a239-18dc834c5d34.png)

The problem is seen using a uniform grid. I will open a new issue with a better title.

**Comment by JFLemieux73** [comment]
As shown in issue #792, the checkerboard pattern in the corner is related to the remapping. I am going to use upwind for the rest of the tests here to see if there is still thickening in corners with the C grid. 

dt=1h
ndte=2400
elasticDamp=0.1
advection='upwind'
ice_data_conc   = 'p8'

Let's look at the solutions after 1 month.

**Comment by JFLemieux73** [comment]
Here is the hi B grid solution:

![Bevp_NE_cdx_P1e4_upwind_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/202292477-9737156e-7d8f-4ec4-b6ac-04811dfa5b7c.png)

And the C grid:

![Cevp_NE_cdx_P1e4_upwind_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/202292534-07989909-2f4c-4042-8fd2-23b111196e70.png)

Note that the ice is thicker than in previous tests because Pstar = 1e4.

**Comment by JFLemieux73** [comment]
Here is C-B:

![Cevp_NE_cdx_P1e4_upwind_Bevp_NE_cdx_P1e4_upwind_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/202293857-50d6c250-c296-46c2-b943-8f57a0dd3249.png)

The differences are small but we do see thicker ice with the C grid but not exactly in the corner.

**Comment by JFLemieux73** [comment]
I have verified and the diff between EVP (B grid) and VP (B grid) are very small (~1 mm, not shown).

**Comment by JFLemieux73** [comment]
The C grid noise has been eliminated with l_fixed_area=T (see issues #809 and #811). The code does not crash anymore for gx simulations (see PR #833).
