### ISSUE TITLE
Found one remaining `#ifdef ncdf` not covered by `USE_NETCDF`

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#796]
I just stumbled upon these lines:

https://github.com/CICE-Consortium/CICE/blob/4f7f7cf626984bd08a32829294adef0c7226b3f5/cicecore/cicedynB/analysis/ice_history.F90#L421-L423

All other uses of `ncdf` were cleaned up and the macro renamed to `USE_NETCDF` in https://github.com/CICE-Consortium/CICE/pull/490, but this one was forgotten, I think.

I'm not sure of the implications as I did not look further, apart to find out that it dates back to https://github.com/CICE-Consortium/CICE-svn-trunk/commit/f41374dc6c9e4bd6922ae7f6c27fa02ad8c48f87.

@apcraig

**Comment by phil-blain** [comment]
Looking at that a bit, I think we should just remove those 3 lines, and let `f_bounds` acquire its value from the namelist as the rest of the `f_*` variables. 

I'm not sure I understand why it was special-cased...

**Comment by apcraig** [comment]
Fixing this week.  Thanks @phil-blain
