### ISSUE TITLE
JRA55do files and JRA55 file names

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#840]
Need to add the new JRA55do files to distribute. Also, the old JRA55 files will have a name change.

**Comment by dabail10** [comment]
Also, the tables need to change. Did we decide to distribute both the JRA55 and JRA55do data? We will need to update the references here.

https://github.com/CICE-Consortium/CICE/wiki/CICE-Input-Data

**Comment by daveh150** [comment]
I was thinking both JRA55 and JRA55do can be posted on zenodo under separate links. I agree we need to update the JRA55 file names for new code to work.

**Comment by dabail10** [comment]
Ok. I have added the JRA55do data by year to the Zenodo and updated the inputdata wiki. Let me know if you see any issues here. I am currently preparing renamed gx1 datasets. I will add these as an "update" and they get a new DOI. I think this is the way we want to do it. Then we add another entry where the new versions should only be used with CICE 6.4.2+ or whatever.

**Comment by dabail10** [comment]
Ok. I have added the JRA55do to Zenodo and updated the names in the gx1 JRA55 forcing by year. All of the links are added to the CICE Input Data page.

https://zenodo.org/record/8117763 (gx3 JRA55do)
https://zenodo.org/record/8118062 (gx1 JRA55do)
https://zenodo.org/record/8118183 (tx1 JRA55do)
https://zenodo.org/record/8118239 (gx1 JRA55 v2)
