### ISSUE TITLE
Test nghost

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#855]
Test nghost > 1, should be identical to nghost=1 for a given problem.

Alternatively, check value of nghost at initialization, abort if it's not 1.

**Comment by eclare108213** [comment]
If it actually works (which surprises me!), then it would be nice to maintain it.  I don't think we need to make nghost a namelist input until someone actually needs to change it.  That said, maintaining it means testing that it doesn't get broken in some PR, which might require a namelist input.  I'm also fine just leaving things as they are.

**Comment by apcraig** [comment]
I too was surprised the it even ran including with debug flags on.  Then it produce bit-for-bit was even more shocking.  It could be eap or vp or some other configurations don't work with nghost>1, so another step might be to extend the testing.

I'm undecided as well whether to test and maintain the nghost capability or just punt for now.  If we do want to test, we need to make nghost a namelist so the testing software can run those tests.

If the likelihood that nghost is >1 anytime in the next decade or so is low, maybe we should just leave it alone.

**Comment by apcraig** [comment]
But from a software engineering perspective, it would be cool to add the necessary test cases and make it part of our test suite.

I guess the question is whether it's a requirement for the code to run with nghost>1.  If so, we should test and maintain it.  If not, then we shouldn't.

One way to view nghost is that it's a parameter set to 1 and it's not expected/allowed to change without further testing/development.  The fact that a bunch of code supports nghost>1 doesn't mean it's a requirement to do so.

**Comment by eclare108213** [comment]
I doubt that it will be needed, perhaps ever.  It's only in there because CICE was built on POP's framework. We could just note in the documentation that it exists and if it needs to be used, then the developer needing it should take care to test it very thoroughly, and at that point add a namelist option for it.

**Comment by apcraig** [comment]
I agree, I'll try to add something to the documentation then will close this issue.  Thanks.
