### ISSUE TITLE
Transport in one grid cell wide channels.

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#868]
@apcraig I will start modifying the remapping code to get transport in one grid cell wide channels. Would have time to implement a new test case? I think the best way to test this would be a east-west one grid cell wide channel maybe 200 km long.  The initial ice conditions would be:

aice=0.5
thickness = 1 m
there is ice only between 10 and 60 km (a 50 km long block of ice). 
There could be walls on both sides (at 0 km and 200 km).

The wind blows from the west at 5 m/s. We can then look at the ice fields after a few days...The block should be advected. 

note: it would be nice also to have a south-north channel to make sure we get the same thing.

**Comment by JFLemieux73** [comment]
12 lines of code...that's what was needed! 

I coded a simple test case. Here is the initial condition (hi):

![ic](https://github.com/CICE-Consortium/CICE/assets/31927797/0c37dd4f-c57e-433e-8b36-97a4ab8f2429)

**Comment by JFLemieux73** [comment]
Here is the hi field after 20 days with upwind:

![Upwind_hi_2005-01-20](https://github.com/CICE-Consortium/CICE/assets/31927797/a18adcd4-96e4-4654-935f-72c7f5303750)

and now with remap:


![Remap_hi_2005-01-20](https://github.com/CICE-Consortium/CICE/assets/31927797/a72c4b4b-e204-4d32-a485-45fce2ecd705)

**Comment by JFLemieux73** [comment]
So there is transport with remap (thanks to l_fixed_area = T). The solution is also a lot less diffused than the upwind one...good!

**Comment by dabail10** [comment]
Wow. So, the incremental remapping does not just reduce to upwind in a situation like this? Great news.

**Comment by apcraig** [comment]
Glad it was easy to setup and test.  What's the next step?  Do we want to formally commit the 1-grid channel grid to the code and setup a test in the test suite?  Should we have a look at what the boxislands test is doing?

**Comment by JFLemieux73** [comment]
I created the test a bit quickly. For example the box is 80x80...Let me clean it up before I commit it. I also think it would be good to test a north-south channel. I don't think we need the boxislands test case right now.

**Comment by apcraig** [comment]
@JFLemieux73, if you want me to create a PR, I can also do that.  I would also add a N-S channel case and add tests to the test suite and update documentation where needed.  I'll also have a quick look at the boxislands test just for my own sanity.

**Comment by JFLemieux73** [comment]
Yes maybe it is better (and faster) if you create the test cases. Should I first create a PR with my modifs to ice_transport_remap?

**Comment by apcraig** [comment]
Just to be clear, to get transport in the channel, we need to modify the code??

If the problem is just very stiff, why don't we get some small non-zero transport?  Why is it zero in the channel by default?

**Comment by JFLemieux73** [comment]
Yes you need the code I have in 

https://github.com/JFLemieux73/CICE/tree/OneGridChannels

With that code you should get transport even for the noisy boxislands test case.

**Comment by JFLemieux73** [comment]
That's why  I was asking if I should first do a PR with this branch.

**Comment by apcraig** [comment]
I can do the code modifications as part of setting up the single channel tests.  Will those modifications change answers to "standard" test cases?  Is there a reason why these modifications aren't or haven't been added to the code before now?

**Comment by apcraig** [comment]
See #875
