### ISSUE TITLE
time level inconsistency in transport code

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#87]
From: Frederic Dupont <Frederic.Dupont@ec.gc.ca>
Subject: small inconsistency in CICE512
Date: October 14, 2016 at 2:14:04 PM MDT
To: Elizabeth Hunke <eclare@lanl.gov>

Hi Elizabeth,

I think I found a small inconsistency in CICE 5.1.2 for shift_ice (in
ice_itd.F90):

for each receiving category, at each point:

      do n = 1, ncat-1
     [ some checks done ...]
     [ prepare ishift pointers for cat n ]
         do ij = 1, ishift
            i = indxii(ij)
            j = indxjj(ij)
            m = indxij(ij)

            nd = donor(m,n)
      !echmod            worka(i,j) = dvice(m,n) / vicen(i,j,nd)
            worka(i,j) = daice(m,n) / aicen(i,j,nd)
            if (nd  ==  n) then
               nr = nd+1
            else                ! nd = n+1
               nr = n
            endif

            aicen(i,j,nd) = aicen(i,j,nd) - daice(m,n)
            aicen(i,j,nr) = aicen(i,j,nr) + daice(m,n)

            vicen(i,j,nd) = vicen(i,j,nd) - dvice(m,n)
            vicen(i,j,nr) = vicen(i,j,nr) + dvice(m,n)

            dvsnow = vsnon(i,j,nd) * worka(i,j)
            vsnon(i,j,nd) = vsnon(i,j,nd) - dvsnow
            vsnon(i,j,nr) = vsnon(i,j,nr) + dvsnow
            workb(i,j) = dvsnow

         enddo                  ! ij

     [ followed by the actual transport in thickness space for all tracers, including enthalpies, etc...]
      enddo                     ! boundaries, 1 to ncat-1

The issue is for snow:

because the worka/workb arrays are dependent on aicen(i,j,nd) and vsnon(i,j,nd). In case of growth (shift towards thicker cat, i.e.
increasing n), aicen(i,j,nd) and vsnon(i,j,nd) might have already been updated. It would be more in line with the rest of the transport
equation in thickness space that worka be computed with aicen and vsnon at the previous timestep (Euler-forward approach), therefore saving
aicen/vnson at the beginning of the routine in separate arrays. It is not a serious inconsistency but I don't see any reasons why the cases of growth and melt would be treated differently. (correction attached with some goodies from bigger ITDs)

Anyway, the code is already a nice improvement to what was done in CICE4!

I would have an additional question regarding the formulation of worka since I noted that it changes from a fraction in volume (CICE 4.1) to a fraction in area (5.1.2). Is it because it was found that there was not much correlation between volume of snow and ice being advected to the next category (i.e. volume of snow is not necessarily proportional to volume of ice)?

Fred.

**Comment by eclare108213** [comment]
@dupontf @JFLemieux73 @phil-blain 
Does this still need to be fixed, or was it already done?  I don't think it was -

**Comment by dupontf** [comment]
Hi Elizabeth, I think JF commited something about this. @JFLemieux73, can you confirm?

**Comment by JFLemieux73** [comment]
Hi,

I juts checked my commits and it is not there. I am a bit confused as I thought there was a pull request for that.

**Comment by eclare108213** [comment]
Ah, it's in icepack, not cice:
https://github.com/CICE-Consortium/Icepack/pull/222
I'll close this one.
