### ISSUE TITLE
Issue with mesh mask check in nuopc/cmeps cap

### ISSUE THREAD

**Issue by dougiesquire** [CICE-Consortium/CICE#871]
I could well be wrong, but the consistency check between the internal and supplied mesh masks in [cicecore/drivers/nuopc/cmeps/ice_mesh_mod.F90](https://github.com/CICE-Consortium/CICE/blob/main/cicecore/drivers/nuopc/cmeps/ice_mesh_mod.F90#L669-L686) does not appear to do what it is supposed to. Should it not be something like the following: https://github.com/dougiesquire/CICE/compare/main...mesh_mask_check?

Happy to submit a PR if that's helpful.

**Comment by dabail10** [comment]
Good catch! I had not seen this before. Do you want to issue the PR?
