### ISSUE TITLE
freezing temperature namelist option

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#88]
Implement a namelist option for freezing temperature.  This has already been done for CESM/RASM, but I don't think it made it into the main CICE repo.

**Comment by dabail10** [comment]
The namelist option tfrz_option is already there. There is a call in ice_forcing.F90 to icepack_sea_freezing_temperature. This function is in ice_therm_shared.F90 and uses the flag tfrz_option.
