### ISSUE TITLE
ice_in variables undefined in chapter 5 of docs

### ISSUE THREAD

**Issue by rgrumbine** [CICE-Consortium/CICE#884]
https://cice-consortium-cice.readthedocs.io/en/main/cice_index.html 

As we discussed at the meeting, not all variables are expected to be defined here. Still, these are variables from sections of ice_in I was looking at for setting loose an evolutionary optimization program and which don't have definitions in the main docs: 

&dynamics_nml
    evp_algorithm    'standard_2d'
    Ktens            0.            
    capping_method   'max'         
    k1               7.5           
    k2               15.           
    alphab           20.           
    threshold_hw     30.           
    coriolis         'latitude'    
    kridge           1             
    ktransport       1             
    ssh_stress       'geostrophic'
    maxits_nonlin    10            
    precond          'pgmres'      
    dim_fgmres        50           
    dim_pgmres        5            
    maxits_fgmres    1             
    maxits_pgmres    1             
    monitor_nonlin   .false.       
    monitor_fgmres   .false.       
    monitor_pgmres   .false.       
    ortho_type       'mgs'         
    reltol_nonlin    1e-8          
    reltol_fgmres    1e-1          
    reltol_pgmres    1e-6          
    algo_nonlin      'picard'      
    use_mean_vrel    .true.        
/

&shortwave_nml
    snw_ssp_table    'test'        
    sw_redist          .false.     
    sw_frac            0.9d0       
    sw_dtemp           0.02d0      
/

&forcing_nml
    fe_data_type     'default'     
/

**Comment by rgrumbine** [comment]
Ah. That's good. But perhaps there should be a link from section 5 over here? It was section 5 I was looking at, which I agree isn't the best place but one a new user may well look. 

Or maybe all variables in section 3 ug_case_settings could automatically be dragged in to section 5?  https://cice-consortium-cice.readthedocs.io/en/main/cice_index.html

**Comment by apcraig** [comment]
OK, I understand now.   Section 5 (the code variable index) is sort of interesting.  It's not comprehensive (and it probably can't/shouldn't be) and it's not supposed to cover the namelist/model inputs completely either.  There already is a link to the namelist/model inputs section at the top of section 5, see the top paragraph in section 5 (I guess that's easy to overlook).  I don't think we should duplicate the namelist inputs into section 5.  About the only thing I think we could do is place the link to the namelist settings in a separate line at the top of section 5, taking it out of the paragraph so it's more obvious?  Maybe we should also rename section 3.4 from "Case Settings" to "Model Namelist Inputs, Model CPPs, and Other Settings"?

**Comment by rgrumbine** [comment]
I like your new name for section 3.4

Even knowing the link was in that short paragraph, it was almost invisible to me. Something about the color scheme and wording, I guess.

So yes, I like your solution of splitting the text to something like:
* Below are variable descriptions for those variables which are ... (including describing why certain classes of variables aren't present here)
* For parameters involved in controlling a model run see section 3.4 -- Model Namelist Inputs, Model CPPs, and Other Settings
