### ISSUE TITLE
grid_location is missing for C and CD grids for call to seabed_stress_factor_LKD

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#891]
I think hwu, au, and hu are not ok because the grid_location is missing. The code therefore assumes these should be calculated at the U point while they should be calculated either at the E or N point. 

I will be away for two weeks and won't have time to look at this. @apcraig @phil-blain please have a look if you have time. 

I think we should make this modification before the next release.

**Comment by phil-blain** [comment]
I see, this dates back to my https://github.com/apcraig/CICE/pull/20/commits/48c07c66af4f872a2896fbf83773e391d513abba.

I can fix that. It won't be bit for bit but I'll run the QC test.
