### ISSUE TITLE
Errors when running CICE test suite on Travis-CI

### ISSUE THREAD

**Issue by anders-dc** [CICE-Consortium/CICE#90]
Hi all,

I have tried running the CICE test suite on Travis-CI, but am encountering "Division by 0" errors. Is this a well-known problem? Please see the build log here:
https://travis-ci.org/anders-dc/CICE/jobs/343922056#L764

I am invoking Travis-CI from my [own fork](https://github.com/anders-dc/CICE/tree/travisCI), with the following [Macros](https://github.com/anders-dc/CICE/blob/travisCI/configuration/scripts/machines/Macros.travisCI_gnu) and [env](https://github.com/anders-dc/CICE/blob/travisCI/configuration/scripts/machines/env.travisCI_gnu) configuration. I used these settings because they were successful with Icepack.

Cheers, Anders

**Comment by eclare108213** [comment]
We found with Icepack and some compilers that we didn't regularly run with turn up issues like this.    Can you tell which compiler and configuration is crashing?  And which line it's crashing on?  It's likely that some of the things we fixed in the Icepack driver have not yet been fixed in CICE - we need to identify those and get them fixed....  I'll look back through the Icepack PRs for this kind of thing.

**Comment by eclare108213** [comment]
I looked through the Icepack PRs, and nothing jumped out at me.  Most of the bug fixes were within the column physics modules themselves or the forcing, which is different from CICE's.  There could be a missing parameter initialization...  we'll need to debug specific cases.

**Comment by anders-dc** [comment]
Thank you, I will dig out some more information and report back.

**Comment by anders-dc** [comment]
I can reproduce this bug from my local machine and the CICE master branch by running the `base_suite` with the `loft` environment:

    csh cice.setup --suite base_suite --testid travisCItest --mach loft --env gnu 

It turns out that the `Division by 0` error message is cast by [configuration/scripts/cice.batch.sh](configuration/scripts/cice.batch.sh). The variable `$taskpernode` evaluates to zero as `maxtpn = 1` and `nthrds = 2`.

**Comment by anders-dc** [comment]
I can mitigate this behavior by setting `setenv ICE_MACHINE_TPNODE 2` (instead of `1`). However, I didn't do this for Icepack.

**Comment by anders-dc** [comment]
@apcraig, @eclare108213 Could you please check if the following command runs on your system and the master branch of CICE?

    ./cice.setup --suite base_suite --testid travisCItest --mach loft --env gnu

I am not sure I am qualified to mess with [configuration/scripts/cice.settings](https://github.com/CICE-Consortium/CICE/blob/master/configuration/scripts/cice.settings). Thanks!

**Comment by anders-dc** [comment]
I suggest we continue the conversation in #111, where we can directly work on the code.
