### ISSUE TITLE
Finalize the release

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#91]
- [x] Complete [tasks for release](https://github.com/CICE-Consortium/Icepack/projects/2)
- [x] Create release notes at https://github.com/CICE-Consortium/CICE/wiki/CICE-Recent-changes
- [x] Update doc/source/conf.py version/release
- [x] Generate and check html and pdf documentation
- [x] Commit and push final changes to master including, at least,    
   doc/source/conf.py
- [x] Create release branch in repository if needed
Naming convention is CICEm.n
- [x] Generate test results and post to Test-Results wiki
Use --bgen with the full release name
- [x] Git Tag the release
Naming convention is CICEm.n.p
This generates documentation at readthedocs
- [x] Move release notes from https://github.com/CICE-Consortium/CICE/wiki/CICE-Recent-changes to https://github.com/CICE-Consortium/CICE/releases, and publish
- [x]  Post science results as needed
- [x] Add to zenodo community
- [x]  Add links in appropriate places on github where to find the release and tar file
[News](https://github.com/CICE-Consortium/About-Us/wiki/Consortium-News-and-Highlights)
[Version index](https://github.com/CICE-Consortium/CICE/wiki/CICE-Version-Index)
- [x] Send out release email s

**Comment by eclare108213** [comment]
We need to do a fresh Icepack release along with or just prior to the CICE v6 release.  See https://github.com/CICE-Consortium/Icepack/wiki/Icepack-Recent-changes

**Comment by duvivier** [comment]
@eclare108213 
I think we removed:  Generate and check html and pdf documentation
doc/source/intro/major_updates.rst also includes the version/release number, so we'll just have release notes with the release and put the info on the wiki. The html and pdf should be generated automatically with the PRs and release (I will double check that). we should just have to change the version numbers at points @apcraig has already noted.

**Comment by eclare108213** [comment]
Ok, I'll remove that from the checklist above.  I also don't know what is intended with this part:

         Use --bgen with the full release name
         Create release specific tables on wiki??

Probably they are left over from earlier iterations of this process and we can remove those too.

**Comment by duvivier** [comment]
I didn't know what that meant either. So, with that bit removed, I think that item can be checked off too.

**Comment by apcraig** [comment]
The release process is evolving as we gain experience.  I think the list above is based on the release process from a while back.  It is updated now,\

https://github.com/CICE-Consortium/About-Us/wiki/Release-Process

I would check off the --bgen task for now.

**Comment by eclare108213** [comment]
I will copy the checklist above to the release-process wiki, to use as a template in the future.
