### ISSUE TITLE
timers calls as in CESM

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#94]
CICE currently uses MPI_WTIME for calculating timings.  CESM uses GPTL.  Should we change this?
(revision 1121 in svn repository, cesm_cice branch)

**Comment by eclare108213** [comment]
Info from @dabail10 in email:

>The timers we use are from the General Purpose Timing Library (GPTL) that Jim Rozinski wrote. I >tried to wrap calls from the existing timers to this library. Kind of like this in ice_timers.F90:
>
>#ifdef CESMCOUPLED
>         call t_startf('ICE:'//all_timers(timer_id)%name)
>         call t_stampf(wall, usr, sys)
>         all_timers(timer_id)%block_cycles1(block_id) = wall
>#else
>         all_timers(timer_id)%block_cycles1(block_id) = MPI_WTIME()
>#endif
>
>The GPTL timers work better with OpenMP threading.

Is GPTL generally available on most/all machines, or is it something that users would be responsible for installing themselves?  If the latter, then I'd be inclined to stick with what we've got.

**Comment by dabail10** [comment]
Ok. We still install GPTL as a part of the CESM build.

**Comment by eclare108213** [comment]
I'd like to close this task without any changes, since GPTL is a package that would need to be installed.  Does anyone disagree with that?

**Comment by apcraig** [comment]
I agree that we can close this and stick with what we have.  I think MPI_WTIME works well enough.

Having said that, we could probably add the gptl code to CICE and treat it as CICE code in the standalone mode.  I'm not sure this is a good idea, but it's an option.  We would probably still have to support ifdef-ing it out when building/running in CESM and other models that might have their own copy of gptl.

I'm not in favor of having to build separate libraries as part of CICE standalone at this time.  It might be something we eventually have to do, but I don't think gptl is worth making that effort.

**Comment by dabail10** [comment]
The advantage of GPTL is that it works well with OMP threading. However, I am happy to leave it out of CICE6.

**Comment by eclare108213** [comment]
I'll close the issue.  We can change it later if the need arises.
