### ISSUE TITLE
Minor modifications required in documentation

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#951]
- Remove sentence: 'Here we assume that the top layer is thin enough.' in section 2.1
- the eqs in section 2.5 assume that the ice is in the northern hemisphere (f>0) for the water stress term when the turning angle is not zero. Need to mention it or modify the eqs to have a 'sign' variable for some terms (as done in the code).

**Comment by eclare108213** [comment]
JF's comment from #952: 
```
    The eqs in the doc in section 2.5 are correct for the northern hemisphere (with fm>0) for the water stress term. Hence, in the doc, waterx = uwcos(theta) - vwsin(theta). In the code, however, waterx = uwcos(theta) - vwsin(theta)*sign(c1,fm). We could do:

we add sign(c1,fm) in the doc for waterx, watery and ccb. But I find these eqs are already quite busy.
we mention that the formulation of the water stress is for the northern hemisphere and that the sin(theta) terms are multiplied by -1 in the code when the ice is in the southern hemisphere.
```

The documentation does not appear to define what all the symbols are in the equations, e.g. theta.  Since it is already simplified and the details are (or should be!) in the papers, I suggest putting a plus-or-minus symbol before the sin(theta) term and add a sentence that says something like "the sign of the sin(theta) term is hemisphere-dependent."

**Comment by apcraig** [comment]
So plus/minus goes in front of just the sin(theta) term associated with the ocean velocity turning term?  Is that right?

Should I add plus/minus to all equations or just to equation 2, note that it's hemisphere dependent.  Then also note the equations that follow do not have plus/minus but should?

**Comment by eclare108213** [comment]
Based on JF's comments, I think it would be on both equations in (2) for the velocity components, in front of (Vw-v)sin(theta).  Search for 'sign' in ice_dyn_shared.F90.
