### ISSUE TITLE
snow, ice evaporation

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#97]
Check for potential bug.  This might be easier (or already fixed) as part of the CMIP6/SIMIP history output (#93).  Alex West's original email:

Hello Elizabeth,
 
Hope that you’re well.  I’ve been having a go at adding two new diagnostics to CICE to report ice and snow evaporation separately – apart from being in the SIMIP data request, I think they may be useful for my PhD on the Arctic energy budget.  However, I’ve been having some unexpected problems, and wondered if there are aspects of the evaporation I’m still not aware of (and if I’ve come across a possible reason why this hasn’t been done before!).
 
Basically, I’ve
 
-          defined the new diagnostics, evap_ice_ai and evap_snow_ai, in the history routines in the normal way;
-          defined new aggregate and category fields evap_ice, evapn_ice etc in ice_flux;
-          added code to thickness_changes in ice_therm_vertical to calculate the fields evapn_ice, evapn_snow in the same way as evapn, and divide them by timestep length;
-          added the new evaporation fields to the routine merge_fluxes in in_flux.
 
It looks to my naive eye that the new fields are then calculated in much the same way as the existing evapn field.  However, when I look at the resulting diagnostic files, the new snow and ice evaporation fields are of a completely different order of magnitude to the total evaporation field (about 1.e3 bigger).  Moreover, the sum of the two new fields actually has a different structure to the total evaporation field.
 
Do you have any idea what I might be missing here?  I attach the copies of ice_flux, ice_step_mod, ice_therm_vertical, ice_history and ice_history_shared from my branch; unfortunately the output file with the three evaporation fields is too large to send by email.
 
Because this branch is a general ‘new diagnostics for SIMIP’ branch it also contains Dave Bailey’s new diagnostic changes, so a diff with the 5.1.2 trunk will show these differences also.

**Comment by dabail10** [comment]
I have added two new variables in CESM with the SIMIP request to do this. So, I believe this will be resolved when I bring the CMIP variables in.

**Comment by dabail10** [comment]
This is addressed in PR #182.

**Comment by dabail10** [comment]
Resolved in PR#191.
