### ISSUE TITLE
Deprecate ORCA grid

### ISSUE THREAD

**Issue by anton-seaice** [CICE-Consortium/CICE#983]
I suggest we deprecate the ORCA / CPOM grid code

Its [not a lot](https://github.com/search?q=repo%3ACICE-Consortium%2FCICE%20orca&type=code) of code, but does helps to keep things tidy (especially in `ice_read_write.F90` ).

**Comment by eclare108213** [comment]
I contacted Danny Feltham, who said that they are still running v5.1.2 occasionally but have mostly moved to SI3, so we can deprecate all of the CPOM grid code in v6.  I suspect that we can also deprecate the hadgem forcing data. Let's not simply delete it -- use the deprecation process (remove namelist options and make the code abort if someone tries to use it, without removing all the code, then finish deleting it later).  I'll add these to the deprecation table.

**Comment by anton-seaice** [comment]
Thanks E!

Is this the only code which uses the `tripoleT` grid format / norther boundary ?

**Comment by phil-blain** [comment]
>Is this the only code which uses the tripoleT grid format / norther boundary ? 

No, we also use `tripoleT` since this is what NEMO uses and we run coupled with NEMO, but do that without the `orca_halogrid` switch.
